### ISSUE TITLE
usb installation stuck at 0 on latest release

### ISSUE THREAD

**Issue by Zboubinou** [XorTroll/Goldleaf#109]
I tried usb install with tinfoil-57f2b27 and it was  stuck at 0%
Tried again with tinfoil-267ef5b (did it before a few times without trouble) and it worked.

Just for you to know (really good work btw)

**Comment by Sev73n** [comment]
me too I am in 6.1

**Comment by pjh4** [comment]
I am also having this issue with tinfoil-57f2b27 on the switch v6.1.0

**Comment by kkaazzee** [comment]
I ran into this as well. All is well after re-installed a build created just after macOS USB support was completed: https://bsnx.lavatech.top/tinfoil/tinfoil-4ba0159.zip

**Comment by ralsim** [comment]
i've tried the latest build and the build linked above, i get the same i'm yet to test other nsp's but i'm on 6.1 trying to install a 14gb nsp to a fat32 sdcard running the script from ubuntu 18

**Comment by Shift-X** [comment]
Ralsim,
If you're having problems try running it with sudo.
