### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by CVFireDragon** [XorTroll/Goldleaf#111]
I run make but it doesn't compile

**Comment by XorTroll** [comment]
Any specific error?

**Comment by CVFireDragon** [comment]
`Makefile:15: *** missing separator.  Stop.`

**Comment by XorTroll** [comment]
Fixed

**Comment by CVFireDragon** [comment]
yup that fixes it

**Comment by CVFireDragon** [comment]
Now I have a new error... `C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'SystemProgram' not handled in switch
[-Wswitch]
         switch(Type)
               ^
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'SystemData' not handled in switch [-W
switch]
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'SystemUpdate' not handled in switch [
-Wswitch]
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'BootImagePackage' not handled in swit
ch [-Wswitch]
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'BootImagePackageSafe' not handled in
switch [-Wswitch]
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'Application' not handled in switch [-
Wswitch]
C:/Users/Luke1/Downloads/Goldleaf-master/Goldleaf-master/Source/gleaf/horizon/Ti
tle.cpp:72:15: warning: enumeration value 'Delta' not handled in switch [-Wswitc
h]
linking Goldleaf.elf
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/8.2.0/../../../../aarch64
-none-elf/bin/ld.exe: cannot open output file C:/Users/Luke1/Downloads/Goldleaf-
master/Goldleaf-master/Output/Goldleaf.elf: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /home/Luke1/Downloads/Goldle
af-master/Goldleaf-master/Output/Goldleaf.elf] Error 1
make: *** [Makefile:159: Build] Error 2`

**Comment by ThatNerdyPikachu** [comment]
Fixed via PR #115
