### ISSUE TITLE
USB install works fine with regular titles, but crashes switch with DLCs and Updates (sometimes)

### ISSUE THREAD

**Issue by PabloZaiden** [XorTroll/Goldleaf#118]
USB install works fine with regular titles, but crashes switch with DLCs and Updates (sometimes)
I wasn't able to find an exact repro, but most of the times, installing Pokken or Zelda updates/dlcs, the console crashes leaving an broken installed title.

Current workaround I've found is usb-installing the main games, but going through sd card for dlcs and updates.

**Comment by chocomega** [comment]
Do you install them during the same batch ?
It also crashes sometimes when I install multiple NSP but so far if I install them one by one (pressing B to go back after each install) it doesn't crash.

**Comment by PabloZaiden** [comment]
No. First the game, then the Updates, then the DLCs.
It sometimes crashes with updates or DLCs. Even when going one by one.
If I install them from the SD card, there are no issues.
