### ISSUE TITLE
Warn on installing titles with dangerous permissions set

### ISSUE THREAD

**Issue by GerbilSoft** [XorTroll/Goldleaf#120]
There's a fake NSP going around purporting to be one of the "Pokémon: Let's Go" titles. If the user runs this title, it wipes the PRODINFO and PRODINFOF partitions, which effectively bricks the system (if they don't have a backup).

These partitions aren't writable by titles unless they have specific permissions that aren't normally present in games. In particular, bit 63 of the NPDM permission field grants "all" permissions to the title.

https://switchbrew.org/wiki/NPDM
https://switchbrew.org/wiki/Filesystem_services#Permissions

The user should be shown a warning if they're about to install a title that has either the "all" permissions bit set or a combination of "dangerous" permissions that aren't normally found in retail titles. (I haven't gone through all of the permissions bits, so I'm not sure which ones should be checked.)

Sidenote: I'm not sure if goldleaf has a GUI right now or there are plans, but if it does, an overlay icon should be added for these titles as well, similar to Windows' UAC shield.

**Comment by XorTroll** [comment]
I know it would be a good idea, but it's kinda complex to detect that.

**Comment by XorTroll** [comment]
I... don't plan on focusing on this aspect, at least for now
