### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [XorTroll/Goldleaf#123]
1. Delete title and ticket(s) option (base and updates could be deleted together, whilst dlc would be a separate title)
1. When on the ticket deletion menu, can the previously uninstalled tickets (in that session) be marked inactive so we can still see them?
1. Can the UI not have that fade in and out effect on every menu item change?

**Comment by ThatNerdyPikachu** [comment]
I could probably implement number 1 myself, if that's okay..

**Comment by XorTroll** [comment]
Submit a PR then
