### ISSUE TITLE
Darker menu buttons

### ISSUE THREAD

**Issue by lookye** [XorTroll/Goldleaf#125]
Please make the color a bit darker, especially within the install process, so that you can better see on which button you are at the moment.

**Comment by FutabaHoneyOTU** [comment]
how about a full on dark mode
(based on the option in system settings)

**Comment by XorTroll** [comment]
Themeing will come with v0.5, already a partial thing in latest commits.

**Comment by lookye** [comment]
I will close this as the dark menu (from your latest commits) is nice.
