### ISSUE TITLE
[Tinfoil 0.2.1] USB-Install not shown on fw 4.1.0

### ISSUE THREAD

**Issue by Zireael** [XorTroll/Goldleaf#128]
Hi,
I haven't tried Goldleaf yet, but using Tinfoil, so figured I'll make a report in case they share same ode.
Basically, I'm on fw 4.1.0 and using Tinfoil 0.2.1 with latest Kosmos/SDfiles build (Atmosphere).
I do not have option to do 'USB install' in my menus.
Friend has had the same issue (no option given) on fw 4.1.0, and was able to see the option for USB Install immediately after he upgraded to 5.1.0 with Choi.
Is 4.1.0 incapable of supporting USB install?

Another issue (not much to do with Tinfoil) we've had was not being able to install .ncps we've converted from .xci and again, as soon as friend upgraded to 5.1.0 that worked.

Thank you for your work!

**Comment by XorTroll** [comment]
Thanks, but I would suggest to place Tinfoil-related issues on Adubbz's repository.

**Comment by Raugo** [comment]
USB install don't work in firmwares lower that 5.0. In that firmware don't have the required functions https://switchbrew.org/wiki/USB_services#usb:ds

**Comment by ThatNerdyPikachu** [comment]
@XorTroll You cannot place issues on Adubbz's repository, as it has been archived.

**Comment by XorTroll** [comment]
Then try to ask Adubbz from any other place, sorry but this is no longer Tinfoil.
