### ISSUE TITLE
Goldleaf hangs when selecting option for USB Install

### ISSUE THREAD

**Issue by JimothyJones** [XorTroll/Goldleaf#142]
When going on the USB Install menu option, it just says "Starting Test" and seems to freeze, the only way I can exit the app is going back to the Home menu.

What’s weird is I’ve had it get past that part before, and working with GoldTree on windows, though the process froze after I selected the NSP to load.

But now I can’t even get it past the aforementioned stage and GoldTree (or the Zadig tool) doesn’t recognise it.

Any idea what’s up?

**Comment by XorTroll** [comment]
Have you installed libusbK via Zadig? Are you on Windows? (I guess you are)

**Comment by JimothyJones** [comment]
I think so, as I’ve had the Switch recognised by Goldtree once in the past?

But even if it’s not installed, I can’t install it as Zadig doesn’t see my switch when I connect it whilst in Goldleaf's USB Install mode.

**Comment by JimothyJones** [comment]
Closing this as managed to get it going, having a different issue now where Goldtree seems stuck on "Goldleaf is ready for the installation. Preparing everything." Opening a new issue for this.
