### ISSUE TITLE
Goldtree seems stuck on "Goldleaf is ready for the installation. Preparing everything."

### ISSUE THREAD

**Issue by JimothyJones** [XorTroll/Goldleaf#143]
Goldleaf and Goldtree recognise eachother, but now when running Goldtree, after selecting an NSP it says "Goldleaf is ready for the installation. Preparing everything."

It seems to stay there indefinitely.

Have tried with different NSPs and result is the same.

Any advice? Running on windows 10, and Switch 6.2 Atmosphere 1.7.5

**Comment by JimothyJones** [comment]
GoldTree says "Goldleaf is ready for the installation. Preparing everything."

GoldLeaf says "Connection request was received from a Goldtree PC Client. Sending confirmation and waiting to select an NSP …"

I have already selected an NSP.

**Comment by ThatNerdyPikachu** [comment]
Goldleaf's USB functionality is not fully implemented yet.

Please wait for an official release, or until the implementation is complete.

**Comment by JimothyJones** [comment]
Ok no problem, will mark this as closed then. Thank you!
