### ISSUE TITLE
Console is crashing while deleting files

### ISSUE THREAD

**Issue by lookye** [XorTroll/Goldleaf#147]
**FW:** 6.2
**CFW:** ReiNX 2.0

When browsing the SD Card and deleting files (doenst matter if nro / nsp or folders) after some deleted files, the console will crash.

**Error Code:** 2168-0002

EDIT: I´m using the latest Build from lavatech

**Comment by XorTroll** [comment]
I'm going to make a commit in a few minutes, try that build when it gets built.

**Comment by XorTroll** [comment]
Another doubt, did it always crash with an specific format, like all of them normal / unsupported formats or something?

**Comment by lookye** [comment]
Tried it with invisible files like **.**Goldleaf.nro or normal folders.

**Comment by lookye** [comment]
Sorry misclicked and closed it.

**Comment by lookye** [comment]
The error is fixed for normal files/folders.
But it´s still crashing after about 3 invisible files with a (.)dot in front of the filename.

**Comment by XorTroll** [comment]
Does v0.2 crash too?

**Comment by lookye** [comment]
Tried it with the official 0.2 from the release Tab.
Deleted as a test 4 files from root and one in a folder.
No crash happened. Seems the bug was fixed. Thanks.
