### ISSUE TITLE
USB install fails when enumerating devices (Program.cs L105)

### ISSUE THREAD

**Issue by lyptt** [XorTroll/Goldleaf#150]
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

**Comment by XorTroll** [comment]
This issue is weird. Any more details, did you have many USB devices, Switch connected or not...?

**Comment by lyptt** [comment]
Nah, just keyboard and mouse. Switch is connected as instructed in Goldleaf. I've got the driver installed for TegraCrmGui to work too.

In device manager, the correct device is listed with the expected USB device ID.

**Comment by XorTroll** [comment]
So what happened, did Goldtree throw that error and close or something?
I've done many USB tests and never got that error, nor any other testers got it.

**Comment by lyptt** [comment]
Yup. It reports that it's failed to find the correct USB device, but under the hood this is an issue with the native DLL accessing uninitialised memory.

**Comment by XorTroll** [comment]
Have you done any USB installs previously?

**Comment by lyptt** [comment]
Nope, first time today

**Comment by XorTroll** [comment]
Ao you said you have the driver installed with TegraGui...
Did you select the correct interface, which should be the Switch plugged in with Goldleaf opened?

**Comment by lyptt** [comment]
I never managed to reach the point of selecting anything. Goldtree immediately exits every time, both normally and in administrator mode.

**Comment by XorTroll** [comment]
Any news?

**Comment by jja2000** [comment]
Goldtree still can't detect my switch it seems, I have the libusbK driver installed with goldleaf opened. Goldleaf detects a usb connection, but goldtree still can't find it. The device shows up in device manager on windows.

I'm running Windows 10 on the host and FW3.0.0 with ams 0.8.7 on the switch
