### ISSUE TITLE
Crash after browsing NAND (NRO)

### ISSUE THREAD

**Issue by lookye** [XorTroll/Goldleaf#151]
FW: 6.2
CFW: SX 2.5
Version: Goldleaf RC 0.1

A friend browsed NAND, went to SAFE partition, pressed "back" and it crashed.
Error was not reproducible.

**Comment by andmaltes** [comment]
FW 6.2.0
CFW ReINX
Goldleaf NSP

Same here. I went to NAND and explored SAFE, then USER and then SYSTEM. Pressed back and when browsing sd card, it crashed.
In the same way, I was not able to reprodice the error again.

**Comment by XorTroll** [comment]
Sometimes browsing can have crashes, will try to fix them

**Comment by newget** [comment]
After exploring SAFE, nothing appears in other partitions too.
Then crash

**Comment by XorTroll** [comment]
Does v0.2 crash too?

**Comment by newget** [comment]
Browsing SAFE, nothing appears.
After browsing SAFE, every partitions show nothing.
Try System, User, Sdcard then crash.

**Comment by XorTroll** [comment]
So on v0.2 too? All those random crashes were corrected on v0.2
