### ISSUE TITLE
Error when trying to install a .nsp

### ISSUE THREAD

**Issue by Oscartwest** [XorTroll/Goldleaf#152]
Whenever I try to install a nsp via USB(also get this error when installing from sd card, but it is a different error code) I get this error:

Failed to open the meta NCA (CNMT NCA) within the NSP. (error code 0x202)

FW: 6.2.0
CFW: Atmosphere 8.2

**Comment by kingafro000** [comment]
I have been having this same issue. My error code has been 0x234c02 but says the same thing. I wasn't even able to install the Goldleaf .nsp.

FW: 6.2.0-10
CFW: Atmosphere 8.2

**Comment by Oscartwest** [comment]
Thank you that fixed it.

**Comment by jtviolet** [comment]
@XorTroll Can you elaborate on the signature patches? What is required to implement those once they are on your device?

**Comment by XorTroll** [comment]
Cosmos has the required stuff, not trying to promote it but I've always used it and never had issues with nsps

**Comment by vaicius** [comment]
I keep getting Error: 2002-4517 (0x234A02) when I try to install split NSPs from SD card. I upload them to SD card using VM windows 10. Split NSP files using "SplitNSP-Swift-GUI" for macOS or "NSPsplitty" on windows 10. I'm on a system version 9.0.1 | AMS 0.9.4|S.
