### ISSUE TITLE
Still crashes on 6.0...

### ISSUE THREAD

**Issue by CVFireDragon** [XorTroll/Goldleaf#153]
Well, the .nsp works if I install it with DevMenu; but the .nro just crashes my Switch...

**Comment by XorTroll** [comment]
Any more detailed info?

**Comment by CVFireDragon** [comment]
Well, I got the nro from releases. It didn't show an author or anything and crashed my Switch (I use Kosmos). I updated to the latest release of Kosmos, and then I saw an icon and author. It also crashed my Switch. Thats about it

**Comment by XorTroll** [comment]
Does v0.2 crash too?

**Comment by CVFireDragon** [comment]
nope, not for me
