### ISSUE TITLE
Deleting files from SD card does not update file list

### ISSUE THREAD

**Issue by MCFX2** [XorTroll/Goldleaf#155]
FW: 6.0.1
Installed as NSP via old Tinfoil
SD card is a 400GB exFAT card.

When I delete a file (in my cases, NSPs) from the title installation menu, it does not update the file list and still shows the deleted file. This persists even if Goldleaf is completely closed and re-opened. The only way to get a correct file list is to completely restart my system. Plugging into my PC verifies the files were in fact deleted correctly.

If you delete an NSP this way and then attempt to install it, you get a crash (duh) that takes you back to the home menu. If you attempt to delete the file again, it simply does nothing and returns you to the file list.

**Comment by MCFX2** [comment]
Some quick additional testing reveals this is specifically a problem with the "Install and delete" option. Deleting a file that you did not first install has no issues, and if Goldleaf crashes after installing an NSP or is closed then you can delete it normally.

**Comment by XorTroll** [comment]
Yeah this is a bug, the option of install and delete doesn't seem to delete the file.

**Comment by duckyb** [comment]
Also, simply using "Install" and after using the "Delete" function won't work
