### ISSUE TITLE
unable to establish usb connection on linux

### ISSUE THREAD

**Issue by itapai** [XorTroll/Goldleaf#156]
On the switch i have: usb connection detected. Open goldtree to connect it via usb
but when i try to open goldtree via mono ( mono goldtree ) i get the following output:

```
Goldtree.v0.1]$ mono Goldtree.exe
    Goldtree - Goldleaf's USB installation client
    Copyright (C) 2018 - Goldleaf project, by XorTroll

[gtree:Warn] Make sure to open Goldtree after having launched Goldleaf on your console. Waiting for connection...

[gtree:Error] No USB connection was found. Make sure you have Goldleaf open before running Goldtree.
Press any key to exit...
```

I know its still early days, but support for linux ( via mono ) is desireable ;)

**Comment by Crissal1995** [comment]
Support for linux and osx is coming, but (for now) Goldtree relays on libusbK (only Windows)

**Comment by pdalfarr** [comment]
> Support for linux and osx is coming, but (for now) Goldtree relays on libusbK (only Windows)

Hope this will arrive soon ;-)
