### ISSUE TITLE
Install multiple NSP's using Goldtree

### ISSUE THREAD

**Issue by Migushthe2nd** [XorTroll/Goldleaf#158]
Goldtree only supports selecting and installing one NSP at a time. Being able to select multiple files like the old Tinfoil will save a lot of time.

**Comment by PurpleMyst** [comment]
Another request: If installing multiple NSPs, sort them by base game -> update -> DLCs.

**Comment by Niekvdm** [comment]
@XorTroll I've made a fork of your Goldtree source and added a WebGUI around it to add support for multi-install.
For now it requires manually action in the Goldleaf app but it works... Are you working on multi support inside the Goldleaf app?

**Comment by XorTroll** [comment]
I was working on other features, but the idea looks nice

**Comment by XorTroll** [comment]
Pretty sure USB will get a rewrite soon tbh

**Comment by sepuvk** [comment]
+1

**Comment by sepuvk** [comment]
@XorTroll +1

**Comment by AssisrMatheus** [comment]
@XorTroll +1

**Comment by XorTroll** [comment]
Added for all filesystems :)

**Comment by delize** [comment]
Is there a guide that explains how to do this? I am still not sure how to go about doing this.
