### ISSUE TITLE
Add an "Exit" or "Back" button functionality in USB Installation Mode

### ISSUE THREAD

**Issue by bbatod** [XorTroll/Goldleaf#161]
Right now, if you enter USB Installation mode, you cannot go back or exit Goldleaf unless you click on Home button and relaunch Goldleaf through Homebrew Menu again. 

Also, this seems to be causing issues with Goldtree detecting the Goldleaf client.

**Comment by newget** [comment]
We really need this.

**Comment by XorTroll** [comment]
Agree, but it's libnx fault for their system to wait for connection

**Comment by Crissal1995** [comment]
Can't you use a thread for waiting response?

**Comment by XorTroll** [comment]
This is a WIP idea as on v0.5 USB is being handled in a different way, so might partially fix this.

**Comment by XorTroll** [comment]
Whoops, closed by mistake

**Comment by ToppestOfDogs** [comment]
I really need this, more often than not I'll get stuck on the USB screen with no way to get out, because the NSP version doesn't let you press home if it thinks it's doing an install, so I just have to hard reboot.

**Comment by XorTroll** [comment]
With the new system this works, since it's a filesystem and one can go back.
