### ISSUE TITLE
Allow management of individual updates

### ISSUE THREAD

**Issue by noahc3** [XorTroll/Goldleaf#163]
DevMenu's last useful feature is that you can uninstall individual updates for games without uninstalling the whole title. Having this feature in Goldleaf would be great.

Edit: With this would probably need to be a reset required version feature to be useful, also present in DevMenu but not in GoldLeaf.

**Comment by RiPPERD** [comment]
this would be great!! i stupidly installed a load of chineese updated for a game that was EU and had to start again!
would also be good if it could check if the update is compatible with title
