### ISSUE TITLE
Transfer a file/folder via USB

### ISSUE THREAD

**Issue by satelliteseeker** [XorTroll/Goldleaf#165]
It could be very helpful if the file manager supports:
- Receive a file/folder from Goldtree and save at current location
- Send selected file/folder to Goldtree and save on PC

This would save a lot of hassle on rebooting-and-RCMing Switch for basic file transfer operations. Now the only solution to transfer files when Switch is on has been FTP, but it's unstable with exFAT-formatted SD cards and doesn't work for users who have disabled Wi-Fi.

If it's not practical to transfer a folder, the feature to zip and unzip any folder can be an alternative (currently NX-Shell supports unzip only). it should also set a limit on file size if FAT32-formatted SD card is detected.

**Comment by XorTroll** [comment]
To be honest this looks like a nice idea

**Comment by kowaiser** [comment]
I have been looking for some way to do this. USB installs are buggy and the router is away from the PC, so FTP transfers are difficult.

**Comment by XorTroll** [comment]
This might be done, a system to transfer files via USB

**Comment by DavidOliM** [comment]
I think it would be nicer if it just connected to the PC as a mass storage device

**Comment by XorTroll** [comment]
With 0.6's PC-over-USB system this idea + NSP installs get unified, so done :)
