### ISSUE TITLE
Add option to switch between 12H/24H time

### ISSUE THREAD

**Issue by smurfhunter** [XorTroll/Goldleaf#167]
Others on reddit have complained, so I figured I would put an issue here, even though it's a low priority fix.
https://reddit.com/r/SwitchHacks/comments/ab221r/release_goldleaf_with_12_hour_time/

**Comment by XorTroll** [comment]
Somehow never saw the issue, so will set this as something possible to be configured from settings.

**Comment by XorTroll** [comment]
Took a while, but added it in last commit ;)
