### ISSUE TITLE
Multiple Issues and feature requests

### ISSUE THREAD

**Issue by RiPPERD** [XorTroll/Goldleaf#168]
Hello thank for continued updates etc im new to the switch scene but look me up im not a n00b
Heres my 2 cents anyway...

My Switch:
Switch - 6.2.0 - Atmosphere 0.82 - Loader from pc via paperclip

Issues to be fixed from my experience: SD ONLY - haven't touched the nand browser dont trust myself yet lol
1. Install & Delete - This doesn't work correctly - doesn't delete files
2. Options - Delete - This will delete sometimes but since 0.2 update it crashes my system with ASOD (atmosphere screen of death) lol 
The issue seems to be related to having a lot of files on the directory as didnt happen before i added around 30 nsp files... maybe you need to change cache settings or similar? This only happened once i clicked options and delete and i could tick items... as soon as i clicked 1 item it freezes and dies.

New Features/Requests:
1. Some sort of tick or INSTALLED option so we know if its already been installed
If i have loads of dlc or updates then i loose track of where im up to.
2. Installing update - check that it is for the game installed same for dlc would be good
3. uninstall updates 1 by 1 not the entire game and updates 

I will update this as i find other things

RiPPERD

**Comment by MCFX2** [comment]
The point of issues is that each one covers one topic. Suggest closing this and opening a separate issue for each item.
> Install & Delete - This doesn't work correctly - doesn't delete files

This is known, see #155 .
> Options - Delete - This will delete sometimes but since 0.2 update it crashes my system with ASOD (atmosphere screen of death)

This should be its own issue.

> Some sort of tick or INSTALLED option so we know if its already been installed
If i have loads of dlc or updates then i loose track of where im up to.

See #14 

> Installing update - check that it is for the game installed same for dlc would be good
uninstall updates 1 by 1 not the entire game and updates
These should both be their own separate issues.
