### ISSUE TITLE
Goldleaf 0.2 USB does not recognize switch on lower firmware

### ISSUE THREAD

**Issue by shedeus** [XorTroll/Goldleaf#171]
Goldleaf NRO 0.1 recognizes my 3.0.1, 3.0.0, and 2.3.0 switches and performs USB install properly (with occasional freezes).

When I upgrade to Goldleaf 0.2, only my 6.1.0 switch performs USB install, while all other lower firmware switches are not recognized with this error message from Goldtree 0.2:

"[gtree:Warn] Make sure to open Goldtree after having launched Goldleaf on your console. Waiting for connection...

[gtree:Error] No USB connection was found. Make sure you have Goldleaf open before running Goldtree.
Press any key to exit..."

I am using Kosmos 11.7 and Atmosphere 0.8.2 on all switch consoles.
Thanks for your awesome work on this by the way!

**Comment by XorTroll** [comment]
USB only works on 5.0.0+

**Comment by shedeus** [comment]
Ok, thanks for confirming.  I will stick with Goldleaf 0.1 on all switches with lower firmware since USB install works fine on 3.0.0 and lower.

Thanks!!
