### ISSUE TITLE
(Feature Request) Android build

### ISSUE THREAD

**Issue by CCF100** [XorTroll/Goldleaf#172]
Is it possible to make a build of goldtree for Android?

**Comment by XorTroll** [comment]
Sending NSPs from Android?
Really?

**Comment by Niekvdm** [comment]
I see a challenge

**Comment by CCF100** [comment]
Explain, @XorTroll

**Comment by lookye** [comment]
I think (And I think XorTroll and ThatNerdyPikachu are thinking the same), why should someone develop an Android App to send files via USB C (phone to console) or wifi?
It´s a useless feature and too much work to do so.

I think this "issue" can be closed, don´t you think?

**Comment by CCF100** [comment]
But you can push payloads with an Android phone just fine... The switch and android can communicate with each other just fine...

**Comment by lookye** [comment]
Different protocols are used to push the payload in comparison with transfering files. You´re argument is invalid. Please think about it. Its not: Connect both, select a file and go. There is much more coding to do. Also Goldleaf needs to be rewritten to accept files it they were send via Android App.

Then, coding an Android App is something else than coding a small PC app to push files or Goldleaf.
If you want it, you can write an App, thats working on all Android Apps (Different phone models, different Android versions, different errors can happen).

Please close this "issue".

**Comment by XorTroll** [comment]
Unless somebody does this, this won't be done. I'm not going to write an Android client, I see it kinda pointless

**Comment by Agash** [comment]
I might see myself making a real quick and dirty Xamarin app for those who really want this (even tho i think it's pointless), depending on the .net core version of Goldtree and it's specific implementation. So might or might not happen.
This issue tho can be closed can't it?

**Comment by XorTroll** [comment]
Pointless, so yes.
