### ISSUE TITLE
Add exit button in main menu

### ISSUE THREAD

**Issue by SegFault42** [XorTroll/Goldleaf#174]
just add a button to exit goldleaf in main menu

**Comment by crazyp187** [comment]
You can just press + to exit Goldleaf

**Comment by SegFault42** [comment]
not working with the nsp version

**Comment by Thetoto** [comment]
You cannot exit a title.

**Comment by XorTroll** [comment]
> not working with the nsp version

Read the README carefully and stop making pointless issues, please.
