### ISSUE TITLE
File browser issues

### ISSUE THREAD

**Issue by Crissal1995** [XorTroll/Goldleaf#183]
1. Cwd and footer text, when are too long, goes to a new line. Cwd small collide with the file box, so it's not so messy (but two pixels above is better), while footer goes off the screen
2. If file is selected to copy and then deleted, Goldleaf crash
3. If file is selected to copy and then its folder is deleted, Goldleaf crash
4. "Console Information" and "About Goldleaf" are the only two menu items that can be exited without pressing B; you can press any button (A will reload the same screen) and even touch the screen to discard them [P.S. the arrows/sticks will work as movement too]

Issue 1. related:
![2019011419200700-da63280140b1530cd17755515d814cfe](https://user-images.githubusercontent.com/9823755/51132533-bf64da80-1832-11e9-8d61-680a278b09cd.jpg)

**Comment by XorTroll** [comment]
1 - thanks, will try to fix that
2 - ^ (I thought this was fixed tho)
3 - ^
4 - I've done that on purpose

**Comment by Crissal1995** [comment]
For 1, if I can suggest you a solution, is to just raise a little the text for cwd and to trim text for footer
For 4, oh I always thought it was a bug ahahah ok perfect (if I can suggest this too, block the A button, cause the screen flickers)

**Comment by Crissal1995** [comment]
BTW, if it matters, I tested this from nro

**Comment by XorTroll** [comment]
I assume most of this features are fixed for 0.7.1.
