### ISSUE TITLE
USB installitation on macOS fail with usb.core.USBError: [Errno 84] Overflow

### ISSUE THREAD

**Issue by EddyCR** [XorTroll/Goldleaf#186]
Hello,

OS Version: macOS Mojave.
After selecting the nsp to install from the list in the USB installation screen and doing the regular installation process with tinfoil the switch stays in the % installation screen with 0 processes and the terminal on mac throws this:
![image](https://user-images.githubusercontent.com/5322460/51214450-98b2ac80-18e3-11e9-82c6-e3fee6a5a8fd.png)

I have followed the instructions stated on the usb_install_pc.py, and I have installed and reinstalled several times what it's defined in there and I have tried with differents nsp files it's always the same error.

**Comment by Agash** [comment]
The usb_install_pc.py script was for old Tinfoil. You need to use Goldtree. Here's is a python implementation of it:
https://github.com/friedkeenan/GoldtreePy

**Comment by Agash** [comment]
This is the repository for Goldleaf not Tinfoil, just fyi.
Try out Fluffy, I use it on my mac and it works flawless with Goldleaf, it has support for the old Tinfoil too: https://github.com/fourminute/Fluffy
There's a recommended Tinfoil.nro, use that one and follow the instructions for MacOS.

**Comment by EddyCR** [comment]
Understood, Thank you for your help

**Comment by Agash** [comment]
@XorTroll I guess this can be closed?

**Comment by XorTroll** [comment]
Yup
