### ISSUE TITLE
The Delete File option doesn't actually do anything on any NSP (that I just installed)

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [XorTroll/Goldleaf#189]
It says it deleted the file, but it didn't. Latest release, 0.2

(Works fine on any other file)

**Comment by Strat00s** [comment]
Hurray. I am not the only one. Still happening on 0.3.

**Comment by hacheraw** [comment]
Same on Goldleaf 0.4 @ latest Reinx on 6.2

**Comment by XorTroll** [comment]
Fixed on v0.5! It was all unmanaged stuff, but v0.5 will have this fixed too!
