### ISSUE TITLE
[Enhancement] Check NSP before installation like in tinfoil

### ISSUE THREAD

**Issue by FutabaHoneyOTU** [XorTroll/Goldleaf#191]

**Comment by XorTroll** [comment]
Check what?

**Comment by deadair3210** [comment]
I think they mean check the validity of the nsp sort of like the verify nsp option in tinfoil

**Comment by XorTroll** [comment]
NSP information is displayed after selecting several options like location and fw version ignore, and if the NSP is invalid it won't be read correctly and Goldleaf will warn about that. Isn't this enough checking?

**Comment by FutabaHoneyOTU** [comment]
> NSP information is displayed after selecting several options like location and fw version ignore, and if the NSP is invalid it won't be read correctly and Goldleaf will warn about that. Isn't this enough checking?
well i never encountered a bad nsp so i didnt know this was a thing, since it's already a feature i'll close this
