### ISSUE TITLE
[Feature Request] Progress bar during file/folder transfers

### ISSUE THREAD

**Issue by 16BitWonder** [XorTroll/Goldleaf#192]
I was trying to transfer a folder with a few hundred MB worth of files over to another location, and without any indications otherwise I assumed it had frozen during the transfer.

I know that the majority of transfers probably won't deal with numerous large file sizes like this, but for those that do a progress bar would be nice to see that it's still working.

**Comment by XorTroll** [comment]
Copies and pastes now have progress
