### ISSUE TITLE
Goldleaf does not support non-A-Z letters

### ISSUE THREAD

**Issue by TheZett** [XorTroll/Goldleaf#195]
It seems that GoldLeaf does not support any letter that is not one of the standard 26 latin letters.

They keyboard layouts also do not display them, even if the layout is supposed to have them (e.g. QWERTZ is supposed to show A-Z alongside äöüß).

I noticed that barely any Switch homebrew supports non-A-Z letters (such as ÄÖÜẞäöüß), so that might be a deeper problem, which is not specific to Goldleaf itself.

**Comment by ThatNerdyPikachu** [comment]
It's due to how the FS sysmodule works, this will really never be fixed...

**Comment by XorTroll** [comment]
UI limitation + FS service limitation, however Plutonium already supports UTF16 so can be done
