### ISSUE TITLE
Changing user image not working

### ISSUE THREAD

**Issue by brandonbryan12** [XorTroll/Goldleaf#196]
In v0.3
I've attempted to change my user image a few times, but it reverts back to the old image.

Steps to reproduce:
* Visit the change user image option in Goldleaf
* Find file that needs to be swapped on sd card
* Mount sd card on pc and swap the old image with new image
* Insert sd card into switch and boot
* See old user image again
* Mount SD card back on pc and see the old image replaced the new image

**Comment by XorTroll** [comment]
What did you 3xactly do? Swap a file? You need to select the JPG in the sd card and select replace, no need to swap any file

**Comment by brandonbryan12** [comment]
Do I need to do this in the Goldleaf GUI? I manually replaced when mounted on Windows

**Comment by XorTroll** [comment]
Yeah, select the JPG in the sd card browser and select the option to replace icon

**Comment by brandonbryan12** [comment]
Does the file need to be 128x128? I used a different resolution and my user icon is now just white

**Comment by XorTroll** [comment]
I should clarify this, like with titles the icon should (must) be 256x256

**Comment by brandonbryan12** [comment]
I reformatted the image to 256x256 and the white screen issue is still occurring. Here is the image I'm using [https://drive.google.com/file/d/1W4vH5hPZY8C3Q0eSAmkLTmlrYNvhsI3z/view?usp=sharing](url)

**Comment by VinyLimaZ** [comment]
That's the same that happened to me!
I copied the jpeg of the profile, edited as I wanted, and saved, in the GUI I selected the image to change the profile and rebooted.
When the system went back, only the image of profile selection (when you open a game) is with my image (that's fine), but the image of the bubble top and the image inside the profile applet show a white image D:
Any error, just don't show up the image on all places

**Comment by MrCheeze446** [comment]
I'm also having an issue with this, tried to replace the image and crashed. now everytime i try to replace the image back to the original or go into an app that uses user icons it softlocks my switch and i have to hard reboot

**Comment by XorTroll** [comment]
v0.5 will be more strict with the selected image.
Which kind of icons did you specially? Big ones, icon size...?

**Comment by MrCheeze446** [comment]
The icon i tried using was not properly sized (i was unaware it had to be a different size), it was a jpg and if you want i can upload the one i tried to set

**Comment by jaconfurz** [comment]
@ MrCheeze446. I have the same problem with my switch. I installed a icon larger than 256x256. Now my switch crashes whenever anything with the user applet is pulled up.

Have you been able to fix your problem yet?

**Comment by MrCheeze446** [comment]
i was indeed able to fix this issue by resetting the console, goldleaf for setting the user icon works just fine if it's the right size

**Comment by jaconfurz** [comment]
You fixed it by resetting the console? What do you mean "reset"? You flashed a backup of your NAND? 

I'm hoping to fix this problem without doing a reset.

**Comment by MrCheeze446** [comment]
flashing a nand backup from before the image was broke should work!

**Comment by XorTroll** [comment]
Make sure the images for this are 256x256 and valid JPEGs. Goldleaf does check size and format, but watch out anyway.

**Comment by null-von-sushi** [comment]
Leaving this here in case anyone else also finds this issue while searching for a way to change profile pictures:

JPEGs, even ones with the correct size, created by GIMP did not work for me. Maybe mspaint.exe or whatever macOS comes with will work, I am not sure. 
What did work for me was:

1) export current profile picture using goldleaf
2) Go to [pixlr.com](https://pixlr.com/x/) and upload the old profile picture, create a new layer and in that layer upper layer upload your new profile picture (I used one created with GIMP and the correct size). 
3) Click save at the bottom and download the image as a JPG file.

The JPG file pixlr gave me worked for me without issues. I am not sure why files created with GIMP did not work.
