### ISSUE TITLE
Generate.bat file for Ubuntu

### ISSUE THREAD

**Issue by Ninoh-FOX** [XorTroll/Goldleaf#198]
this is the Generate.bat to ubuntu sh Generate :

`#!/bin/sh
#IMPORTANT! Place keys.dat at "BuildTools/keys.dat"!
chmod +x BuildTools/hacpack
rm ExeFs/main >nul 2>nul
rm --r Output
make clean
make
mv Output/Goldleaf.nso ExeFs/main
rm Output/Goldleaf.nso >nul 2>nul
rm Output/Goldleaf.nsp >nul 2>nul
rm --r Build.program
rm --r Build.control
rm --r Build.html
rm --r Build.meta
rm --r Build.nsp
rm --r BuildTools/Build.program
rm --r BuildTools/hacpack_backup
rm --r BuildTools/hacpack_temp
rm --r hacpack_backup
BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype program --titleid 050032A5CF12E000 --exefsdir=ExeFs --romfsdir=RomFs --logodir=Logo --outdir=Build.program
BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype control --titleid 050032A5CF12E000 --romfsdir=Control --outdir=Build.control
BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype manual --titleid 050032A5CF12E000 --romfsdir=OfflineHtml --outdir=Build.html
BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype meta --titleid 050032A5CF12E000 --titletype application --programnca Build.program --controlnca Build.control --htmldocnca Build.html --outdir=Build.meta
mkdir Build.nsp
mv Build.program/*.nca --target-directory=Build.nsp
mv Build.control/*.nca --target-directory=Build.nsp
mv Build.html/*.nca --target-directory=Build.nsp
mv Build.meta/*.nca --target-directory=Build.nsp
rmdir Build.program
rmdir Build.control
rmdir Build.html
rmdir Build.meta
BuildTools/hacpack -k BuildTools/keys.dat --type nsp --titleid 050032A5CF12E000 --ncadir=Build.nsp --outdir=Output
mv Output/050032a5cf12e000.nsp Output/Goldleaf.nsp
rm --r Build.nsp
rm --r hacpack_backup`

**Comment by 2767mr** [comment]
If you want to submit changes or new files I'd recomend opening a pull request.

**Comment by HaxXorHardy** [comment]
> #!/bin/sh
> #IMPORTANT! Place keys.dat at "BuildTools/keys.dat"!
> chmod +x BuildTools/hacpack
> rm ExeFs/main >nul 2>nul
> rm --r Output
> make clean
> make
> mv Output/Goldleaf.nso ExeFs/main
> rm Output/Goldleaf.nso >nul 2>nul
> rm Output/Goldleaf.nsp >nul 2>nul
> rm --r Build.program
> rm --r Build.control
> rm --r Build.html
> rm --r Build.meta
> rm --r Build.nsp
> rm --r BuildTools/Build.program
> rm --r BuildTools/hacpack_backup
> rm --r BuildTools/hacpack_temp
> rm --r hacpack_backup
> BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype program --titleid 050032A5CF12E000 --exefsdir=ExeFs --romfsdir=RomFs --logodir=Logo --outdir=Build.program
> BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype control --titleid 050032A5CF12E000 --romfsdir=Control --outdir=Build.control
> BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype manual --titleid 050032A5CF12E000 --romfsdir=OfflineHtml --outdir=Build.html 
> BuildTools/hacpack -k BuildTools/keys.dat --type nca --ncatype meta --titleid 050032A5CF12E000 --titletype application --programnca Build.program --controlnca Build.control --htmldocnca Build.html --outdir=Build.meta
> mkdir Build.nsp
> mv Build.program/*.nca --target-directory=Build.nsp
> mv Build.control/*.nca --target-directory=Build.nsp
> mv Build.html/*.nca --target-directory=Build.nsp
> mv Build.meta/*.nca --target-directory=Build.nsp
> rmdir Build.program
> rmdir Build.control
> rmdir Build.html
> rmdir Build.meta
> BuildTools/hacpack -k BuildTools/keys.dat --type nsp --titleid 050032A5CF12E000 --ncadir=Build.nsp --outdir=Output
> mv Output/050032a5cf12e000.nsp Output/Goldleaf.nsp
> rm --r Build.nsp
> rm --r hacpack_backup

this for better reading.
