### ISSUE TITLE
Add install and delete option

### ISSUE THREAD

**Issue by CiroMeiraLins** [XorTroll/Goldleaf#20]
Add install and delete option

**Comment by FinnYoung** [comment]
and "install and delete all" please

**Comment by duckbill007** [comment]
`
diff --git a/include/mode/install_nsp_mode.hpp b/include/mode/install_nsp_mode.hpp
index fcdc415..04bcf92 100644
--- a/include/mode/install_nsp_mode.hpp
+++ b/include/mode/install_nsp_mode.hpp
@@ -12,6 +12,7 @@ namespace tin::ui
             std::string m_name;
             FsStorageId m_destStorageId = FsStorageId_SdCard;
             bool m_ignoreReqFirmVersion = false;
+            bool m_deleteAfterInstall = false;
 
         public:
             InstallNSPMode();
@@ -20,5 +21,6 @@ namespace tin::ui
             void OnNSPSelected();
             void OnDestinationSelected();
             void OnIgnoreReqFirmVersionSelected();
+            void OnDeleteAfterInstallSelected();
     };
-}
\ No newline at end of file
+}
diff --git a/source/mode/install_nsp_mode.cpp b/source/mode/install_nsp_mode.cpp
index 36efa5d..b64c907 100644
--- a/source/mode/install_nsp_mode.cpp
+++ b/source/mode/install_nsp_mode.cpp
@@ -102,6 +102,29 @@ namespace tin::ui
 
         auto optStr = prevView->GetSelectedOptionValue()->GetText();
         m_ignoreReqFirmVersion = (optStr == "Yes");
+
+        auto view = std::make_unique<tin::ui::ConsoleOptionsView>();
+        view->AddEntry("Delete file after install", tin::ui::ConsoleEntrySelectType::HEADING, nullptr);
+        view->AddEntry("", tin::ui::ConsoleEntrySelectType::NONE, nullptr);
+        view->AddEntry("No", tin::ui::ConsoleEntrySelectType::SELECT, std::bind(&InstallNSPMode::OnDeleteAfterInstallSelected, this));
+        view->AddEntry("Yes", tin::ui::ConsoleEntrySelectType::SELECT, std::bind(&InstallNSPMode::OnDeleteAfterInstallSelected, this));
+        manager.PushView(std::move(view));
+    }
+
+    void InstallNSPMode::OnDeleteAfterInstallSelected()
+    {
+        // Retrieve previous selection
+        tin::ui::ViewManager& manager = tin::ui::ViewManager::Instance();
+        ConsoleOptionsView* prevView;
+
+        if (!(prevView = dynamic_cast<ConsoleOptionsView*>(manager.GetCurrentView())))
+        {
+            throw std::runtime_error("Previous view must be a ConsoleOptionsView!");
+        }
+
+        auto optStr = prevView->GetSelectedOptionValue()->GetText();
+        m_deleteAfterInstall = (optStr == "Yes");
+
         std::vector<std::string> installList;
 
         if (m_name == "Install All")
@@ -151,6 +174,16 @@ namespace tin::ui
                 fprintf(stdout, "%s", e.what());
                 break;
             }
+
+            if (m_deleteAfterInstall)
+            {
+                FsFileSystem sdcard;
+                fsMountSdcard(&sdcard);
+                std::string nspPath = "/tinfoil/nsp/" + installList[i];
+                nspPath.reserve(FS_MAX_PATH);
+                fsFsDeleteFile(&sdcard, nspPath.c_str());
+                fsFsClose(&sdcard);
+            }
         }
 
         printf("Done!\n\nPress (B) to return.\n");
`

**Comment by duckbill007** [comment]
```
diff --git a/include/mode/install_nsp_mode.hpp b/include/mode/install_nsp_mode.hpp
index fcdc415..04bcf92 100644
--- a/include/mode/install_nsp_mode.hpp
+++ b/include/mode/install_nsp_mode.hpp
@@ -12,6 +12,7 @@ namespace tin::ui
             std::string m_name;
             FsStorageId m_destStorageId = FsStorageId_SdCard;
             bool m_ignoreReqFirmVersion = false;
+            bool m_deleteAfterInstall = false;
 
         public:
             InstallNSPMode();
@@ -20,5 +21,6 @@ namespace tin::ui
             void OnNSPSelected();
             void OnDestinationSelected();
             void OnIgnoreReqFirmVersionSelected();
+            void OnDeleteAfterInstallSelected();
     };
-}
\ No newline at end of file
+}
diff --git a/source/mode/install_nsp_mode.cpp b/source/mode/install_nsp_mode.cpp
index 36efa5d..b64c907 100644
--- a/source/mode/install_nsp_mode.cpp
+++ b/source/mode/install_nsp_mode.cpp
@@ -102,6 +102,29 @@ namespace tin::ui
 
         auto optStr = prevView->GetSelectedOptionValue()->GetText();
         m_ignoreReqFirmVersion = (optStr == "Yes");
+
+        auto view = std::make_unique<tin::ui::ConsoleOptionsView>();
+        view->AddEntry("Delete file after install", tin::ui::ConsoleEntrySelectType::HEADING, nullptr);
+        view->AddEntry("", tin::ui::ConsoleEntrySelectType::NONE, nullptr);
+        view->AddEntry("No", tin::ui::ConsoleEntrySelectType::SELECT, std::bind(&InstallNSPMode::OnDeleteAfterInstallSelected, this));
+        view->AddEntry("Yes", tin::ui::ConsoleEntrySelectType::SELECT, std::bind(&InstallNSPMode::OnDeleteAfterInstallSelected, this));
+        manager.PushView(std::move(view));
+    }
+
+    void InstallNSPMode::OnDeleteAfterInstallSelected()
+    {
+        // Retrieve previous selection
+        tin::ui::ViewManager& manager = tin::ui::ViewManager::Instance();
+        ConsoleOptionsView* prevView;
+
+        if (!(prevView = dynamic_cast<ConsoleOptionsView*>(manager.GetCurrentView())))
+        {
+            throw std::runtime_error("Previous view must be a ConsoleOptionsView!");
+        }
+
+        auto optStr = prevView->GetSelectedOptionValue()->GetText();
+        m_deleteAfterInstall = (optStr == "Yes");
+
         std::vector<std::string> installList;
 
         if (m_name == "Install All")
@@ -151,6 +174,16 @@ namespace tin::ui
                 fprintf(stdout, "%s", e.what());
                 break;
             }
+
+            if (m_deleteAfterInstall)
+            {
+                FsFileSystem sdcard;
+                fsMountSdcard(&sdcard);
+                std::string nspPath = "/tinfoil/nsp/" + installList[i];
+                nspPath.reserve(FS_MAX_PATH);
+                fsFsDeleteFile(&sdcard, nspPath.c_str());
+                fsFsClose(&sdcard);
+            }
         }
 
         printf("Done!\n\nPress (B) to return.\n");
```

**Comment by lobofoots** [comment]
Sometimes the install blocks midway, there is an error message about firmware or fs mitm problem. Do not delete all if install stops half way.
