### ISSUE TITLE
Issues with the web browser

### ISSUE THREAD

**Issue by Souperman9** [XorTroll/Goldleaf#200]
I'm on 5.1.0 and using 90DNS. On Goldleaf 0.3, whatever site I try to access, I get an error code of 2800-1810. It says "The page cannot be displayed because the security of the page's certificate cannot be confirmed. The certificate has either expired or is not yet valid. Please make sure he console's date and time setting are correct." (Which they are.) I haven't tried this with an http site because I haven't found any.

**Comment by XorTroll** [comment]
Interesting to hear, anyone facing similar issues with 90DNS?
