### ISSUE TITLE
An error ocurred attempting to delete the account: 0xdc7c

### ISSUE THREAD

**Issue by Aida-Enna** [XorTroll/Goldleaf#201]
I'm trying to delete the secondary user account on my switch and receiving this error.

**Comment by XorTroll** [comment]
Does it have a service account linked or something?

**Comment by Aida-Enna** [comment]
It does not - It was removed via DevMenu on an earlier firmware in an attempt to get rid of it.

**Comment by zzayoung** [comment]
I have the same problem ，but my account is a service account. 
I want to delete it,is there any way to do it without linking to nintendo services?

**Comment by RicardoR12534** [comment]
Same. Tried to set the user state to invalid in DevMenu and now I can't delete the account.

**Comment by coggy9** [comment]
I'm also having the same issue with linked accounts. I would like to remove my accounts for other store regions since my Switch has been banned for a while now.

**Comment by PashaKagan** [comment]
Same.
I'd be happy to be able to remove my two other accounts.

**Comment by XorTroll** [comment]
Linked to a service account and banned: cannot delete from Goldleaf, unsure about other ideas

**Comment by Aida-Enna** [comment]
My secondary account is not banned nor tied to a service account.

**Comment by XorTroll** [comment]
#306 duplicate.
