### ISSUE TITLE
Question about installing on a Mac

### ISSUE THREAD

**Issue by Chippel** [XorTroll/Goldleaf#203]
Is it somehow possible to install nsp files via MacBook? I also have a Windows computer but it won't boot up anymore. I guess my machine is too old.

**Comment by crc-32** [comment]
If you mean via goldtree, https://github.com/friedkeenan/GoldtreePy should work

**Comment by Chippel** [comment]
Thank you. Where did you find it? It should be linked on the main page imho.

**Comment by friedkeenan** [comment]
There is also [Fluffy](https://github.com/fourminute/Fluffy) if you prefer a GUI

**Comment by crc-32** [comment]
Just use goldleaf then?

**Comment by Crissal1995** [comment]
Put goldleaf nro in switch/ folder (the one containing Tinfoil.nro), and remove tinfoil/ folder

**Comment by crc-32** [comment]
^ it's not a case of changing, it's just a different, independent app. you could even use both at once and there'd be no issue other than there being no point in doing so

**Comment by EddyCR** [comment]
So I installed Goldleaf, when trying to run Goldtree.py to install i get this error:
![image](https://user-images.githubusercontent.com/5322460/51870760-19c56700-231a-11e9-92ed-db7a668b92cb.png)

I run the command when im in the usb install on GoldLeaf and waiting for nsps

Any ideas, or some help, sorry to keep bothering you guys.
