### ISSUE TITLE
Not functioning properly in flight mode.

### ISSUE THREAD

**Issue by bandithedoge** [XorTroll/Goldleaf#204]
Today I tried installing some NSPs through Goldtree. I usually use flight mode on my switch (not for ban prevention). When I was installing these NSPs, I forgot to turn flight mode on, so between installing different files I turned on. And guess what? "Average speed" showed 0 MB/s and Goldtree crashed. Since I can't go to the home menu while installing something, I had to reboot my switch. Thankfully, everything still works. Then I transferred one NSP to my SD card to see if it works - same thing, Switch freezes. Then I turned flight mode off and everything installs fine.

**Comment by XorTroll** [comment]
Mind testing more installs? I don't think flight mode should affect them.

**Comment by XorTroll** [comment]
Those errors when starting install still persist, hopefully I think that middle-install freezes have been corrected. Closing this issue as flight mode doesn't seem to be an issue here.
