### ISSUE TITLE
USB Install Bugs I've Found While Developing Fluffy

### ISSUE THREAD

**Issue by fourminute** [XorTroll/Goldleaf#205]
While developing Fluffy I've become quite familiar with Goldleaf's USB install process. I've come up with a list of bugs I can be certain are due to Goldleaf's USB install process malfunctioning. 

1)  **Goldleaf refuses to request next NCA:**
The most prominent bug. I have confirmed that Fluffy delivers the last payload to Goldleaf.

`Wrote Buffer Size: 1048576`

`Wrote Buffer Size: 1048576`

`Wrote Buffer Size: 1048576`

`Delivering last payload data size: 212992` 

`Wrote Buffer Size: 212992`

However, Goldleaf refuses to send an NSPContent request for the next NCA(_confirmed by debugging usb input_) and freezes at 99% progress.

2) **Goldleaf freezes at 0% when re-installing a previous or current corrupted Title.** 

To remedy this bug, I would have to uninstall the Title and re-install it with Tinfoil then uninstall it again. Only then would Goldleaf install the Title successfully.

3) **Goldleaf spits out Finish when re-installing corrupted Title.**

By default, Goldleaf should overwrite the existing Title without hesitation.

4) **Goldleaf won't install some Title when "Ignore Firmware" option is set to "Yes"**

This can include up to a third of the Titles that I've tested. So this bug is pretty prominent. I am running the latest Firmware and don't experience this bug in Tinfoil using the same option.

Lastly, but not least. Please don't change the way Goldleaf communicates via USB, I actually prefer it over the archaic Tinfoil's method. It feels very modern to request and send NCA's individually as well as separating the Ticket from the rest of the payload. 

If you have any questions I'll be here.

**Comment by tiliarou** [comment]
Just one precision (sorry maybe it's obvious): when you mention tinfoil it's the old Addubz/Xortroll version or the DZ/vertigo/blawar version ?

**Comment by fourminute** [comment]
Who the heck is Blawar?

**Comment by tiliarou** [comment]
Ok I actually didn't think this through... if it was during developing fluffy it means you were using addubz tinfoil. Forget my question.

PS: blawar = vertigo (just an alt. name)

**Comment by XorTroll** [comment]
Interesting, thanks for the error information.
I think that the problem is that two threads are running for USB installs, without any kind of synchronization.

**Comment by ThatNerdyPikachu** [comment]
> I think that the problem is that two threads are running for USB installs, without any kind of synchronization.

Thing is, you said you fixed this, didn't you?

**Comment by XorTroll** [comment]
No?

**Comment by XorTroll** [comment]
Moving all USB issues to #220
