### ISSUE TITLE
Enhancement: Show free drive space

### ISSUE THREAD

**Issue by xorinzor** [XorTroll/Goldleaf#206]
It would be a nice enhancement that when you're using GoldTree (might apply to other steps too), it shows you during the installation step what free space both your SD card, as well as internal memory has.

Right now you have to choose without knowing how much space is left on either (or you have to check before opening GoldLeaf)

**Comment by XorTroll** [comment]
This is already shown in the console information menu...
But adding size checks to installations would be an important improvement.

**Comment by xorinzor** [comment]
I know this is available in the console information menu, but if I just install something via GoldLeaf, it's not logical that I'd have to check the disk space separately.

The screen is currently pretty much empty aside the 2 buttons along the bottom to select the desired destination for the app to be installed to. It'd make much more sense to display the remaining space of both destinations too.
