### ISSUE TITLE
(Feature Request) Support for USB/HDD Device mounting

### ISSUE THREAD

**Issue by RyuSeisuke1992** [XorTroll/Goldleaf#207]
Since the latest version of libNX supports `usb:hs service wrapper`, would it now be possible to mount the Goldleaf external data medium via the USB-Port?

**Comment by XorTroll** [comment]
It would be such a great feature, might look at it, but more things are scheduled already to be added or fixed before new suggestions like this one.

Anyway, this could be really nice!

**Comment by XorTroll** [comment]
This will be added as soon as Atmosphere's side is done. Probably not before 0.6 releases, sadly.

**Comment by mid-kid** [comment]
"Atmosphere's side"? Is there something Atmosphere needs to support for this to be possible? `usb:hs` is a stock service, is it not?
