### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by wang93wei** [XorTroll/Goldleaf#208]
I hope to support multiple languages, thank you.

**Comment by XorTroll** [comment]
Yeah was hoping to add this soon.
Spanish support will be granted, but I would need translators

**Comment by lookye** [comment]
I can make a translation from en to ger (de).

**Comment by LittleWhite-tb** [comment]
Push it and I am pretty sure you will have translators. By the way, can handle french.

**Comment by XorTroll** [comment]
Yeah, pretty sure there would be people willing to help on this.
Not a feature for v0.4, but probably a good enhancement for further versions!

**Comment by wang93wei** [comment]
> Yeah, pretty sure there would be people willing to help on this.
> Won't be a feature for v0.4, but probably a good enhancement for further versions!

Thank you! I wish you have a nice day.

**Comment by Insignate** [comment]
I'm willing to make the Pt-Br translation.

**Comment by XorTroll** [comment]
Glad to say that v0.5 is definitely going to add this!

I've almost finished with Spanish translation. Any translation suggestions will be handled by Discord, **NOT HERE PLEASE**.

**Comment by tiliarou** [comment]
Referencing PR for French and German strings:
- fr_FR: https://github.com/XorTroll/Goldleaf/pull/224
- de_DE: https://github.com/XorTroll/Goldleaf/pull/223

**Comment by MenosGrante** [comment]
@XorTroll I think good idea for helping to localize Goldleaf is creating translation page on Crowdin. [They provide free accounts for Open Source projects. ](https://crowdin.com/page/open-source-project-setup-request). [Or you can use another tool called OneSky, it is totally free.](https://www.oneskyapp.com/).

This will help you facilitate the localization process and will not force people to search for strings in the code.

**Comment by tiliarou** [comment]
Couldn't agree more ! I wanted to suggest it but thought it was paid only.
Look at the mess we did in the French translation PR...
