### ISSUE TITLE
More installing formats appart from NSP

### ISSUE THREAD

**Issue by Oleboy555** [XorTroll/Goldleaf#212]
https://gbatemp.net/threads/nszip-nsp-compressor-decompressor-to-reduce-storage.530313/

this would be an awesome feature in my opinion

**Comment by DavidOliM** [comment]
This would actually increase install time or storage since it would be needed to decompress while installing or decompress then install. (If using USB install method)

It would be even worse if installing from SD

**Comment by leo60228** [comment]
@DavidOliM No, it wouldn't. You would need to decompress while installing, but that should barely affect performance. If SD/USB is slower than NAND, it would likely be faster.

**Comment by XorTroll** [comment]
The format hasn't really been that popular (while it was really promising), thus I don't think many people will tend to use NSPZs.

**Comment by dreambottle** [comment]
You can make it popular. Lack of support from NSP installers is likely holding it back.

**Comment by Oleboy555** [comment]
> The format hasn't really been that popular (while it was really promising), thus I don't think many people will tend to use NSPZs.

If no installer supports it of course it wont be popular

**Comment by XorTroll** [comment]
Honestly I'm considering adding more formats appart from NSP. Using compression formats like ZIP or directly inside a directory might be helpful.

**Comment by lookye** [comment]
Closed in conjuntion to: #417
