### ISSUE TITLE
USB install stuck at "Starting installation"

### ISSUE THREAD

**Issue by bandithedoge** [XorTroll/Goldleaf#213]
I'm using Goldleaf 0.3, NSP version. I'm currently installing a bunch of NSP files. I have installd 2 without any issues, but when I install the other ones, it gets stuck at "Starting installation", while Goldtree says "Goldleaf is ready for the installation. Preparing everything...". I transferred the NSPs to my SD card and installed them with n1dus. Obviously, they installed just fine.

**Comment by ThatNerdyPikachu** [comment]
Try and restart it, close and open goldleaf / goldtree, etc.

This is a known bug, needs to be fixed.

**Comment by bandithedoge** [comment]
I restarted both goldtree and my Switch multiple times. Still happening.

**Comment by ShinkoNet** [comment]
Try connecting the switch using a USB 2.0 port. I had this issue when USB Installing from a 3.0 port.

**Comment by bandithedoge** [comment]
@ShinkoNet I'm using a 2.0 port. I don't even have 3.0 on my motherboard.

**Comment by XorTroll** [comment]
Moving all USB issues to #220
