### ISSUE TITLE
no issues ,switch browser have video play back

### ISSUE THREAD

**Issue by Kronos2308** [XorTroll/Goldleaf#214]
i see that you post that the browser d'not have video play back well , is a litle triki but the video playback work fine 
tested on youtube 
animebomb
an others
the problem of the aut applet is the loguin , and pass save only get that by using the browser you open on the profile

**Comment by smurfhunter** [comment]
This has no reason to be an issue. The .nro is not guaranteed to support video playback.

**Comment by Kronos2308** [comment]
Question
You read well my mensage ?
Y say that the video work
But the app say no,well the videoplayback work

**Comment by deadair3210** [comment]
Video playback is iffy on the web browser. Pretty sure Goldleaf does nothing other than launching the browser. The only thing I know that changes anything about the browser is whether its the normal browser or the web login browser
