### ISSUE TITLE
USB nsp installation hangs at some certain steps

### ISSUE THREAD

**Issue by pabermod** [XorTroll/Goldleaf#215]
Hi,

When using latest 0.4 version (both nro/nsp and goldtree) the usb installation hangs at the end of step 3 of 7. It seems to not permorm this step wholly (the green bar almost reach the end but for a tiny part).
Also the speed drops to zero in this state

EDIT: It has happened with one game of two i've tried

EDIT2: Another nsp (an update) has hanged up at the end of step 4 of 13

Cheers

**Comment by deadair3210** [comment]
Have had this happen multiple times with the same experiences of the install never quite finishing. Last thing Goldtree shows is Content was sent to Goldleaf

**Comment by friedkeenan** [comment]
This sounds like the error people were having with GoldtreePy at friedkeenan/GoldtreePy#3. The way I fixed it was increasing the timeout from 1 second to 3 seconds, but I'm not sure how to implement that in C#.

**Comment by NekoNoor** [comment]
I just got this problem at the end of the 3rd nca using goldtreepy (with usb timeout error) so then i tested it in goldtree 0.4 and the same thing happens, hangs at the end of the 3rd nca. 0 MB/s

**Comment by love768952693** [comment]
Version 0.4 seems to have such problems, and I don't know how to solve them.

**Comment by love768952693** [comment]
5 Of 8 also appeared hangs,

And the PC display is

  [gtree:Log] Sending content 'acb06ad11bfab81900fc02e772a8723f.nca'... (5 of 8)

[gtree:Log] Content was sent to Goldleaf.

**Comment by XorTroll** [comment]
Moving all USB issues to #220
