### ISSUE TITLE
Cannot install NSP’s on .4 update

### ISSUE THREAD

**Issue by Powerfvl** [XorTroll/Goldleaf#216]
After updating Goldleaf from .3 to .4 I can no longer install NSP’s. I have used this tool since release and it has always worked. It begins with the new checking titles and then quits and gives me an error. I am trying to install a game update.

**Comment by SassyCultist** [comment]
Did you already have an older update version installed for that game? This may be the same issue as #218

**Comment by XorTroll** [comment]
Any error, more information...?

**Comment by XorTroll** [comment]
Closing this as 0.4 is really unstable.
