### ISSUE TITLE
Read-only attribute - error

### ISSUE THREAD

**Issue by Viperbite** [XorTroll/Goldleaf#217]
If the read-only attribute is on the NSP file, an error occurs when installing from a computer via cable (Failed to open the meta NCA (CNMT NCA) within the NSP. (Error code 0x202))

**Comment by XorTroll** [comment]
Interesting, have you tried that just once, or with several NSPs to confirm so?

**Comment by Viperbite** [comment]
> Interesting, have you tried that just once, or with several NSPs to confirm so?

Yes, I've tried several files, and I'm not the only one with a problem.

**Comment by renatosk** [comment]
with latest nightly i dont get more invalid nca magic , i get two errors: one is when i use goldtree ,goldenleaf get stuck in "connection was established.Waiting for a NSP request from PC client..." , and the other is when i use fluffly , i get the error 0x202 , description: invalid path (1)

**Comment by lookye** [comment]
@Viperbite Does the error occur still with the latest Goldleaf releases for you?

**Comment by XorTroll** [comment]
This is old as hell, and stuff has changed quite a lot...
