### ISSUE TITLE
Installing new game update version does not work on 0.4

### ISSUE THREAD

**Issue by SassyCultist** [XorTroll/Goldleaf#218]
I am trying to install a new update for a game that I have previously installed an update for and it will not work in Goldleaf 0.4. It seems to be related to the new check to see if something is installed before installing it. Goldleaf 0.3 works fine for doing this.

**Comment by XorTroll** [comment]
Will not work? Mind explaining a bit more the situation?

**Comment by SassyCultist** [comment]
I have a game installed with an update. I tried to use goldleaf 0.4 to install a newer update and it refused to install because I already had a version of that title installed. When I downgraded to goldleaf 0.3, I tried to install the same nsp it worked. Both of these were done through usb installation on firmware 6.2.0.

**Comment by Powerfvl** [comment]
Yes this is the same issue, except I am not using USB install. I used install from SD and have the same issue.

**Comment by lunalik2** [comment]
I am having the same issue. BOTW update file hangs at a full progress bar.

**Comment by brlala** [comment]
Having the same problem as well, most of my USB .nsp installation will hangs at a full progress bar with 0MBps transfer rate. NSP installs correctly using other NSP installer.
