### ISSUE TITLE
Feature Request: Goldleaf NS File Manager, added support for Chinese names.

### ISSUE THREAD

**Issue by love768952693** [XorTroll/Goldleaf#221]
At present, the Goldleaf file manager will not be able to view the Chinese name directly. I don't know if the author can add support for the Chinese name.

Thank you

**Comment by XorTroll** [comment]
This might be a bug with encoding.

**Comment by Limero** [comment]
Same issue as https://github.com/XorTroll/Goldleaf/issues/195 ?

**Comment by XorTroll** [comment]
Fixed unicode issues in remote PC for 0.7, can't do anything for SD since FS doesn't support non-ASCII.
