### ISSUE TITLE
Goldleaf thinks it can't launch NROs when it's loaded through hbl.nsp title redirection

### ISSUE THREAD

**Issue by friedkeenan** [XorTroll/Goldleaf#225]
When you launch Goldleaf through title redirection or through the homebrew menu NSP, it says that it can't launch NROs because it hasn't been launched as an NRO, except it had. I think the problem is [this line](https://github.com/XorTroll/Goldleaf/blob/master/Goldleaf/Program/ExeFs/main/Source/gleaf/Application.cpp#L78) where libnx will tell Goldleaf that it's running as an application, and Goldleaf just assumes that means it's running through its own NSP, when in reality it could be that, or it could be running through title redirection.

**Comment by XorTroll** [comment]
True, already known issue

**Comment by XorTroll** [comment]
v0.5 will fix this btw
