### ISSUE TITLE
Bypass the need for minimum firmware?

### ISSUE THREAD

**Issue by 1kozlovsas** [XorTroll/Goldleaf#226]
I saw issue #92 and my issue is the same but in a different context.

I loaded Celeste onto my SD card and installed it through Goldleaf (Booted Goldleaf from Album) to my SD card. Upon trying to run the game I was asked to link a Nintendo account which would require me to update. I installed the game both ignoring the check and not ignoring it. I'm currently on 4.1.0. 

Can Goldleaf bypass the need for this check?

**Comment by 1kozlovsas** [comment]
NEVER MIND.

To all those who try to launch the NSP files, heed this: IT IS NOT GOLDLEAF, IT'S ATMOSPHERE.

You need to patch the CFW. Link here to download: https://gbatemp.net/threads/i-heard-that-you-guys-need-some-sweet-patches-for-atmosphere.521164/

This can be closed. Thanks for all the hard work.

**Comment by ThatNerdyPikachu** [comment]
You can close issues yourself, there's a Close Issue button right in the message box at the bottom~!
