### ISSUE TITLE
Much slower usb transfer speeds with 0.4 release of Goldleaf

### ISSUE THREAD

**Issue by patrikhejnar** [XorTroll/Goldleaf#228]
Hello, 

immediatelly after updating to 0.4 version i ve seen decrease in usb install speeds from 
cca 40-46mbytes/s while using versions 0.2, 0.3 to 16-25mbytes in version 0.4

Goldtree version doesnt affect these speeds, only goldleaf.

Thanks for your hard work :)

**Comment by friedkeenan** [comment]
This should probably be in #220
