### ISSUE TITLE
Install tickets like in 3DS

### ISSUE THREAD

**Issue by PWalll** [XorTroll/Goldleaf#232]
I know it's a little complicated but I pray for it because I nand it because of y downgrade my hand and now I have to reinstall all to work.

**Comment by deadair3210** [comment]
Pretty sure the switch doesn't treat tickets in even closely to the way the 3ds did, mostly due to Big N putting in extra work to make sure that ticket sharing isn't a thing.

**Comment by PWalll** [comment]
I say extract a ticket ex an nsp in a pc and put in sd card and installed

**Comment by PWalll** [comment]
*install it

**Comment by XorTroll** [comment]
Tickets can already be installed from the browser...?

**Comment by PWalll** [comment]
and where I get that ticket 
and how I install
And you are asking about your program??

**Comment by XorTroll** [comment]
?

**Comment by PWalll** [comment]
How I install the tiks and how i extract them

**Comment by XorTroll** [comment]
Read the README please.
