### ISSUE TITLE
Network Install

### ISSUE THREAD

**Issue by Arkholl** [XorTroll/Goldleaf#233]
Hi.
It would be great if we can install NSP over network.
Even with a custom API to communicate (list all, get details, get/install) with a server hosting the various nsp (base, updates, dlcs) as a media server does, so it will open the possibility to create a local/private eshop.

It may be a long time to finish all, but all travels begin with one step.

What do you think?

**Comment by XorTroll** [comment]
Tested 0.6's PC-over-USB over network, and it was terribly slow. Doubtfully this will be added.

**Comment by XorTroll** [comment]
#162
