### ISSUE TITLE
[7.0.0] Atmosphere 0.8.4: Can't install nsps: Failed to open the meta NCA

### ISSUE THREAD

**Issue by Yooooomi** [XorTroll/Goldleaf#234]
Hello,

I'm using Goldleaf 0.5 (0.4 kept crashing)

Whenever I try to install an nsp from Goldleaf it indicates `An error occured: Failed to open the meta NCA`
There is also a bug when trying to rename a random file, indicating that it can't rename this file

Any suggestion on what to do ? Has it something to do with the fact that I'm on 7.0.0 ?
Any other tool to install nsp files securely ? (i guess not :( )

Thank you

**Comment by LeoShivas** [comment]
Hi,
For my information, where did you find the 0.5 version of GoldLeaf ?

**Comment by 1kozlovsas** [comment]
What's the specific error code after the error message?

**Comment by Yooooomi** [comment]
The error code I'm getting is `(CNMT NCA): 0x299002`
Seems to happen only on 7.0.0 since my friend runs it smoothly in 6.2

@LeoShivas, got the 0.5 from here : https://bsnx.lavatech.top/goldleaf/

**Comment by lookye** [comment]
You can not install NSPs on Atmosphere. SciresM does not allow it. Pleas close this issue, as its not a problem with Goldleaf but Atmospheres decision not to support NSPs.

(You can only install NSPs on Atmosphere with Sigpatches (Kosmos) but not on 7.0.X atm)

**Comment by Yooooomi** [comment]
So I may want to downgrade to 6.2 with ChoixDuJourNX ? Would there be any issue with downgrading to 6.2 from 7.0.0 ?

**Comment by lookye** [comment]
I dont know. Also this does not belong here.

**Comment by XorTroll** [comment]
Actual reason:
Sigpatches are broken for 7.0.0, ScrotuM didn't change anything on purpose.

Just wait.
