### ISSUE TITLE
[7.0.X AMS 0.8.4] Failing installing NSPs

### ISSUE THREAD

**Issue by Yooooomi** [XorTroll/Goldleaf#235]
Hello,

Sigpatches came out this morning for 7.0.0 and I can't succeed in installing NSPs through GoldLeaf (0.5)

Usb installation tells me that it's not a valid NSP (GoldLeaf.nsp seems to be valid but hangs at step 4 of 5)
The NRO tells me `Failed to open the meta NCA (CNMT NCA): 0x299002` for every NSP

Is there any thing I'm doing wrong ?
Thanks

**Comment by XorTroll** [comment]
Mind testing with original Tinfoil?

**Comment by Yooooomi** [comment]
I really don't know how to install this neither where to find it. Some people say I need a key. I didn't wanted to install it.
But I can test yeah why not.
Do you have sources or steps to follow ?

Thanks

**Comment by XorTroll** [comment]
Anyway, mind testing other NSPs?

**Comment by Yooooomi** [comment]
I've tested many NSPs even the GoldLeaf.nsf and it ALWAYS tells the same error

**Comment by XorTroll** [comment]
Might be sigpatches' fault? Others don't have those errors

**Comment by Yooooomi** [comment]
Sigpatches are brand new so I don't have many informations. But people say that they can launch installed game threw those sigpatches on 7.0.0

**Comment by Strat00s** [comment]
Sigpatches are working normally on 7.0.1, except that only DevMenu is able to install any NSPs.

**Comment by renatosk** [comment]
Usb install works on 0.3 , but normal install dont , get the same error as OP

**Comment by XorTroll** [comment]
Forget about what I've said about sigpatches.
Only Sd card installs fail, as FS services were removed the ability to mount NCAs from @Sdcard:/ in 7.0.0, hence the code fails to access the NSPs contents via SD card.

Don't worry, v0.5 will fix this.

**Comment by PiotrZadka** [comment]
ANy ETA for v0.5 ?

**Comment by D3fau4** [comment]
5h

**Comment by PiotrZadka** [comment]
Wow, thats quick answer. Thank you

**Comment by smashbro73** [comment]
I haven't tested goldleaf USB install, but original tinfoil with aluminium foil usb install works

**Comment by ItsukaNakou** [comment]
it's happening to me to... But not only with goldleaf, tinfoil and dOPUS are giving me the same problem...

**Comment by XorTroll** [comment]
Both use the same systems for NSP installing.
Forget about dOPUS, it's a dead project, and same thing about Tinfoil.

**Comment by ItsukaNakou** [comment]
Yeah... Just tried them cause i was desperate, but goldleaf is definitely the best tool.

**Comment by ItsukaNakou** [comment]
when's v5.0 coming out?

**Comment by smashbro73** [comment]
give him some time

**Comment by Yooooomi** [comment]
Please leave this issue clean for constructive results :)
It'd be more productive

Thanks

**Comment by nection** [comment]
I'll wait for 0.5, because I also have MACHINTOSH and I can not load via USB, and neither from a virtual machine windows.

**Comment by ItsukaNakou** [comment]
What's libnx-goldleaf used for?

**Comment by Yooooomi** [comment]
@XorTroll Is it FS services fault if GoldTree says that it's not a valid NSP via GoldTree ?

**Comment by XorTroll** [comment]
No

**Comment by Yooooomi** [comment]
What would cause this ? I have downloaded an official NSP and it won't install. Any ideas ?
The exact error is `An error ocurred opening the selected NSP. Are you sure it's a valid NSP?`
And yeah I'm sure it's a valid NSP

**Comment by chou915388** [comment]
I installed some nsp via USB successful, but I can't start these games with a error code: 0005-2005,
like this: https://imgur.com/a/E4Z1dOx

**Comment by RenaKunisaki** [comment]
I'm trying to install NSP on 7.0.1 (AMS 0.8.4, GoldLeaf 0.4) and when asked to ignore firmware version, select Yes, it freezes and then displays a crash screen.

If I hold Power button before crash screen appears, I can open the menu, but if I press Home, it crashes immediately.

Also had a crash while browsing installed titles.

Also, it complains that there's not enough space in NAND to install, which is wrong. (NAND has 24.7GB free, SD has 9.0GB, NSP is only 1GB)
[02220678757_0100000000000006.log](https://github.com/XorTroll/Goldleaf/files/2903538/02220678757_0100000000000006.log)

**Comment by coryshaw1** [comment]
Also having issues with all nsp installs via usb and sd card on 7.0.1 with sig patches. Old tinfoil works flawlessly.

**Comment by Yooooomi** [comment]
Free space is a bit bugged and will be fixed in 0.5
Please consider using 0.3 to install games with USB.

**Comment by PiotrZadka** [comment]
> 
> 
> Free space is a bit bugged and will be fixed in 0.5
> Please consider using Goldleaf 0.3 to install games with USB.

I tried 0.3 and goldtree 0.3 and Super Smash installs with error at the end. Once I try to run the game it says that game is corrupted and contact nintendo.

**Comment by Yooooomi** [comment]
I personally use latest GoldTree on master and Goldleaf 0.3 and it allowed me to play smash :)
Never use 0.4 ><

**Comment by smashbro73** [comment]
I used latest goldleaf on bsnx and it works. I mean experimental nightly v0.5 build

**Comment by chou915388** [comment]
You can use Goldleaf 0.2 with Goldtree 0.2 over USB, its works for me to install all nsp and update.
If you have problem during installing nsp with Goldleaf 0.2, you can choose another place: NAND or SD.

**Comment by chou915388** [comment]
> I used latest goldleaf on bsnx and it works. I mean experimental nightly v0.5 build

You mean goldleaf v0.5 and goldtree v0.5? Where can I get them? thx.

**Comment by PiotrZadka** [comment]
> 
> 
> > I used latest goldleaf on bsnx and it works. I mean experimental nightly v0.5 build
> 
> You mean goldleaf v0.5 and goldtree v0.5? Where can I get them? thx.

Discord


> 
> 
> I used latest goldleaf on bsnx and it works. I mean experimental nightly v0.5 build

I tried installing on latest nightly and goldtree and I get error "Invalid NCA magic (missing sigpatches?) (firmware too low?) 4517 . I'm on latest atmosphere/kosmos and 7.0.1 cfw

**Comment by Yooooomi** [comment]
Use Goldleaf 0.3 and goldtree 0.5
Get Goldleaf from releases and goldtree 0.5 from master or 0.4 should work too

Summary:
- Goldleaf 0.3
- Goldtree 0.4-0.5

**Comment by XorTroll** [comment]
Use nightly builds for the most installs' stability, Goldtree is the same since like 0.3.

**Comment by renatosk** [comment]
> I tried installing on latest nightly (v0.5) and goldtree and I get error "Invalid NCA magic (missing sigpatches?) (firmware too low?) 4517 . I'm on latest atmosphere/kosmos and 7.0.1 cfw

I'm getting this same error on 0.5 nightly in USB installs

**Comment by goffrier** [comment]
0.5 is broken use 0.3 with goldtree 0.3

**Comment by PiotrZadka** [comment]
> 
> 
> 0.5 is broken use 0.3 with goldtree 0.3

0.3 & 0.3 worked like a charm! thanks!

**Comment by akwiz** [comment]
Same issue for me on 7.0.1 with latest patches. Invalid NCA magic. Happens with goldleaf 0.3 0.4 and 0.5. any new ideas?

**Comment by chou915388** [comment]
> 
> 
> Same issue for me on 7.0.1 with latest patches. Invalid NCA magic. Happens with goldleaf 0.3 0.4 and 0.5. any new ideas?
> 
> Edit: I don't think I'm using the nightly goldtree. Let me try that

0.2 goldleaf + 0.2 goldtree

**Comment by Bluediablito** [comment]
Can someone please point me in the right direction to goldtree .5. Thank you

**Comment by lookye** [comment]
> Can someone please point me in the right direction to goldtree .5. Thank you

There is no goldtree 0.5...Use one of the earlier releases (goldtree never changed)

**Comment by Bluediablito** [comment]
Thank you lookye, I guess I'll hold of since .5 is crashing and some nsp not installing on 7.0.1 kosmos 1111

Any suggestions

**Comment by nection** [comment]
> Thank you lookye, I guess I'll hold of since .5 is crashing and some nsp not installing on 7.0.1 kosmos 1111
> 
> Any suggestions

is the same thing that happens to me, I hope the final 0.5 fix all this, because with the 0.5beta I still do not work some NSP's.

**Comment by lookye** [comment]
@Yooooomi 
The problems should be solved with the 0.5 release.
Can this be closed?

**Comment by Yooooomi** [comment]
Yes, if 0.5 doesn't fix I'll reopen another one

**Comment by stuie1** [comment]
I’m just saying using the 0.5 nsp I can’t connect to goldtree but using the 0.2 nsp it connects
