### ISSUE TITLE
Goldtree asking wrong mode to read files

### ISSUE THREAD

**Issue by Yooooomi** [XorTroll/Goldleaf#241]
I was reading goldtree source code because I couldn't install NSP. It was telling me `Are you sure it's a valid NSP`
I added debug and saw the filestream you open doesn't specify Read-Only mode. So in few systems like mine installation canceled cause of permission denied.

Simply add `FileMode.Read` as third parameter when opening filestream.

Thanks

**Comment by XorTroll** [comment]
Interesting, might give this a try

**Comment by Yooooomi** [comment]
Just reviewed it
It's called FileAccess :)

**Comment by XorTroll** [comment]
Fork the repository, commit changes and pull them from your fork.
Would be glad to merge that.

**Comment by Yooooomi** [comment]
Did not understand much about your error object but it would be good if errors we're stocked into a file so that people know where to look at.
Mine was just a permission denied and got me changing many times the version 
I'll try to submit something nice about what could could be done better

**Comment by XorTroll** [comment]
Goldtree changed in 0.6, so hopefully this works fine now.
