### ISSUE TITLE
Goldleaf asking for double the space to install

### ISSUE THREAD

**Issue by doomtrigger** [XorTroll/Goldleaf#245]
i have 16 gb on my sd card its asking for 26 gb to install a 13gb nsp

**Comment by PiotrZadka** [comment]
Thats how it works. You always need double storage even on your PC. You need some space to unzip the files/install. It's not like it's creating files from thin air.

**Comment by XorTroll** [comment]
Well, this might be interesting to check out.
No temporary data is unzipped nor copied, as using mounting systems from the console itself and buffered content writing, so double space might not be required.

Just added it to ensure tests would work fine, but might not be required.

**Comment by j13li78** [comment]
wouldn't it theoreticaly possible to install one byte and then delete on byte which at the end would only need the space of the file or the nsp could be moved to the sysnand first and from their installed on the sd card + after the completion it will be deleted from the sysnand
