### ISSUE TITLE
How do I install Goldtree 0.5 from master build in order to use with Goldleaf (0.2, 0.3, or 0.5)?

### ISSUE THREAD

**Issue by crazy1111** [XorTroll/Goldleaf#246]
I'm using latest Goldleaf 0.5 pre build from bsnx along with Goldtree 0.3 and I get Error "invalid NCA magic (missing sigpatches?) firmware too low? 4517. I'm on latest atmosphere 0.8.4, firmware 7.0.1. I'm also new to github and have done extensive searching on Google but need help on how to use Goldtree 0.5 from master build in order to install NSPs through USB?

And I've also tried already other people's solutions of using Goldtree 0.2 (and 0.3) with Goldleaf 0.2 (and 0.3) and keeping getting errors!

**Comment by XorTroll** [comment]
This is because you miss sigpatches, probably. Do you have them?

**Comment by crazy1111** [comment]
No, where can I find them?

**Comment by crazy1111** [comment]
I believe so, I downloaded some from https://gbatemp.net/attachments/patches-zip.158610/, but these don't seem to work. Where can I find the RIGHT ones? Also, do I just place patches in Atmosphere folder on SD root or do I need to place them somewhere else?

**Comment by crazy1111** [comment]
Not sure what I was doing wrong, but I reformatted my micro SD card (in exFat), reinstalled EVERYTHING (including patches I found off of this YT tutorial on YT: https://www.youtube.com/watch?v=f8w6nI0b4_o&list=FLcra03Y1pTvwk8Ew_7oD8Xw&t=32s&index=3, and tried again using Goldleaf 0.2. and Goldtree 0.2 USB install, and it worked!!!

**Comment by crazy1111** [comment]
Not sure what I was doing wrong, but I reformatted my micro SD card (in exFat), reinstalled EVERYTHING (including patches I found off of this YT tutorial: https://www.youtube.com/watch?v=f8w6nI0b4_o&list=FLcra03Y1pTvwk8Ew_7oD8Xw&t=32s&index=3, and tried again using Goldleaf 0.2. and Goldtree 0.2 USB install, and it worked!!!

**Comment by crazy1111** [comment]
Not sure what I was doing wrong, but I reformatted my micro SD card (in exFat), reinstalled EVERYTHING (including patches I found off of this YT tutorial on YT: https://www.youtube.com/watch?v=f8w6nI0b4_o&list=FLcra03Y1pTvwk8Ew_7oD8Xw&t=32s&index=3), and tried again using Goldleaf 0.2. and Goldtree 0.2 USB install, and it worked!!!

**Comment by crazy1111** [comment]
Not sure what I was doing wrong, but I reformatted my micro SD card (in exFat), reinstalled EVERYTHING (including patches I found off of this YT tutorial: https://www.youtube.com/watch?v=f8w6nI0b4_o&list=FLcra03Y1pTvwk8Ew_7oD8Xw&t=32s&index=3), and tried again using Goldleaf 0.2. and Goldtree 0.2 USB install, and it worked!!!

**Comment by XorTroll** [comment]
Ok then.

**Comment by akwiz** [comment]
I am having the exact same issue. I have tried every iteration of goldleaf and goldtree and I am still running into the same issue. The older versions give me sig patch errors and the 0.5 nightly usually fails at loading tickets or something of the sort.

I can install like 1 out of 20 NSPs though. Any suggestions?
