### ISSUE TITLE
Failure rate installing NSPs on the nightbot 5.0

### ISSUE THREAD

**Issue by IAmTheRealLinkle** [XorTroll/Goldleaf#247]
During installing NSPs, I got a no sig patches error, when in fact I do have them. Some games even installed perfectly. For BOTW I got a low firmware issue, and plenty other. This is the 5.0 version.

**Comment by UnicornsOnLSD** [comment]
What version are you on? If you're on 7.0.x, you need to download new signature patches

**Comment by IAmTheRealLinkle** [comment]
I am on 5.1.0, worked before. Kosmos latest package, along with latest sig patches included on the Kosmos page. Clean install.

**Comment by UnicornsOnLSD** [comment]
Did you delete /atmosphere, /bootloader, and /modules before installing Kosmos?

**Comment by IAmTheRealLinkle** [comment]
It was a full resintall. Clean. SD card was formatted via switch, and switch was wiped.

**Comment by UnicornsOnLSD** [comment]
Sounds very odd. Remember that Goldleaf 0.5 is still in development. Check if you are using the latest commit and try again

**Comment by IAmTheRealLinkle** [comment]
That is why I made this. So he knows. I will recreate them today, it was the latest build. Then I will give full Errors
