### ISSUE TITLE
Improve firmware 5.1.0 support

### ISSUE THREAD

**Issue by xalloc** [XorTroll/Goldleaf#251]
Is the "ignore required firmware" feature still buggy under Switch fw 5.1.0?
No people seem to be able to run Stardew Valley NSP v0 (0100E65002BB8000) as it asks for an update when launched.
I then tried installing the latest game update (1.3.33):
-Goldleaf crashes the console after some time during install (but when I reboot the update seems to be installed)
-Tinfoil completes the install

When I launch the updated game, the console freezes in the Switch initial loading... sometimes if I press the Vol+/- button or the power button you can see the Switch logo slightly moving for an instant. Like the console isn't totally frozen, but is under a giant loading work that never finishes.

 My setup:
firmware 5.1.0
Atmosphere 0.8.4 (Kosmos)
latest Goldleaf and Tinfoil Fixed by @fourminute

Do you need any more feedback to investigate in the issue?

**Comment by IAmTheRealLinkle** [comment]
I second this please.

**Comment by XorTroll** [comment]
I am on fw 5.1.0, and never had any relevant issues against other fws.
I do even test all the stuff on this version.

**Comment by IAmTheRealLinkle** [comment]
@xortroll could you tell me your setup? Is it SD files or just pure atmosphere? I will just switch.

**Comment by xalloc** [comment]
@XorTroll good to know, I also add that my SD card is formatted in exFAT.
Who knows if it's some games that are difficult or it's just the setup. Maybe comparing our setups can help.

**Comment by XorTroll** [comment]
FAT32, Kosmos, gbatemp sigpatches

**Comment by IAmTheRealLinkle** [comment]
I will give that setup a try! Thank you. Honestly I usually run EXfat, but FAT32 will be worth it if it helps fix the problems. I honestly do not understand why I have so many, I do clean installs and all. But I will text your setup and reply back!

**Comment by IAmTheRealLinkle** [comment]
Update: on EXfat, running stock ATMO with sig patches from GBA, running amazing. Thank you!

**Comment by unbranched** [comment]
@IAmTheRealLinkle interesting, and what was the setup you came from?

**Comment by xalloc** [comment]
@IAmTheRealLinkle interesting, what was the setup you came from? What did you change?

**Comment by xalloc** [comment]
Mistery solved. So about the game update 1.3.33 it simply needs firmware 6.0.1, that's why it couldn't start...

Instead the fact the base v0 game refused to start on my console, is because of [this reason](https://github.com/XorTroll/Goldleaf/issues/48).

This issue can be closed.
