### ISSUE TITLE
0.5 nightly: Unable to view title if update/DLC installation failed

### ISSUE THREAD

**Issue by chinhodado** [XorTroll/Goldleaf#265]
0.5 nightly: If update/DLC installation failed, then the title entry will not be viewable, which also makes it impossible to remove the update/DLC. It was not an issue in 0.4 because in 0.4 update/DLC had their own entry.

**Comment by emariz** [comment]
I think that my reply on another issue might help you. https://github.com/XorTroll/Goldleaf/issues/219#issuecomment-475915335

**Comment by lookye** [comment]
@emariz @chinhodado 
Please update Goldleaf to the 0.5 Release. Your problem should be solved then.

To delete faulty installations do this:

System Settings > Data Management > Manage Software > Scroll to the faulty installation and delete it.
