### ISSUE TITLE
[Feature Request] NSzip support

### ISSUE THREAD

**Issue by dissociativity** [XorTroll/Goldleaf#267]
Some of us have rather large NSP collections, supporting .nsz files would help make that a little easier to manage.

https://github.com/nicoboss/nsZip

**Comment by friedkeenan** [comment]
Wait, do people actually use that? NSPs are just collections of NCAs, which I think are by definition compressed. Also, I've asked before (albeit in the developer channel of the AtlasNX discord) if anyone used this, and I got a resounding no as my answer.

Either way, this is a duplicate of #212
