### ISSUE TITLE
[Can´t open] Can download NSP but not use it.

### ISSUE THREAD

**Issue by Ofdas23** [XorTroll/Goldleaf#268]
Hello there,

I recently switched from SXOS to Atmosphere, but after switching, almost every games from me stopped working. My thought was maybe it is like that because I have used SXOS´installer to install NSPs, thats why I installed NSMBU (New Super Mario Bros U Deluxe) via Goldleaf. Installation is succesful but I cant launch it. It says: "Checking wether you can play the game or not" , then it just says that an error occured. 
How can I fix this? By the way, I am very new to Atmosphere and I am not sure wether I have set Atmosphere up the right way or not. 

Thank yo in advance!

**Comment by XorTroll** [comment]
That looks like a missing ticket. Are you sure that the NSP is fine?

**Comment by Ofdas23** [comment]
@XorTroll It was a missing ticket. I wasted your and my time with this... whoops. But why did the same NSP worked for SXOS but not for Atmosphere?
Thank you for your help!
