### ISSUE TITLE
commit #d212c5a didn't fix it free space check.

### ISSUE THREAD

**Issue by maskmark** [XorTroll/Goldleaf#269]
no, commit #d212c5a didn't fix it!
the installer still requests double of free size than the nsp installation actually needs when installing into nand or sdcard. my sdcard has 15gb and my nand has 17gb of free space,but goldleaf 0.5 nightly build refuses to intall a 9.4gb nsp file because of no enough free space.
and when I deleted some files till I get 20gb free , goldleaf let me install the nsp.
so it is still something wrong.

**Comment by lookye** [comment]
There are several commits after that old commit from that. You should update your nightly.
