### ISSUE TITLE
GoldTree using endianness of host machine

### ISSUE THREAD

**Issue by NoahRoseLedesma** [XorTroll/Goldleaf#272]
# GoldTree using endianness of host machine

## Bug description
Write commands in GoldTree use the endianness of the host machine when sending data over the USB pipe. This can cause communication errors between GoldLeaf and GoldTree

## Your setup
- **Goldtree version**: 8b7d40b

**Comment by XorTroll** [comment]
Might expand on this a little more?
Goldtree isn't specially stable, and any suggestions to improve it might be very helpful.

**Comment by roothorick** [comment]
The Switch, x86, and most ARM systems are all little endian. What exactly *is* your host? You might be seeing something else.

**Comment by XorTroll** [comment]
(waiting for further information)

**Comment by NoahRoseLedesma** [comment]
I did experience any problem on my host machine, but I noticed that there would be a problem on some machines when I did some digging into the USB stuff. This was all a long while ago so I don't remember what the offending code was.

If others haven't complained it is probably of little importance.
