### ISSUE TITLE
Crash upon closing goldleaf nsp

### ISSUE THREAD

**Issue by Endar-Marit** [XorTroll/Goldleaf#274]
#Bug title
Crashes to black screen (Goldleaf 0.5 NSP)

#bug description
Goldleaf 0.5 nsp crashed to black screen after trying to close it

##Setup

- 7.0.1

- ReiNX 2.1

- Goldleaf 0.5 - NSP 

- Goldtree 0.5

## Bug reproduction

Enter installed goldleaf nsp, wait for it to load
Press home button
press x to close
crash to black screen

**Comment by D3fau4** [comment]
Did you have the console connected to the PC?

**Comment by Endar-Marit** [comment]
Ah yep, known bug there?

**Comment by bonezinger** [comment]
I can confirm this, same config (ReiNX 2.1, goldleaf 0.5, using the .nsp version, connected to the PC with a USB cable), crashed after Home -> X -> Close. Also happens if you try to open something else and close Goldleaf.
Without the cable connected, I managed to close without crashing, so that does seem to be the culprit.

**Comment by lookye** [comment]
All CFWs are affected and its not only Goldleaf. Its for a lot of homebrews.

Solution: Unplug the cable before quitting homebrews.

**Comment by mrbob312** [comment]
actually the correct way to close it it with +, just like most other homebrew (for hbAppstore its -)

**Comment by ViramilhoPT** [comment]
Same problem here. But closing with + fix it. Using Atmo 8.7 firm , 7.0.0

**Comment by maronin** [comment]
Can you guys please elaborate what you mean by "close it with +"? What key combination do you need to do?

Thanks!

**Comment by lookye** [comment]
First: Make sure, no USB is plugged into your console.
Second: Press the + button on your right joycon...

**Comment by mrbob312** [comment]
Press the + symbol on the right joy con



On 23 Apr 2019, at 09:07, Mark Aronin <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you guys please elaborate what you mean by "close it with +"? What key combination do you need to do?

Thanks!

**Comment by Georgenko** [comment]
> 
> 
> First: Make sure, no USB is plugged into your console.
> Second: Press the + button on your right joycon...

The first step isn't necessary for me, i'm using atmosphere tho.
