### ISSUE TITLE
Wrap-around and super speed right stick don't get along

### ISSUE THREAD

**Issue by CecilFF4** [XorTroll/Goldleaf#275]
## Feature description

Can you implement an options menu or something to disable the wrap-around or customize how fast the right stick scrolls? Because, combined, they make it nigh on impossible to go to a file/folder. Rolling back to a nightly I was using because 0.5 stable just isn't cutting it for me. :(

**Comment by lookye** [comment]
Why dont you just use the directional buttons on the left Joycon?

**Comment by CecilFF4** [comment]
Because those have no repeat. I like a repeater, just one that's not going at light speed.

**Comment by fennectech** [comment]
Should also be quite a bit slower. With a delay after the first move down.

**Comment by XorTroll** [comment]
Fixed adding delay on Plutonium, will be applied on 0.6 :)
