### ISSUE TITLE
Implement splitting for nsp dumps

### ISSUE THREAD

**Issue by Sirius902** [XorTroll/Goldleaf#276]
Implement splitting for nsp dumps

Please add an option to dump nsps into 4gb parts instead of into one large file.

## Benefits

This would allow those who have a FAT32 formatted SD card to dump nsp files larger than 4gb.

## Additional information

If it helps gcdumptool by DarkMatterCore (https://github.com/DarkMatterCore/gcdumptool) has this feature for dumping game carts.

**Comment by XorTroll** [comment]
Done for 0.7
