### ISSUE TITLE
Error 0x177a02

### ISSUE THREAD

**Issue by SegFault42** [XorTroll/Goldleaf#277]
# Error 0x177a02

## Bug description

Hi, i'm trying to install "Baba is you" from goldleaf and i have this error : 0x177a02

## Your setup

- **Console firmware**: [ 5.1.0 ]

- **CFW with version**: [ ReiNX 2.0 and Atmosphere 0.8.6 ]

- **Goldleaf version**: [ 0.5 ]

## Bug reproduction

Just install bab is you with the same config as me

## Additional information

I use Kosmos, Fat32 FS and gbatemp sigpatch

**Comment by lookye** [comment]
You cant install that title as your FW [ 5.1.0 ] it too low. Its not a problem with Goldleaf.

**Comment by SegFault42** [comment]
@lookye And what about the bypass firmware feature ?

**Comment by friedkeenan** [comment]
That's not a magic cure-all. If a game legitimately needs a higher firmware, the game won't work. Not sure that's what's happening here though.

**Comment by lookye** [comment]
@SegFault42 
Ignoring the FW does not do the magic. Titles have a Master Key (easy description: minimum FW to install/play) and an expected fw (the fw youll need under normal circumstances).

And the title you want to install does only work if you have at least FW 6.2

**Comment by blairfancy** [comment]
Not aggree with your comment i have the same issue with crash bandicoot that require FW4.01 while i m on FW 6.2

**Comment by lookye** [comment]
@blairfancy 
To quote someone else about the same error code:

> You either forgot the FS patches if you're launching with fusee-primary or you forgot kip1patch=nosigchk in hekate's config if you're launching through it via fss0=atmosphere/fusee-secondary.bin.

But: What the guy above wanted, was a problem bc of his low firmware.
Also he never replied here if it was solved or not, so I assume updating the FW was the thing to solve it for him.

**Comment by SegFault42** [comment]
Yes, solved by upgrading fw.

**Comment by chadbanks** [comment]
I am getting this error when installing the most recent nsp update for Rocket League. I'm on the most recent release of horizon os, atmosphere and goldleaf.
