### ISSUE TITLE
Title not updated but installed separately

### ISSUE THREAD

**Issue by chucktheripper** [XorTroll/Goldleaf#278]
# Title not updated but installed separately

## Bug description

I tried to update Dead Cells v1.0.0 to UPD 1.0.2 but instead of updating it, it installs it seperately without a reference in the "Installed Titles"-List. Probably it's because the Title ID of v1.0.0 is 0100646009FBE000 and the Title ID of v1.0.2 is 0100FC000AEF0800.

After the Installation, v1.0.2 appears as own installed Title and can't be opened with a message which says, that the title needs to be installed. I removed it thru the options, because it didn't appear in the "Installed Titles"-List after updating.

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: Atmosphere 0.8.5

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

Install Dead Cells 1.0.0 thru USB-Installer (which now works flawless for me on the named setting)
Update Dead Cells to v1.0.2 thru USB-Installer
v1.0.0 is now installed as Basic Title
v1.0.2 is not listed in the Details of the Basic Title "Dead Cells"
v1.0.2 can't be found / removed from "Installed Titles" list

## Additional information

I couldn't find information about a v1.0.1, or even figuring out, how Titles are versioned.
Using Kosmos v11.11.1 with Goldleaf 0.5, exFAT formatted SD-Card

**Comment by deadair3210** [comment]
Did you get the update through a normal means like eShop? Update titleids are usually at least similar to the original I'd, with 800 at the end instead of 000. Maybe wrong region update?

**Comment by lookye** [comment]
To be honest, thats not a problem with Goldleaf.
The base game you installed is the western version.
The Update you installed is from the asian version.

It seems they dont share their IDs. Thats why the update got installed seperately and doesnt apply on your base game. Youll need to find the Update for your game version otherwise it will not work.

**Comment by chucktheripper** [comment]
Thanks for your response i'll try to find another version and try to find out which versions are valid for my configuration!
