### ISSUE TITLE
0Xb64 on install

### ISSUE THREAD

**Issue by andmaltes** [XorTroll/Goldleaf#279]
## Bug description

I am trying to USB install (goldtree 0.5) Yoshi's NSP with the V0.5 and I got the following error: 

An error ocurred attempting to install the NSP:
Error: 0xb64
Module Goldleaf 356)
Description: Invalid USB Command (5)

I am using REINX over 6.2.0

I am not sure how can I provide further details. Please let me know if there is some kind of log that I may share.

Thanks,

**Comment by andmaltes** [comment]
The file was with the ReadOnly check on windows and that seemed to be causing the issue,

**Comment by ANOUNYMOSGAMER** [comment]
@andmaltes can you please clarify what you mean by "the file was with the read only check on windows"?
I right clicked my nsp file and the read only was not ticked, or do I need an application to open the nsp file and see whether its ticked from there?

**Comment by Nuckfugget** [comment]
> @andmaltes can you please clarify what you mean by "the file was with the read only check on windows"?
> I right clicked my nsp file and the read only was not ticked, or do I need an application to open the nsp file and see whether its ticked from there?

Not sure if you've figured it out yet but you have to right click on the nsp and go to properties and uncheck read only.

**Comment by Kinc4id** [comment]
I have the exact same issue. My file is not read only.

**Comment by pabloveliz93** [comment]
I had the same error code and the solution from @andmaltes  worked, just right-click the .nsp and then uncheck the Read Only box that is near the bottom.

**Comment by TariqMK** [comment]
Sadly I am having the same issue.

- The file is not read only
- I have plugged the USB C cable into different ports

But still the same error, I have no idea how to proceed.

**Comment by fabian1983** [comment]
i confirm solution is read only check on the NSP file

it should be off

**Comment by saudisa** [comment]
> i confirm solution is read only check on the NSP file
> The read only flag should be off !
> it worked for me. Thanks for reading

hi , still the same error , (Error: 0xb64)

**Comment by Pan2310** [comment]
He confirmed the solution. Thank you

**Comment by branch3s** [comment]
> 
> 
> > i confirm solution is read only check on the NSP file
> > The read only flag should be off !
> > it worked for me. Thanks for reading
> 
> hi , still the same error , (Error: 0xb64)

hey, I had the same issue, the file may not be read only but check the folder, if the folder is read only it applies to the files within regardless of their individual properties
