### ISSUE TITLE
Manage console content not removing files from SDCard

### ISSUE THREAD

**Issue by k3dubeu** [XorTroll/Goldleaf#280]
Removing Base and Updates from Manage console content does not delete the files in the sd Nintendo/Contents/registered directory. Files still present and taking up free space. 

Version: v0.5
CFW: AMS 0.8.6
FW: 6.2.0

**Comment by XorTroll** [comment]
Hmm, try rebooting after that, apparently the content is automatically cleaned.

**Comment by k3dubeu** [comment]
I've tried nemerous times and did not notice my SDCard Freespace to increase. The files in the SDcard was still present. Though after deleting content (Uninstalling a game through the Nintendo firmware) and then rebooting, my freespace updated. It may seem that the SDCard content is only reevaluated after installing/removing software using the stock method.
