### ISSUE TITLE
Wrong Translation

### ISSUE THREAD

**Issue by Nonosabes** [XorTroll/Goldleaf#281]
Wrong Translation under User Accounts when you try to rename the account, It reports "Eliminar duenta" it should be "Eliminar cuenta"
![wrong translation](https://user-images.githubusercontent.com/37082681/55266671-a1651e80-5254-11e9-94ce-be22d99952f9.jpg)

**Comment by XorTroll** [comment]
Yo mismo hice la traducción a español, algún error se me escapó al parecer.
Gracias por el aviso

**Comment by XorTroll** [comment]
Arreglado hace algunas semanas.
