### ISSUE TITLE
Cannot install any version of GoldLeaf via USB

### ISSUE THREAD

**Issue by v1sla** [XorTroll/Goldleaf#282]
Hi all!

I have a problem with installing any version of GoldLeaf on my SD card via USB. It stops at 4/4 or 3/5 (depending on the GoldLeaf version i try to install) and the avarage speed drops to 0. I tried different GoldTree versions aswell and the result is the same. What can I do with that? Is there any other way to install GoldLeaf? 
Right now I have a 0.4 GoldLeaf version installed.

**Comment by XorTroll** [comment]
Update to 0.5.

**Comment by v1sla** [comment]
@XorTroll That's what I wanted to do but unfortunatelly have no idea how - except the nsp file installation via USB. Any suggestions?

**Comment by patrikhejnar** [comment]
Download .nro version to switch folder on your micro sd, run from Album applet and install newest version of goldleaf

**Comment by v1sla** [comment]
It worked! Thank you guys :)
