### ISSUE TITLE
Error 0x964

### ISSUE THREAD

**Issue by pabermod** [XorTroll/Goldleaf#284]
# [ Error 0x964 installing new update ]

## Bug description

[ When installing new update of a game this error appear ]

## Your setup

- **Console firmware**: [ 7.0.1 ]

- **CFW with version**: [ Atmosphere 0.85 ]

- **Goldleaf version**: [ 0.5 ]

- **Goldtree version**: [ 0.5 ]

## Bug reproduction

1. Install a game
2. Install an older update
3. Install a new update

## Additional information

Error: 0x964
Module: Goldleaf (356)
Decription: The module is already installed (4)

**Comment by pabermod** [comment]
Also after the error appears i can't go back from the usb install screen (it gets stuck at installing content XXXXXXXXX (X of XX)

I cant exit the app with Plus button, and if I press home button I get a system crash

**Comment by SassyCultist** [comment]
I am getting this same error on firmware 6.2.0. It seems to be similar to the issue that I reported on Goldleaf 0.4. #218

**Comment by XorTroll** [comment]
USB (on 0.5) doesn't give the option to reinstall the title, but 0.6 will probably add this.
You would need to uninstall the installed title/update and then retry.

**Comment by SassyCultist** [comment]
Uninstalling first works fine but I hope this is fixed in 0.6

**Comment by diolos** [comment]
I have the same issue. I have Original Zelda BOTW at version 1.5, with 2 dlc succcesfully transferred via usb with goldleaf. But when I try to install 1.6 nds I get the same error, telling me that its already installed, but it isnt true and I can´t install. Any news about that? Thanks!

**Comment by 5H00T4** [comment]
> USB (on 0.5) doesn't give the option to reinstall the title, but 0.6 will probably add this.
> You would need to uninstall the installed title/update and then retry.

But 0.3 could already do that. :|
Bit disappointing that it regressed in some points since then.

Nevertheless, looking forward to 0.6.

**Comment by MAN-biker** [comment]
The same error. Cant install update by USB.

**Comment by Marcoskio25** [comment]
I found a possible reason. Goldenleaf is not installing more than one application at a time, so I have to install what I want, close it with the Home button, open goldenleaf again, and continue installing one at a time.
