### ISSUE TITLE
Install from internet [personal cloud]

### ISSUE THREAD

**Issue by AlgusDark** [XorTroll/Goldleaf#285]
# Network install from internet

## Feature description

Would be really interesting to use cloud for nsp so you don't need to connect switch to PC.

## Benefits

+ You can use cloud as if you were using similar store for homebrew
+ You can have your personal backups in the cloud to use anywhere.

## Additional information

So, you could use Google Drive (API is very friendly) to scan your folders and check your titles there.

**Comment by XorTroll** [comment]
Can be related to #162
