### ISSUE TITLE
set archive bit on directories

### ISSUE THREAD

**Issue by fennectech** [XorTroll/Goldleaf#286]
# [ Feature name or title ]
I would like to set the archive bit on split NSPs as linux systems provide no way to do this.
## Feature description
I would like to be able to set the Archive bit on split NSPs so they can be installed.
[ Please describe your desired feature as detailed as possible here. ]
It would be nice to be able to set the archive bit on folders
## Benefits
Allows split nsps to be used without using a windows computer.

**Comment by tantoinet** [comment]
Same Feature request here. Please help us on this :)
As a workaround, [NX-Shell](https://github.com/joel16/NX-Shell/) allows setting the Archive bit, but crashes inconditionally when leaving the app on 7.0.x (tested with NX-Shell 1.20 + ReiNX 2.1.1).

**Comment by colibre** [comment]
You can set the archive bit using `mattrib`

**Comment by fennectech** [comment]
Awesome.  No longer have to spin up my winders VM to set the archive bit!

**Comment by XorTroll** [comment]
I certainly like this idea, will be looked for 0.7.

**Comment by XorTroll** [comment]
Added for 0.6 :)
