### ISSUE TITLE
Update and DLC Dumping

### ISSUE THREAD

**Issue by reikarin** [XorTroll/Goldleaf#287]
## Feature description

dump game's update and dlc, only base game atm that can be dumped using goldleaf 

## Benefits

so we dont need to backup nand to dump these file 

## Additional information

i am using this tool for dumping update and dlc
https://github.com/CaitSith2/SwitchSDTool

**Comment by XorTroll** [comment]
Will do some tests these days, won't be so complex to add.

**Comment by XorTroll** [comment]
Fixed for 0.7 ;)
