### ISSUE TITLE
FW 6.2.0 - FS (1) Wont Install NSP located on SD

### ISSUE THREAD

**Issue by imPRAGMA** [XorTroll/Goldleaf#290]
# FW 6.2.0 - FS (1) Wont Install NSP located on SD

## Bug description

Im on 6.2.0, have a Tinfoil Forwarder NSP on SD, when trying to install it fails and thinks it could be sigpatches as the cause. But im on Atmosphere with all signpatches up to 7.0.1 on my Switch's SD Card.

## Your setup

- **Console firmware**: 6.2.0

- **CFW with version**: Atmosphere 0.87

- **Goldleaf version**: 0.5

- **Goldtree version**: ? n/a?

## Bug reproduction

Be on 6.2.0 get sig patches from AtlasNX's Kosmos SDFiles website (exefs folder) and try install an NSP.

**Comment by XorTroll** [comment]
Might be a corrupted filesystem?
Do you use ExFAT or FAT32?

**Comment by lookye** [comment]
Everything worked for me as intended.
Tested with the same setup you wrote down but with normal NSPs and not forwarders.

**Comment by imPRAGMA** [comment]
ExFAT

**Comment by lookye** [comment]
Sounds like you got your card corrupted then. Is the error still there for you?

**Comment by imPRAGMA** [comment]
I have since deleted and recopied all atmosphere stuff, works now probably a corruption
