### ISSUE TITLE
Can't update games through USB

### ISSUE THREAD

**Issue by mrbob312** [XorTroll/Goldleaf#291]
# Can't update games through USB

Can't install updates through USB, you'll get a Game already installed error instead of the usual remove older updates message

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: kosmos 12.0.1

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

Install an update for a game through USB that already has an update

**Comment by friedkeenan** [comment]
I can confirm this issue persists on the latest commit, though not with all games

**Comment by friedkeenan** [comment]
This appears to happen if you already have an update installed. I think this problem is also connected to how you can't install multiple DLCs

**Comment by Smoker1** [comment]
Still happening. I installed a Game, it has 3 Updates, 1 just wont Install for some reason, the 2nd does, but I try to Install the last one, and it says it is already Installed???????? Should have a Option to Force Install if "Already Present"
