### ISSUE TITLE
No confirmation dialog shown upon directory deletion

### ISSUE THREAD

**Issue by agsimmons** [XorTroll/Goldleaf#292]
# No confirmation dialog shown upon directory deletion

## Bug description

When deleting a directory, no dialog box is shown where the user gives confirmation for the deletion. When deleting a file, however, confirmation is required, which leads me to believe this is an oversight.

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: Atmosphere 0.8.7

- **Goldleaf version**: 0.5

- **Goldtree version**: N/A

## Bug reproduction

Go to Browse SD Card, Press 'Y' when hovering over a directory, select the 'delete' option

## Additional information

N/A

**Comment by XorTroll** [comment]
Known bug, thanks for reporting it.

**Comment by XorTroll** [comment]
Fixed on 0.7 (forgot it, since it wasn't that serious :P)
