### ISSUE TITLE
USB Installtion running slow on Fw 8.0.0

### ISSUE THREAD

**Issue by gary69** [XorTroll/Goldleaf#294]
# [ Bug report title ]

## Bug description

USB Installtion transfer running slow on FW 8.0.0

## Your setup

- **Console firmware**: 8.0.0

- **CFW with version**: Kosmos V12.1 Atmosphere 0.88

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5.0.0

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

![58809829_317613338925663_990648242775523328_n](https://user-images.githubusercontent.com/49876471/56508792-643c3580-654f-11e9-9546-d43dad8cd4ad.jpg)

**Comment by XorTroll** [comment]
If others also can reproduce it then I'll take it as USB's issue, otherwise I guess it could be casual, such as related to the USB cable.

**Comment by lookye** [comment]
I tested it on FW 8.0.1 via USB. The speed i get is around 18-22MB/s

**Comment by XorTroll** [comment]
In 0.6 both USB and SD/NAND speeds are 24MB/s or slightly more, USB may be a little bit lower.

**Comment by XorTroll** [comment]
#220 better to move all issues with USB to a general one.
