### ISSUE TITLE
 I really hope that USB installation will restore multi-threading.

### ISSUE THREAD

**Issue by Aeuko** [XorTroll/Goldleaf#296]
not because single thread will be more stable, unable to install still can not be installed! 
Test speed single thread 15s / s, multithreading 30m / s

**Comment by XorTroll** [comment]
This will be considered, since threading made things more unstable, and I think slower but stable is more desirable.

**Comment by XorTroll** [comment]
Also #220 better to move all issues with USB to a general one.
