### ISSUE TITLE
Doesn't show Files in SD Card with é and '

### ISSUE THREAD

**Issue by imPRAGMA** [XorTroll/Goldleaf#299]
Doesn't show Files in SD Card with é and '
For example, if it has: é AND ' in the filenames title, it wont show in Goldleaf

[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: 6.2.0

- **CFW with version**: Atmosphere 0.85

- **Goldleaf version**: 0.5

- **Goldtree version**: N/A

## Bug reproduction
If we change the é to e and remove the ', it will then show.
Example: Pokémon Let’s Go, Eevee! (Wont work) Pokemon Lets Go, Eevee! (Will work)

**Comment by XorTroll** [comment]
Probably UI libraries' issue.
Will look into it later.

**Comment by ThatNerdyPikachu** [comment]
@XorTroll It's FS -- this even happened with Adubbz's Tinfoil.

**Comment by roothorick** [comment]
To clarify: This is a bug in Horizon itself.

VFAT (the FAT12/16/32 extension that enables non-8.3 filenames) and exFAT encode file names in UTF-16, but Horizon encodes filenames as a kind of broken noncompliant Shift-JIS, in that what in SJIS is *supposed* to be a one-byte character is instead padded to two bytes. This makes it align with UTF-16 such that the base ASCII codepage lines up, but nothing else does. So anything non-ASCII will cause all kinds of breakage in pretty much every homebrew, and even two ASCII characters (\ and `) will show up wrong (¥ and ‾ respectively).

**Comment by XorTroll** [comment]
^ Nothing we can do, however via remote PC this is handled fine in 0.7.
