### ISSUE TITLE
delete system titles

### ISSUE THREAD

**Issue by LoliHitler** [XorTroll/Goldleaf#300]
cannot delete system titles, not sure if its a limitation, restriction of the app to protect the stupid, or a bug, but i cant find anything on the error it gives me when i try

**Comment by lookye** [comment]
If you really want to delete system titles, you can edit the Goldleaf.ini file to allow it.
If you dont have a Goldleaf.ini create one and add this string:
> allowRemoveSystemTitles=true

**Comment by Strat00s** [comment]
What would this be useful for?

**Comment by LoliHitler** [comment]
i want to try and delete badword filter like in 3ds and thx

**Comment by LoliHitler** [comment]
> If you really want to delete system titles, you can edit the Goldleaf.ini file to allow it.
> If you dont have a Goldleaf.ini create one and add this string:
> 
> > allowRemoveSystemTitles=true

**Comment by LoliHitler** [comment]
> If you really want to delete system titles, you can edit the Goldleaf.ini file to allow it.
> If you dont have a Goldleaf.ini create one and add this string:
> 
> > allowRemoveSystemTitles=true

it didnt work, not sure if i made the ini wrong or if i need to place it in a specific directory
i pasted the line into a txt file and renamed goldleaf.ini and placed at root of goldleaf folder

**Comment by lookye** [comment]
You can have a look here:
https://github.com/XorTroll/Goldleaf#configuration

**Comment by LoliHitler** [comment]
> You can have a look here:
> https://github.com/XorTroll/Goldleaf#configuration

i checked it and i cant find what i did wrong, also the line u gave me isnt even listed as an option on that site

**Comment by lookye** [comment]
`
; Goldleaf settings file
; With paths, an initial slash is recommended (/)

[General]

; Use the custom language to be set below. By default Goldleaf will attempt to use the console's language.
useCustomLanguage=true

; Available languages: English (en), Spanish (es), German (de), French (fr), Italian (it)
customLanguage=en

; If used, the path where the common keys should be located. Goldleaf will warn if this path doesn't exist.
keysPath=/switch/prod.keys

[Content]

; In the extremely weird case somebody would like to remove NAND SYSTEM titles, set this to true.
allowRemoveSystemTitles=false

; Warn when attempting to remove a ticket supposedly used by a present title.
warnRemoveUsedTickets=true`

This is how my ini file looks.

**Comment by LoliHitler** [comment]
damn, yeah mine looks nothing like that

**Comment by LoliHitler** [comment]
is that what im supposed to paste into my ini file

**Comment by lookye** [comment]
Try it

**Comment by LoliHitler** [comment]
im not sure how to make 1 then, but yeah that might be the reason it doesnt work

**Comment by lookye** [comment]
Use notepad++ or something similar.

**Comment by LoliHitler** [comment]
about to test it out

**Comment by LoliHitler** [comment]
no matter what i do i get nand system titles are blocked from being removed, thx for all ur help, its disappointing but i ill get over it
