### ISSUE TITLE
[Feature Request] Disable sleep when installing large NSPs

### ISSUE THREAD

**Issue by shedeus** [XorTroll/Goldleaf#301]
I hate having to babysit the switch to keep it from falling asleep while installing large NSPs.  Can you please have the application disable sleep while installing NPSs?  Thank you and I love the tool!!!

**Comment by austin5623** [comment]
Just turn off sleep mode in System Settings>Sleep Mode.

**Comment by devvdi** [comment]
@austin5623 thanks for you advice, but I'm still giving +1 for OP's request.

**Comment by XorTroll** [comment]
Done for 0.6 :)

**Comment by shedeus** [comment]
0.6!?!?!?  You are my hero.  THANK YOU!!
