### ISSUE TITLE
Limited amount of DLCs shown

### ISSUE THREAD

**Issue by Shadowghost** [XorTroll/Goldleaf#302]
# Limited amount of DLCs shown

## Bug description

I ran into this when installing DLCs of **Taiko no Tatsujin Drum 'n' Fun!**. This games has tons of DLCs (ID range from _[...]001_ to _[...]045_) and when I checked the installed content via Goldleaf it only shows DLC up to ID _[...]029_.
When installing DLCs with higher IDs, Goldleaf does it's job and finishes without an error, but the DLC does not show up. If installed again there is no message telling me that the DLC is already installed. I checked all the NSPs again and they are clean CDN NSPs with required firmware equal or lower to mine.
Since I don't have any other games with that much DLCs, I couldn't check if it's only occurring on this game.

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: Atmosphere 0.8.9

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction
Install **Taiko no Tatsujin Drum 'n' Fun!** and it's DLCs. After that check installed content and reinstall DLC with an ID > [...]029, you'll see that no DLC with an ID > _[...]029_ is listed even though you installed it.

**Comment by XorTroll** [comment]
#315 might be also related to this...?

**Comment by Shadowghost** [comment]
Yeah, most likely caused by the same bug.
