### ISSUE TITLE
Translation Mistake

### ISSUE THREAD

**Issue by ilegitimado** [XorTroll/Goldleaf#304]
## Translation error
On the Spanish version of Goldleaf, inside 'Administrar cuentas de usuario' the 3rd option should be 'Eliminar cuenta' and NOT 'Eliminar duenta'. (I'm a native Spanish speaker).
## My setup

- **Console firmware**: [ 7.0.1 ]

- **CFW with version**: [ Atmosphere 0.8.9 ]

- **Goldleaf version**: [ 0.5 ]

- **Goldtree version**: [ 0.5 ]

## Bug reproduction
Open Goldleaf. Go to 'Administrar cuentas de usuario'. Select an user. The 3rd option is not written correctly. 
![15581956613685022377933736751953](https://user-images.githubusercontent.com/50776178/57972231-db6eb900-7997-11e9-8789-e9e8b90b3d81.jpg)

**Comment by XorTroll** [comment]
Yo he sido el traductor de español ya que yo también soy español, ya me di cuenta del fallo. Ya está corregido, y la próxima versión lo tendrá arreglado.
