### ISSUE TITLE
Error 0xdc7c

### ISSUE THREAD

**Issue by HoneyOTU1337** [XorTroll/Goldleaf#306]
# [ Error 0xdc7c ]

## Bug description

[ Trying to delete a linked user, but it will not work. Settings app wants to connect to internet to unlink the account but can't so it does not delete the user. I use Goldleaf to delete user but it tells me Error: 0xdc7c Module: Account (124) Description: Unknown or undocumented error (110) ]

## Your setup

- **Console firmware**: [ 7.0.1 ]

- **CFW with version**: [ Kosmos v12.2 ]

- **Goldleaf version**: [ 0.5 ]

- **Goldtree version**: [ 0.5 ]

## Bug reproduction

[ 1. Open Goldleaf 2. Select Manage user accounts 3. Select a user that is linked 4. Delete and confirm ]

## Additional information

[ The linked user has a dark gray question mark box on the corner of their profile picture. ]

**Comment by lookye** [comment]
It is not possible to delete linked user accounts. 
Normal behavior of Goldleaf not to delete that linked account.

**Comment by zTKS** [comment]
I have this issue too.

I'm using Incognito to change my Prodinfo but even after restoring it in airplane mode, it still doesn't work.

**Comment by XorTroll** [comment]
Account is linked and needs to be unlinked before deleting.
0.7 has unlinking as a feature ;)
