### ISSUE TITLE
File corruption during USB installation if MicroSD card is full

### ISSUE THREAD

**Issue by JohnTheNerd** [XorTroll/Goldleaf#314]
# File corruption during USB installation if MicroSD card is full

## Bug description

If your microSD card is full to the brim and you try to install NSP's through USB that are larger than the free space, Goldleaf will corrupt random files in your microSD card. In my case, it was able to corrupt sept which prevented boot until restored.

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: Atmosphere/Kosmos (v12.2/v0.8.10)

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

Simply install NSP's until you no longer have any space, and try to continue installing.

## Additional information

A simple free space check would eliminate this problem in my opinion.

**Comment by tycho01** [comment]
I ran into this issue as well. If this were done while installing to the console itself, I fear this could overwrite save games as well.

**Comment by XorTroll** [comment]
This shouldn't make sense, since Goldleaf checks the SD card's free space before installing.

**Comment by tycho01** [comment]
I can't say I have an explanation, but I believe #324 corresponds to this issue as well.

**Comment by XorTroll** [comment]
As soon as 0.7 is released mind trying with it the same steps that caused this?

**Comment by lookye** [comment]
@JohnTheNerd @tycho01 any news from you on this case with the latest releases?

**Comment by JohnTheNerd** [comment]
I have (accidentally) tested this with the newest version and can confirm the issue no longer exists
