### ISSUE TITLE
Content Manager limit

### ISSUE THREAD

**Issue by NoWayOuy** [XorTroll/Goldleaf#315]
# Not all titles on Sd card show up in Content Manager

## Bug description

I am using a Sandisk 400gb exfat sd card with over 100 games installed. Only 70 are shown in content manager. All games are shown and can be launched on the home menu. 

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: ReiNX 2.3

- **Goldleaf version**: 0.5 nro

- **Goldtree version**: n/a

## Bug reproduction

Install more than 70 base titles on a 400gb sd card and check whether they all appear in content manager. 

## Additional information

Perhaps an option to increase the amount of time to spend reading sd card in config file would solve issue on large cards if this is a widespread issue

**Comment by SassyCultist** [comment]
I am having the same issue on 8.0.1 with Atmosphere 0.8.9 and Goldleaf 0.5.

**Comment by XorTroll** [comment]
Probably related to UI.

**Comment by XorTroll** [comment]
For those facing this, what exactly happens? the "menu items" are present but like the text/icons are black or invisible? If so, that's UI's issue.

**Comment by NoWayOuy** [comment]
For me at least, all items are shown completely and perfectly, all icons and text look good. For the items that are not shown they are simply not there at all, despite being payable from the home menu. Hope this helps

**Comment by SassyCultist** [comment]
I have updated to 8.1.0 and Atmosphere 0.9.2 since I first commented and the issue remains. Like NoWayOuy said, the icons are just not there for certain games. I have not experienced any graphical glitches.

**Comment by XorTroll** [comment]
Wonder if this is still present...

**Comment by NoWayOuy** [comment]
I have just gotten around to updating to goldleaf 0.7.3 and issue indeed seems resolved. All titles and updates now seem present. Thanks!
