### ISSUE TITLE
Add option to disable linked account check upon install

### ISSUE THREAD

**Issue by bmn001** [XorTroll/Goldleaf#316]
# Add option to disable linked account check upon install

## Feature description

Some apps will not launch if an account has not been linked to a Nintendo ID.  This is a feature request to have Goldleaf **optionally disable** that "linked account check" upon nsp install.

## Benefits

Users who have never connected their Switch to the Internet will have no linked account.

This option would allow those users to experience NSPs which are "locked" behind this account check and are otherwise not launchable.

## Additional information

One other way to accomplish this same goal might be to give Goldleaf the ability to "bless" an existing user account so that it behaves as if it were a linked account.  In that case there would be no need to patch installed NSPs at all.

**Comment by XorTroll** [comment]
This would require to modify the NACP of a title, so isn't as easy as it sounds.

**Comment by XorTroll** [comment]
Made this with a separate project (a sysmodule MitM'ing NS services), check it here: https://github.com/XorTroll/ControlMe

**Comment by bmn001** [comment]
DOPE!

Looks cool, thank you!
