### ISSUE TITLE
USB Queue support

### ISSUE THREAD

**Issue by pkly** [XorTroll/Goldleaf#317]
# USB Queue support

## Feature description

Allow the user to select multiple files in Goldtree instead of a single one, allowing to select the install target for the whole queue at once and making Goldleaf queue aware

## Benefits

When using USB install mode it's a huge pain to go through a bunch of NSP files, let's say installing totally legit DLC nsp's for Taiko (~40 files). It should be more or less easy to implement a queue mode, since single mode already works. Allow the user to select pre-set options for Goldleaf installation and simply push next files from Goldtree to Goldleaf via USB automatically, allowing to install large amount of NSPs or whatever else you might want to install.
This is only really useful when installing more than one nsp at a time, but it's still a viable use-case.

## Additional information

It would require re-working how errors are handled in Goldleaf, because currently they get the application completely stuck, requiring a restart of it if an error occurs while pushing a nsp file to the console via USB.

It could work like this:

1. Launch USB mode in Goldleaf
2. Open Goldtree, select more than 1 file
3. Goldleaf prompts the user with the mode selection (handle each file as separate install [current] or handle each file as queue)
4. If as separate: ask for location/ignoring firmware for each file, if not ask once and repeat the action each time for each file automatically
5. When errors occur show a popup that allows to stop the queue for a time (~10s/5s?), add another screen when the install finished with the status of the install (errors, success, files installed etc.)

**Comment by XorTroll** [comment]
Added option to install all NSPs in a directory on any location, so on PC over USB too :)
