### ISSUE TITLE
USB Install get stuck

### ISSUE THREAD

**Issue by Anubix88** [XorTroll/Goldleaf#318]
## Bug description

Goldleaf get stuck when installing a game through USB. Tried Goldleaf, NS-USBloader 5.1 and Tinfoil with Alluminium Foil. Tinfoil often also get stuck or crashes with error code 2345-0028 after random percentage (sometimes 3% sometimes 80%).
Tried 2 different SD cards booth FAT32.
Tried deleting placeholder and retry many times (even with full reboot).
Signpatches are updated for 8.1.0.
 
## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: AMS 9.1.0

- **Goldleaf version**: 5.0

- **Goldtree version**: 5.0

## Bug reproduction

Install a recent nsp game via USB.

## Additional information

![image0](https://user-images.githubusercontent.com/13465317/60047208-6b0b3400-96c9-11e9-8610-ff8b797b5baa.jpg)

**Comment by lookye** [comment]
Tinfoils problem is not our problem to solve.
From the error code you provided (2345-0028) it seems, that maybe your USB cable does not fit the full nsp transfer. If its possible for you, try another cable and see how it turns out.

**Comment by XorTroll** [comment]
#220 better to move all issues with USB to a general one.
