### ISSUE TITLE
USB installation sometimes causes grey screen of death.

### ISSUE THREAD

**Issue by jibbboot** [XorTroll/Goldleaf#319]
# USB installation sometimes causes grey screen of death.

## Bug description

Attempted to install NSP through goldleaf, Switch shows "waiting for PC...", after attempting to push the NSP the screen went straight to grey screen, forcing a full restart. I believe this is due to multiple instances of goldtree, as I accidentally opened two, closed one and tried to push the NSP through the remaining goldtree window.

## Your setup

- **Console firmware: 8.1.0**

- **Custom Firmware: ReiNX 2.4**

- **Goldleaf version: 0.5**

- **Goldtree version:0.5**

## Bug reproduction

Attempt to install an NSP when you have opened two goldtree windows, close one and use the remaining window.

## Additional information

I believe this can be fixed by limiting the amount of goldtree instances open at one time. Goldleaf also stayed on "waiting for PC" after opening two windows, and closing one of them, so I believe I didn't actually get a chance to push the NSP, it just crashed the switch because of the multiple goldtree windows open.

**Comment by XorTroll** [comment]
#220 better to move all issues with USB to a general one.
