### ISSUE TITLE
System crash after closing while USB connection active

### ISSUE THREAD

**Issue by Souperman9** [XorTroll/Goldleaf#320]
System crash after closing while USB connection active

After plugging the switch into a computer, closing Goldleaf will cause it to crash, requiring a reboot via fatal.

FW: 7.0 (but also happened while I was on 5.1
CFW: Atmosphere 0.9.2
Goldleaf 0.5

Just plug your switch in, and close goldleaf - instant crash.

If you unplug it beforehand, it doesn't seem to happen.

**Comment by lookye** [comment]
This error is known and can only be solved by downgrading/updating the Firmware.
See here: #274
