### ISSUE TITLE
Uninstalling a game killed microSD card

### ISSUE THREAD

**Issue by ntklgka** [XorTroll/Goldleaf#321]
# Uninstalling a game killed microSD card

## Bug description
Using goldleaf to remove a game from the system killed my microSD XC card. Details:

I removed Skyrim from my system using goldleaf, then I went into the Switch Settings > Data Management tab to check for free space on SD card. It showed as if no space was cleared up. So I restart the console and go on the Data Management tab again. This time as soon as I reach the tab, the console freezes for around 30 seconds, then in the microSD section it shows "not inserted". 

At this point I remove the sd card to try and format it on pc. I put it in an adapter and connect it to my PC (Windows 10). First I try right clicking the card but Windows Explorer freezes indefinitely, secondly I tried using a third party program to format the card, but the program won't launch while the card is inserted (as soon as I remove it the program launches, then if I insert it again, the program freezes). Third, I tried using CMD and diskpart to format it, but diskpart won't allow me to type commands while card is inserted (again, if I remove card then diskpart allows me to type commands). 

I also tried uninstalling the card drivers and restarting PC but to no avail.

Now heres the interesting part. I reinsert the card on my console and try to play some games. To my surprise, most games on the SD card are still playable. and some of the games on NAND are now corrupted, which doesnt make any sense. Also Goldleaf itself can still browse the contents of the microSD card, but this is really the only program which can still do it.

I already asked for a replacement at SanDisk but I thought I should just let you know.

## Your setup

- **Console firmware**: 8.0.0

- **CFW with version**: AMS 0.8.9

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

Remove a game using Goldleaf (I removed Skyrim), then go to Settings>Data Management. Look if it cleared up space, if it didnt, restart the console (I have autoRCM enabled), go to Settings>Data Management again, and if it freezes your console than that should be it

**Comment by lookye** [comment]
This sounds like a exFAT corruption which can occur over the time. Unfortunately it happened for you while using Goldleaf.

I have uninstalled content via Goldleaf in the past on exFAT and FAT32 successfully without any problems. Please report back if you´re using a SD in exFAT format.

**Comment by ntklgka** [comment]
I can't know for certain now, because I can't even right click on the card (is there any other way?), but I do have a third party program called "guiformat.exe" on my pc which I have used in the past to format my microSD card in NFTS seeing as Windows 10 doesn't support NFTS formatting but I really can't remember for certain how I last formatted it.

**Comment by lookye** [comment]
Thats too bad.
But from what you described, as mentioned above, its exFAT corruption and thus not a issue with Goldleaf. Just an unfortunate situation.
