### ISSUE TITLE
Unable to use the web browser

### ISSUE THREAD

**Issue by zTKS** [XorTroll/Goldleaf#322]
# Unable to use the web browser

## Bug description

When trying to use the web browser feature, after entering a URL Goldlead will crash my switch and I will receive an error code of 2000-0000 (0x0) from ReiNX and requires a reboot.

## Your setup

- **Console firmware**: 8.0.1

- **CFW with version**: ReiNX 2.4

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

1. Open Goldleaf 2. Go to web browser 3. Enter URL 4. Search for URL. 5. Goldleaf will freeze and crash the switch.

**Comment by XorTroll** [comment]
That's memory issues. From 0.6.1 web browser can only be used from the forwarder so there is always enough memory to use it.

**Comment by ELY3M** [comment]
I cant use browser even I launched it from one of my games.

https://youtu.be/RQks6zekh5I

**Comment by lookye** [comment]
You need to start Goldleaf via the Goldleaf Forwarder.
