### ISSUE TITLE
Error while trying to build from source

### ISSUE THREAD

**Issue by Le0T** [XorTroll/Goldleaf#323]
# Error while trying to build from source

## Bug description
Hi, I was trying to build Goldleaf from source but the make process gave me an error. I added the whole error in the .txt attached.

## Bug reproduction
Cloned the source with "git clone --recursive https://github.com/XorTroll/Goldleaf.git"
cd Goldleaf/Goldleaf
make

## Additional information
Error.txt contains the whole error.

[Error.txt](https://github.com/XorTroll/Goldleaf/files/3362371/Error.txt)

**Comment by XorTroll** [comment]
Some stuff needs fixing. Will fix it when I get back to my PC.
