### ISSUE TITLE
Goldleaf installed NSP via USB without checking available space.

### ISSUE THREAD

**Issue by gRoberts84** [XorTroll/Goldleaf#324]
# Goldleaf installed NSP via USB without checking available space.

## Bug description

Had installed a number of NSP's to SD Card and when attempting to run them (they appeared on my home screen) they said they were corrupted. Checking free space showed I had 500mb space left on SD card, even after removing them.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.92

- **Goldleaf version**: 0.5

- **Goldtree version**: N/A

## Bug reproduction

- Use ns-usbloader to transfer large NSP via USB into Goldleaf.
- Select storage with less space than size of NSP.
- Attempt to load game.

## Additional information

At no point does Goldleaf, nor ns-usbloader report that there is insufficient storage. It simply reports that it has successfully uploaded the files.

**Comment by XorTroll** [comment]
#314 confirms that its fixed on 0.7.x :P
