### ISSUE TITLE
Allow installing games with a higher firmware version requirement

### ISSUE THREAD

**Issue by Luro02** [XorTroll/Goldleaf#325]
It would make things a lot more convenient for people on lower firmware versions :)
I think of an implementation, where you can supply a keys.txt file and it will then try those keys first.

**Comment by lookye** [comment]
This does not work as you think it will.

**Comment by Luro02** [comment]
@lookye then enlighten me 😉

**Comment by lookye** [comment]
Contents have a "Required Firmware" and a "Master Key" which is different for every Firmware.

If you have a title with
Req. FW: 4.1.0
Master Key: 3.0.0 
you can ignore the Firmware and install/play it on Firmware 3.0.0 as the Master Key is from 3.0.0.

But if you have
Req. FW: 6.2.0
Master Key: 8.1.0
You cant install/play it on something lower than 8.1.0 and you cant get around it with a keys txt or something. Also newer contents (directly from N cant be fw downgraded that easily as in the past - see SSBU updates)

**Comment by Luro02** [comment]
you can easily get around it with a keys.txt, that contains the master key for 8.1.0. 
Tools like [reNXpack](https://github.com/The-4n/reNXpack) work by decrypting the entire file with the newer master key and re-encrypting them with an older one (or none).

**Comment by lookye** [comment]
Indeed but not on the console itself while installing or something.

**Comment by lookye** [comment]
So @Luro02 can this "issue" be closed?

**Comment by Luro02** [comment]
obviously not, just go away and let @XorTroll handle this issue
