### ISSUE TITLE
Uninstalling a title doesn't update the free space left on system

### ISSUE THREAD

**Issue by Ner0ls** [XorTroll/Goldleaf#326]
# Uninstalling a title doesn't update the free space left on system

## Bug description

After using the title manager from goldleaf, the free space on my system didn't get released, goldleaf shows the right info, but system's "Data management" doesn't.
The "fix" is to delete a game that's using the same memory Ex. if the goldleaf deleted title it's on SD then you have to delete a title stored in it, using the system's "Data management" tool.

## Your setup

- **Console firmware**: 8.1.0 emummc

- **CFW with version**: Atmosphere 0.9.2

- **Goldleaf version**: 0.5

- **Goldtree version**: 0.5

## Bug reproduction

1. Delete a title using goldleaf content manager
2. Enter settings
3. Check free space

## Additional information

I will post proof if necesary.

**Comment by XorTroll** [comment]
Reboot and it gets deleted.
0.6 fixes this.

**Comment by Ner0ls** [comment]
> Reboot and it gets deleted.
> 0.6 fixes this.

Forgot to mention, even after a reboot it's not fixed.

**Comment by RdlP** [comment]
With the latest release available in release section this doesn't work, even after reboot.

I have the same problem. I have removed content via golden leaf and space in emunand doesn't update.
