### ISSUE TITLE
List DLC titleIDs and versions (preferably names as well) in contents list

### ISSUE THREAD

**Issue by roothorick** [XorTroll/Goldleaf#327]
## Feature description

This is, uh, pretty obtuse:

![2019071021232600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/6509603/61018692-57183100-a35d-11e9-9de2-ec8523eeaa4c.jpg)

Each entry should give a little more description as to what each DLC actually is, at a minimum a title ID, preferably the name of the DLC and the version number.

## Benefits

It would be possible at a glance to tell which DLCs are or aren't installed, and if any installed DLCs are out of date.

## Additional information

Looks like the menu entry is filled here: https://github.com/XorTroll/Goldleaf/blob/35366ce86159d2de14582c2ff02e1880e246ab15/Goldleaf/Source/ui/ui_ContentInformationLayout.cpp#L29

**Comment by XorTroll** [comment]
Actually names can't be listed since the contents themselves don't have them, but since DLCs have their ""own ID"" (last number of the title ID) that could be listed

**Comment by XorTroll** [comment]
0.7.1 lists that "DLC ID" on content manager
