### ISSUE TITLE
Goldleaf doesn't recognize split NSP anymore

### ISSUE THREAD

**Issue by Yoshideking** [XorTroll/Goldleaf#329]
Hi,

So I think since 7.1 I can't get to install games wich are splitted to fit on a fat32 microSD.
I use the SplitNSP.bat program to make my files fit in the SD card wich makes files from "xXgame.00" to "xXgame.02" all packed on a "xXgame.nsp" folder.

In the good old days this worked on Goldleaf, but not anymore.

Could I get some insight on what may I be doing wrong?
When I select the folder on Goldleaf (the nsp folder), Goldleaf just open it. It doesn't give me the choice to install it.

I'm using the last Goldleaf (the application updated itself) and I am on latest Kosmos.
My OFW is on 7.01

Thanks in advance.

**Comment by deadair3210** [comment]
Have you made sure that the archive bit is set on the folder that has the nsp parts? That's what controls wether the switch treats the folder as a nsp or as a normal folder

**Comment by Yoshideking** [comment]
I'm sry, could you give me an example of that bit archive? Never seen it.
Thx for the quick answer.

**Comment by deadair3210** [comment]
For future reference you select the folder that the 00,01,02... Things are in and right click, properties, advanced, and check folder is ready for archiving

**Comment by XorTroll** [comment]
So can this be closed?

**Comment by Yoshideking** [comment]
For sure. Thank you so much for your time.

**Comment by DanielC-08** [comment]
Umm, I think this issue has been solved and should be closed. @XorTroll

**Comment by Yoshideking** [comment]
Yes, it is resolved. Sry for answering so late.

**Comment by FichteFoll** [comment]
In case anyone finds this and is on Linux, use [fatattr](https://github.com/Terseus/fatattr/).

**Comment by xi0n15** [comment]
@Yoshideking can you tell me how did you fix it with NX Shell? im noob here. Thanks in advance

**Comment by xi0n15** [comment]
nvm i got it
