### ISSUE TITLE
Not all Titles showing in Listing

### ISSUE THREAD

**Issue by Smoker1** [XorTroll/Goldleaf#330]
# [ Bug report title ]

## Bug description

[ Please describe your bug as detailed as possible here. ]
When going to Manage Titles/SD Card there are some Games that are not showing up. I will look for a Specific Game, and it is not in the Listings, but I am able to run the Game, and it shows up in the System.

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ] 8.0.1

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ] AMS 0.9.2

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ] 0.5

- **Goldtree version**: [ e.g. 0.5 ] Using NS-USBloader v0.5.2 (but does not Apply to Issue)

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]
As Described. Enter Goldleaf, move to 'Manage Console Contents', then select 'SD Card'. Look for a certain Game, in my case MK11 as an example, and it is not showing up, even though it is installed.

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
This bug is already known. See #315

**Comment by XorTroll** [comment]
Duplicate, closing
