### ISSUE TITLE
Crashes on startup with the language in Italian

### ISSUE THREAD

**Issue by davtur19** [XorTroll/Goldleaf#331]
# Crashes on startup

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.2

- **Goldleaf version**: 0.6

- **Goldtree version**: 0.6

## Bug reproduction

Just open it, always crash when opened

## Additional information

I have emuMMC and a sdcard with FAT32
I talked to others who have the exact same problem, sometimes it crashes like this (exfat sdcard)
![image](https://user-images.githubusercontent.com/13476215/62409758-6f860f00-b5dc-11e9-8d53-1d78027d0bfc.png)

My crash and logs:
![image](https://user-images.githubusercontent.com/13476215/62409720-e078f700-b5db-11e9-88e7-f73346a494f9.png)

[01564784297_010000000000100d.log](https://github.com/XorTroll/Goldleaf/files/3463559/01564784297_010000000000100d.log)

**Comment by davtur19** [comment]
Goldleaf crashes only when the console language is in Italian

**Comment by lookye** [comment]
Did it happen with Goldleaf 0.5 too?

**Comment by davtur19** [comment]
No, only with Goldleaf 0.6

**Comment by lookye** [comment]
We need to find what is causing the crash from the IT language strings.
If you dont mind, you can put the .json file in /switch/goldleaf/  and use goldleaf in english until the italian language is fixed.

[settings.json.zip](https://github.com/XorTroll/Goldleaf/files/3463635/settings.json.zip)

**Comment by davtur19** [comment]
https://github.com/XorTroll/Goldleaf/commit/84ed6864c5c8ebaaece531152d4bdcba1d750944#diff-f19dcb6fc8898519a26f8faf54435001

missing translation strings in the Italian language
320 lines en.json
280 lines it.json

**Comment by lookye** [comment]
Yup, I already saw it. Mind translation the missing lines? Easies way is to come over in the discord.

**Comment by lookye** [comment]
#332 solves this issue now. Thanks for the help.
