### ISSUE TITLE
Remote PC browser not working on fw 8.0.1 AMS 0.9.2

### ISSUE THREAD

**Issue by wicksand420** [XorTroll/Goldleaf#335]
# [ Bug report title ]
Remote PC browser not working on fw 8.0.1 AMS 0.9.2
## Bug description
System crashes back to home menu after selecting "Remote PC (via USB)"
[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
8.0.1
- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]
AMS 0.9.2
- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
0.6
- **Goldtree version**: [ e.g. 0.5 ]

0.6
## Bug reproduction
It happens every time I select Remote PC (via USB) with goldtree running on my pc
[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lodawn** [comment]
console firmware 8.1.0
kosmos 13.1
ams0.9.2
goldleaf 0.6

has same problem

**Comment by lookye** [comment]
How do you proceed?
Try this:
- Just open Goldleaf
- Connect USB
- Open Goldtree
- Select PC Drive

**Comment by lodawn** [comment]
> 
> 
> How do you proceed?
> Try this:
> 
>     * Just open Goldleaf
> 
>     * Connect USB
> 
>     * Open Goldtree
> 
>     * Select PC Drive

console messege:

[gtree:Warn] Make sure to open Goldtree after having opened Goldleaf on your console. Looking for connection...
[gtree:Log] Connection was established.

[gtree:Log] Received command: GetDriveCount
[gtree:Log] Received command: GetDriveInfo
[gtree:Log] Received command: GetDriveInfo
[gtree:Log] Received command: GetDriveInfo

goldleaf:
applet mode => os crash
title mode => error

**Comment by wicksand420** [comment]
Same thing here, exactly.

**Comment by William-Alspaugh** [comment]
8.1.0
AMS 0.9.2
Goldleaf 0.6
Goldtree 0.6

I open goldleaf, plug in my usb-c to my pc and switch, open goldtree, i get this:

[gtree:Warn] Make sure to open Goldtree after having opened Goldleaf on your console. Looking for connection...

[gtree:Error] Unable to find USB communication. Are you sure Goldleaf is open and plugged in?
Press any key to exit...

**Comment by lookye** [comment]
@wicksand420 @lodawn 0.6.1 got released. Is your problem solved with it?
Also make sure you installed the libusbK driver for the Switch on your PC (read the readme) and youre using Goldleaf and Goldtree from the same release.

**Comment by lodawn** [comment]
@lookye 

I tested on 0.6
I removed drive letter of windows reserved partition.
Drive name is 시스템 예약(Korean)
then problem solved.

0.6.1 also works fine.

**Comment by RinkuSonic41** [comment]
Kosmos 13.1 + sigpatches on FW 7.0.1
using Goldleaf 0.6.1
App crashes when trying the Remote USB feature.
When the app is closed from the system menu, the console crashes.
Goldtree just shows this:
[gtree:Warn] Make sure to open Goldtree after having opened Goldleaf on your console. Looking for connection...
[gtree:Log] Connection was established.

[gtree:Log] Received command: GetDriveCount

**Comment by lookye** [comment]
@RinkuSonic41 Ever used USB Installation before?
Please read this in the readme: https://github.com/XorTroll/Goldleaf#remote-pc-system

**Comment by RinkuSonic41** [comment]
> 
> 
> @RinkuSonic41 Ever used USB Installation before?
> Please read this in the readme: https://github.com/XorTroll/Goldleaf#remote-pc-system

dude, it´s exactly of what i´m talking about

**Comment by lookye** [comment]
Have you read it? Is libusbK installed? Did usb installation work on older versions? Have you tried another usb port and/or usb cable?

**Comment by RinkuSonic41** [comment]
Okay, apparently the issue is that the internal updater of Goldleaf actually downloads version 0.6 instead of 0.6
I had to manually update it (or maybe it was just deleting the goldleaf folder from the sd root folder)

**Comment by lookye** [comment]
@RinkuSonic41 tested the updater from 0.6 and it downloaded 0.6.1 and the forwarder as intended.

**Comment by wicksand420** [comment]
I'll test it out in a minute.

**Comment by wicksand420** [comment]
Same thing on latest version. I have goldtree running, in goldleaf I select explore contents, remote pc, crash every time, I'll just keep using the og tinfoil.

**Comment by XorTroll** [comment]
Does any of your drives have any special, non UTF8 characters? People have been facing problems with that

**Comment by wicksand420** [comment]
I have a ssd in my laptop, I don't have any other drives attached to my computer, but I do have my phone attached, I'm using it as a hotspot for internet.

**Comment by lookye** [comment]
That was not the question, does any of your plugged in devices (HDDs or may your phone) do have special characters?

**Comment by wicksand420** [comment]
That was it, it was the phone, thanks @XorTroll

**Comment by wicksand420** [comment]
Good work by the way.

**Comment by wicksand420** [comment]
@lookye no special characters, it was labeled as a z: unplugging my phone from my computer solved the issue.

**Comment by wicksand420** [comment]
The phone is a HUAWEI and the drive doesn't show any non UTF8 characters, but I suspect that is precisely what is happening. I just noticed that sometimes when I just plug it in it shows some Chinese writing instead of the drive name then it changes to Y538.

**Comment by wicksand420** [comment]
It was this 我的光盘
