### ISSUE TITLE
hello youkai arc dumps doesn't work

### ISSUE THREAD

**Issue by reshiram1** [XorTroll/Goldleaf#338]
# [ Bug report title ]

hello youkai arc dumps doesn't work

## Bug description

hello youkai arc dumps doesn't work in youkai watch 4 game on switch

[ Please describe your bug as detailed as possible here. ]

an internal error occurred in the game please press accept

## Your setup

- **Console firmware**: [ e.g. 8.1.0 ]

- **CFW with version**: [ e.g. beta Atmosphere 0.93 ]

- **Goldleaf version**: [ e.g. 0.6 or the exact nightly build ]

- **Goldtree version**: [ e.g. 0.6 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

an internal error occurred in the game please press accept

## Additional information

an internal error occurred in the game please press accept

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
Edit your post and fill out all information.

**Comment by lookye** [comment]
@reshiram1 0.6.1 got released. Is your problem solved with it?

**Comment by XorTroll** [comment]
Fixed in 0.6.1
