### ISSUE TITLE
Can't Install Fire Emblem Three Houses 0.6

### ISSUE THREAD

**Issue by Fever86** [XorTroll/Goldleaf#339]
# Can't Install Fire Emblem Three Houses

## Bug description

Error stating no sig patches or firmware too low. Showed an 11GB file as 2.8GB 

Reverted to 0.5 and no issues whatsoever

## Your setup

- **Console firmware**: [ 8.1.0 ]

- **CFW with version**: [ Atmosphere ]

- **Goldleaf version**: [ 0.6 ]

- **Goldtree version**: [ 0.6 ]

## Bug reproduction

As above. Unable to install with 0.6

**Comment by lookye** [comment]
This is a known bug (and affects all NSPs bigger 4GB) and will be resolved with 0.6.1

**Comment by husky73** [comment]
To me, it appears to be only related when installing via usb (goldleaf/goldtree combo). Same nsp installs correctly from sd.

**Comment by lookye** [comment]
@Fever86 @husky73 
0.6.1 got released. Is the problem now solved?

**Comment by husky73** [comment]
@lookye Yes! I Just got Super Smash Bros Ultimate (15+GB) installed flawlessy, I'll test others nsp and   eventually report back. Thank you!
