### ISSUE TITLE
Ignore FW Requirement Gone for USB

### ISSUE THREAD

**Issue by sawyermade** [XorTroll/Goldleaf#341]
# Cant ignore fw requirement over usb install

## Bug description

Cant ignore fw requirement over usb install, borking lots of nsp installs for me and I am sure other ppl as well. 

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: newest atmosphere/kosmos

- **Goldleaf version**: 0.6

- **Goldtree version**: 0.6

## Bug reproduction

Cant install South_Park_The_Stick_of_Truth_REPACK_eShop_NSW-VENOM : v-sptsor.nsp file. There are about 5-6 other ones I wasnt able to load either due to fw mismatch, I believe.

**Edit**: I can install the files that give me fw mismatch errors with 0.5 goldleaf/tree

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
1. 0.6 has a bug that let you not install files bigger than 4GB (See #339 )
2. 0.6 automatically ignores the firmware requirements.

**Comment by lookye** [comment]
@sawyermade 0.6.1 got released. Does this solve your problem?

**Comment by sawyermade** [comment]
Just retested it and it works like a charm now!
