### ISSUE TITLE
Going back from root of drive kicks back to "Explore content"

### ISSUE THREAD

**Issue by DanielC-08** [XorTroll/Goldleaf#343]
# # Going back from root of drive kicks back to "Explore content"

## Bug description

When going back from root of drive, the screen kicks back to "Explore content" instead of list of drives and folders.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.2

- **Goldleaf version**: 0.6.1

- **Goldtree version**: Version included in 0.6.1 release of Goldleaf

## Bug reproduction

1. Open Goldleaf 0.6.1
2. Press "Explore content"
3. Press "Remote PC (via USB)"
4. Select a DRIVE and not a FOLDER and open it
5. Press B and will be back at the "Explore content" menu

**Comment by XorTroll** [comment]
Don't see why this is an issue... is there a problem with having to select "Remote PC" again?

**Comment by XorTroll** [comment]
True, but not too relevant in my opinion to be put here in an issue.
