### ISSUE TITLE
Error: 0x291 - Can’t install .nsp

### ISSUE THREAD

**Issue by SehrBillig** [XorTroll/Goldleaf#344]
I have tried install a .nsp game but it won’t work. I become always an error code 0x291. I have put the sigpatches in the Atmosphère folder. But it won’t work.

Always this appears:
Error: 0x291
Modul: ETicket (145)

Console firmware: [ 8.1.0 ]

CFW with version: [ Atmosphere ]

Goldleaf version: [ 0.6.1 ]

**Comment by lookye** [comment]
Duplicate to #340 where you already posted.
