### ISSUE TITLE
Is there any way to use Goldleaf to boot an NRO from a flash drive?

### ISSUE THREAD

**Issue by niko1point0** [XorTroll/Goldleaf#345]
# [ Boot NRO from flash drive ]

The ability to plug in a flash drive and boot NRO file from the flash drive

[ Please describe your desired feature as detailed as possible here. ]

Homebrew developers would not need to copy files to the Switch, then boot them, and then delete them, but instead would just be able to plug in a flash drive and boot the NRO

It would be very helpful to my homebrew efforts, and I would be very thankful

**Comment by XorTroll** [comment]
No currently, but I assume this can be implemented by making a temporary copy. Otherwise, you can copy the NRO to the SD card manually and launch it.

**Comment by niko1point0** [comment]
Can this be done without connecting the Switch to a PC?

**Comment by lookye** [comment]
No, you need a PC + USB.
Otherwise, have a look into hbmenus nxlink function.

**Comment by deadair3210** [comment]
You could also use ftp if you wanted
