### ISSUE TITLE
[0.6.1]  Atmosphere  0.9.2：can't install The Legend of Zelda: Breath of the Wild 

### ISSUE THREAD

**Issue by pigpigabc123** [XorTroll/Goldleaf#346]
# [ Bug report title ]

## Bug description

 can't install The Legend of Zelda: Breath of the Wild  from sd card
## Your setup

- **Console firmware**: [ 8.1.0]

- **CFW with version**: [ Kosmos v13.1/Atmosphere  0.9.2 ]

- **Goldleaf version**: [ 0.6.1]

- **Goldtree version**: [ 0.6.1]

## Bug reproduction
can't install The Legend of Zelda: Breath of the Wild  from sd card
shows:  Error 0x291

just like this：
#340 https://github.com/XorTroll/Goldleaf/issues/340#issuecomment-518583428

**Comment by lookye** [comment]
Are you sure youre running Goldleaf/Goldtree 0.6.1?
Make sure youre not running 0.6 (if in doubt, download both again from the 0.6.1 release).

Also make sure you have the sigpatches installed (Kosmos deleted them).

**Comment by pigpigabc123** [comment]
> Are you sure youre running Goldleaf/Goldtree 0.6.1?
> Make sure youre not running 0.6 (if in doubt, download both again from the 0.6.1 release).
> 
> Also make sure you have the sigpatches installed (Kosmos deleted them).

Thank you, problem solved.
