### ISSUE TITLE
Tickets for titles installed on internal memory get listed as unused

### ISSUE THREAD

**Issue by mzino** [XorTroll/Goldleaf#348]
# Tickets for titles installed on internal memory get listed as unused

## Bug description

All titles and updates installed on internal memory have their ticket listed in the "unused tickets" section of Goldleaf.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.3

- **Goldleaf version**: 0.6.1

**Comment by XorTroll** [comment]
Just revised the code, and this is true. Goldleaf only checks if the ticket is part of a title in the SD card.
Next version will correct this, sorry :P

**Comment by XorTroll** [comment]
As said, fixed for 0.7 :)
