### ISSUE TITLE
Add "Get Max USB Packet Size" Command For Buggy USB Stacks

### ISSUE THREAD

**Issue by gudenau** [XorTroll/Goldleaf#349]
# Max USB Packet Size

## Feature description

The USB communications should be able to to request the maximum transfer size a server can handle.

## Benefits

Would allow for servers with buggy USB implantations to transfer larger files without causing errors.

## Additional information

For example, I'm developing a GoldTree server that uses libusb. When the Switch asks for a large transfer (like installing a game) libusb can't handle the packet size and refuses to send the packet.

**Comment by XorTroll** [comment]
Is this still an issue with latest Quark and Goldleaf?

**Comment by gudenau** [comment]
It's a limitation with libusb, but it can be worked around. I had made this issue before figuring this out.
