### ISSUE TITLE
NSP files don't show as NSP files in goldleaf.

### ISSUE THREAD

**Issue by gdcoltre** [XorTroll/Goldleaf#351]
I've looked everywhere and found no one having the same issue, so here we go.

3 NSP files are being read as non .nsp files. Basically when I browse them in goldleaf, the extensions appear as ".n" or ".ns", thus, cannot be installed. The files are correct - as in they are nsp files - and the files are not corrupted. Does anyone had the issue/know the solution? :)

Currently using goldleaf + goldtree 6.1. Firmware 8.1 Atmosphere 0.9.3
![error1](https://user-images.githubusercontent.com/54029489/62867045-b2d13380-bce8-11e9-8831-ea7a3ed42ad7.jpg)

**Comment by XorTroll** [comment]
I would say it's because of "special" characters (ó for instance) but not sure if that's the actual issue.

**Comment by gdcoltre** [comment]
Uhm, could be, but cadence of hyrule has no special characters and has the same issue :(

**Comment by deadair3210** [comment]
Maybe the title is too long?

**Comment by gdcoltre** [comment]
Don't think so, this file for Cadence of Hyrule is the update, the core game (that has the same name) installed just fine.

**Comment by tsunamigue** [comment]
It is something related with the characters, occured me in two files one worked removing the character "-" and the other removing the "é". I know is not much but try to renaming it to something stupid until this is solved.

**Comment by lookye** [comment]
This will be fixed in the next release.

**Comment by XorTroll** [comment]
^ related to unicode issues
