### ISSUE TITLE
Games still ask for a console update

### ISSUE THREAD

**Issue by Passe12345** [XorTroll/Goldleaf#352]
# Games still ask for a console update

## Bug description
Using Goldleaf v0.6.1, either using the USB method through Goldtree v0.6.1 or directly from the sdcard, two backups will still ask to update the console firmware when running them : Trials Rising & #RaceDieRun.

By downgrading Goldleaf to v0.5, it is possible to install and run them on my switch version (v8.0.1).

## Your setup

- **Console firmware**: v8.0.1

- **CFW with version**: Atmosphere v0.9.3

- **Goldleaf version**: v0.6.1

- **Goldtree version**: v0.6.1

## Bug reproduction

On firmware v8.0.1, install Trials Rising or #RaceDieRun using Goldleaf v0.6.1 and try to run it afterwards. It will ask for a console update.

## Additional information

None.

**Comment by lookye** [comment]
You can make a settings.json file and set firmware ignore to true (its disabled by default). Also fw ignore will be set to always enabled by default with the 0.7 release, so the things you install should work then.
