### ISSUE TITLE
Add Downloads folder to Explore PC

### ISSUE THREAD

**Issue by Ninjistix** [XorTroll/Goldleaf#353]
# Add Downloads folder to Explore PC

## Feature description

explore PC lists Desktop and Documents, but adding Downloads would be easier since that's where I download my nsps.

## Benefits

Would be faster than hitting Desktop then backing up and Navigating to downloads folder manually.

## Additional information

maybe the ability to bookmark a location when browsing PC

**Comment by XorTroll** [comment]
You can now add your favourite paths with Quark.
