### ISSUE TITLE
USB - Cannot navigate to folders with accents

### ISSUE THREAD

**Issue by BSoD38** [XorTroll/Goldleaf#354]
# Folders with accents cannot be opened through USB

## Bug description

Goldleaf/Goldtree considers folders as files if said folders contains special characters such as accents (é, è, à), and cannot be opened.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.3

- **Goldleaf version**: 0.6.1

- **Goldtree version**: 0.6.1

## Bug reproduction

Go to USB install menu, and try to access a folder with an accent in its name.

**Comment by BSoD38** [comment]
Apparently, this issue concerns files as well. Files and folders with special characters get their file name cut off, and cannot be opened.

Dashes in filenames (-) seem to trigger the issue too.

**Comment by lookye** [comment]
This will be fixed in the next release.

**Comment by XorTroll** [comment]
Fixed for 0.7 ^ :)
