### ISSUE TITLE
Installing RetroArch on my Switch

### ISSUE THREAD

**Issue by weenar** [XorTroll/Goldleaf#355]
# [ Bug report title ]
Installing RetroArch on my Switch
## Bug description
When I try to install through Goldleaf 6.1 or 5.0, I get an error for retroarch on switch saying "An error occured attempting to install the NSP: Error: 0x234c02.
Module: FS (2)
Description: Invalid NCA (might mean missing sigpatches or a too low firmware) (4518)"
[ Please describe your bug as detailed as possible here. ]
This error is for the file retroarch forwarder.nsp 
## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
Atmosphere 9.3.1
- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
Goldleaf version 6.1 or 5.0
- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
Are you using native atmosphere? If so, you can not install any NSP file.

**Comment by weenar** [comment]
I am using atmosphere 0.9.3 with Kosmos 13.2.1

**Comment by lookye** [comment]
Kosmos does not have sigpatches pre-installed. Grab them or you cant install nsp files in general. Its not a Goldleaf bug.

**Comment by weenar** [comment]
I downloaded joonie 86's kosmos patches but the problem still occurs.

**Comment by XorTroll** [comment]
Maybe the NSP is actually invalid (if other NSPs work then that might be the issue)

**Comment by deadair3210** [comment]
Make sure your sigpatches are for your version of the firmware, had that issue earlier where I updated the sigpatches of a console and forgot to update the firmware to match

**Comment by lookye** [comment]
@weenar So, how´s your progress?

**Comment by lookye** [comment]
Closed due to inactivity from OP.
