### ISSUE TITLE
Cant connect via USB Option to PC

### ISSUE THREAD

**Issue by Klauserus** [XorTroll/Goldleaf#357]
I use Goldleaf v6.1 with Switch 8.1 Atmosphére 9.3 and [this cable](https://www.amazon.de/USB-Kabel-Anker-PowerLine-90cm-Rot/dp/B01GN0M6NE/ref=sr_1_6?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=usb+c+cable&qid=1566317982&s=gateway&sr=8-6)

My PC make the typical usb sound when i connect the switch with it (in switch homemenu).  When i was enter Goldleaf it disconnect it automatical. i dont know why and goldleaf says "the switch isn´t connected to pc"

Is it the wrong cable? I send payloads with it and i thinks the cable is ok

thanks

PS: you made a realy great app for the switch. thanks a lot

**Comment by XorTroll** [comment]
Have you installed libusbK drivers with Zadig?

**Comment by lookye** [comment]
The cable seems to be a charging cable, not a data cable.
Also make sure you installed the libusbK driver (described in the readme) as Xor already said.

**Comment by XorTroll** [comment]
^

**Comment by Klauserus** [comment]
ok. its closed. sorry. it was the wrong cable.
