### ISSUE TITLE
Cannot view folder created from PC.

### ISSUE THREAD

**Issue by N3evin** [XorTroll/Goldleaf#358]
I try making a folder and added some nsp files into the folder via both window and mac. However, it did not show as folder, but as text file with 0 bytes.

Tried on both 0.6.1 and 0.5

**Comment by XorTroll** [comment]
Does it have archive bit?

**Comment by N3evin** [comment]
how do i check that? I am using mac right now

**Comment by N3evin** [comment]
Got it fixed!

Hetake -> tools -> Unset archieve bit
