### ISSUE TITLE
Goldleaf bad performance

### ISSUE THREAD

**Issue by piooop** [XorTroll/Goldleaf#359]
Goldleaf on .nro doesn't work at a good speed since 0.6.0 it only works well with the .nsp

**Comment by lookye** [comment]
Why havent you used the Issue template?

**Comment by XorTroll** [comment]
Any more reasons? that doesn't explain a lot. I've tested both, aside limitations for being a NRO/NSP I noticed little to no difference

**Comment by XorTroll** [comment]
Anyway, please use the issue template if you want to sumbit an issue
