### ISSUE TITLE
Goldleaf bad response time input from controllers on .nro

### ISSUE THREAD

**Issue by piooop** [XorTroll/Goldleaf#360]
# [ Goldleaf bad response time input from controllers on .nro ]

## Bug description ##
[ When i use Goldleaf on .nro format the inputs that i do with the controller (pluged in) sometimes it works sometimes it doesn't. ]

## Your setup

- **Console firmware**: [ 8.1.0 ]

- **CFW with version**: [ Atmosphere 0.9.3 ]

- **Goldleaf version**: [ 0.6.1 ]

## Bug reproduction

[ Run goldleaf in .nro format and use the default controllers. ]

**Comment by lookye** [comment]
Do you mean plugged in Joy Cons directly to the tablet or something else like the Pro Controller connected via cable?

**Comment by XorTroll** [comment]
This can't be related to Goldleaf. Looks like drifting/connectivity issues

**Comment by piooop** [comment]
yes i have the joy-con drift problem sorry
