### ISSUE TITLE
Not able to use internet browser even the hbmenu was launched from one of my games

### ISSUE THREAD

**Issue by ELY3M** [XorTroll/Goldleaf#361]
# [ Bug report title ]

## Bug description
I try to use internet browser after launched the hbmenu from one of game title.
See my video at https://youtu.be/RQks6zekh5I

# Your setup

- **Console firmware**:  8.1.0

- **CFW with version**:  stock atmosphere 0.9.3

- **Goldleaf version**:  6.1

- **Goldtree version**: not used

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
Goldleaf only can use the web browser when its launched specifically from the forwarder. This is not a bug.
