### ISSUE TITLE
option for old style game installs from pc please 

### ISSUE THREAD

**Issue by sw3d3r** [XorTroll/Goldleaf#362]
i have had to switch back to the older version because the new download from usb/pc makes a list on the switch that you need to scroll through, i have over 400 games i have to scroll to find the one i need, takes me so long. on the old version i could pick from my pc which file to install and it took me seconds to find, no scrolling. so i have reverted back to the older version. can you please add an option to allow you to chose on the pc when installing from usb so i can choose the file from goldtree again, instead of on the switch please and  thank you

**Comment by XorTroll** [comment]
0.7 will have an option for this, already implemented and working locally.
