### ISSUE TITLE
USB install  get stuck and open goldtree get error 0x2a8

### ISSUE THREAD

**Issue by Xianbei233** [XorTroll/Goldleaf#363]
# USB install  get stuck and open goldtree get error 0x2a8

## Bug description

click USB install and get freeze then open goldtree get error 0x2a8

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.3

- **Goldleaf version**: 0.61

- **Goldtree version**: 0.61

## Bug reproduction

in description

## Additional information

FAT32 , Kosmos All in One 13.2.1 ,libusbK 3.0.8

**Comment by Xianbei233** [comment]
i turn back to use 0.5 and works fine

**Comment by lookye** [comment]
Never experienced this error.
Are you able to try another cable and/or usb port?
Does it happen with every installation?

**Comment by Xianbei233** [comment]
> Never experienced this error.
> Are you able to try another cable and/or usb port?
> Does it happen with every installation?

actually before install start，just click it and get freeze，then open gold tree get error after command getdriverInfo

**Comment by lookye** [comment]
> Are you able to try another cable and/or usb port?

**Comment by Xianbei233** [comment]
> > Are you able to try another cable and/or usb port?

I tried，I'm sure it's not the problem about cable or port

**Comment by pannal** [comment]
I'm experiencing the same - the weird thing is that it worked with 0.6.1 before. Drivers are installed properly, Goldleaf just freezes when I select USB from the browse contents screen.

**Comment by XorTroll** [comment]
Might be special characters...?

**Comment by pannal** [comment]
> Might be special characters...?

Where would those be? Goldtree isn't even started at that point, so special characters on the SD card? (Browsing works properly there)

**Comment by Xianbei233** [comment]
by the way，system language：simple Chinese

**Comment by ramarivera** [comment]
Same issue here, usin latest release and it just freezes when I click on "Remote PC (via USD)" option on Explore content

**Comment by lookye** [comment]
@ramarivera 
Make sure, youre using a data cable, libusbK driver is installed for the console on your pc and goldtree was opened too (maybe start is as Admin).

**Comment by Xianbei233** [comment]
> @ramarivera
> Make sure, youre using a data cable, libusbK driver is installed for the console on your pc and goldtree was opened too (maybe start is as Admin).

Of course it's not the cable or the thing about the pc or cable, it's just a problem about the goldleaf, no matter connect to pc with useful cable or not.  Otherwise it should jump to the usb install interface to wait the connect or install, not just freezed and can not do anything but reboot

**Comment by pannal** [comment]
> > @ramarivera
> > Make sure, youre using a data cable, libusbK driver is installed for the console on your pc and goldtree was opened too (maybe start is as Admin).
> 
> Of course it's not the cable or the thing about the pc or cable, it's just a problem about the goldleaf, no matter connect to pc with useful cable or not. Otherwise it should jump to the usb install interface to wait the connection to pc , or goldtree send file , not just freezed and can not do anything but reboot

Exactly the same over here.

**Comment by lookye** [comment]
You all can feel free to join the discord (see at the end of the readme) and help to work out the problem.

**Comment by Bahamut** [comment]
I get exactly the same error, and my system is not chinese, its spanish.
I use Windows 8, FAT32 200GB Sandisk with emuMMC Partition on Atmosphere 0.9.3, Kosmos All in One 13.2.1, libusbK 3.0.7... it works on Goldtree 0.5.

**Comment by AbdulrahmanHaji** [comment]
have this issue been solved yet?

**Comment by Snowii123** [comment]
hey guys, got exactly the same issue, system in English, FAT 32 400GB Sandisk with emuMMC, libusbK 3.0.7. Tried only with 0.6.1 and this is what I get after starting goldtree (with goldleaf already frozen on "USB install". Any ideas?

![image](https://user-images.githubusercontent.com/53154845/64700478-4001d680-d4a7-11e9-98ad-200cb64e8a3f.png)

**Comment by pannal** [comment]
@Xianbei233 why did you close this issue?

**Comment by Xianbei233** [comment]
> @Xianbei233 why did you close this issue?

see Snowii123's solution
