### ISSUE TITLE
USB file transfer wont work properly

### ISSUE THREAD

**Issue by trender7** [XorTroll/Goldleaf#364]
# [ Bug report title ]

## Bug description

I installed nsp with goldtree and works fine, but tried copyn a xci file to switch microsd and wont work, after awhile it only said "successfull copy.." but only moved the file as a bunch of MB...
its a 9 gb xci and I tried copy several times it only ends copyng as 10mb,6 mb....
## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ] 8.1.0

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ] SX OS 2.8

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ] latest 0.6.1

- **Goldtree version**: [ e.g. 0.5 ] latest 0.6.1

## Bug reproduction

Copy file from USB pc to switch microsd

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
FAT32 in Switch's SD?
Then +4GB copies from PC to SD probably will cause undefined behavior (fixed it for 0.7 tho)

**Comment by trender7** [comment]
> FAT32 in Switch's SD?
> Then +4GB copies from PC to SD probably will cause undefined behavior (fixed it for 0.7 tho)

Yup fat32, guess it was that problem but thought u had some workaround magic as NSP installed and it was 10 gb XD
