### ISSUE TITLE
USB transfer hangs when interacting with Goldtree Command Line Log

### ISSUE THREAD

**Issue by rgarcia7** [XorTroll/Goldleaf#365]
# USB transfer hangs when interacting with Goldtree Command Line Log

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ] 8.0.0

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ] Atmosphere 0.93

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ] 0.6.1

- **Goldtree version**: [ e.g. 0.5 ]  0.6.1

## Bug reproduction

- Follow the installation steps found on:  https://github.com/XorTroll/Goldleaf#remote-pc-system
- Navigate to the NSP to be installled
- Install on SD Card
- Choose Install
- When the transfer starts, click on the gold tree window content, or select any part of the log
![Capture](https://user-images.githubusercontent.com/29512992/63963883-2dbd7c80-ca53-11e9-80b0-7d6adbf30d99.PNG)
- The UI stops showing new logs, Goldleaf UI hangs and the transfer stops
- To continue the transferring process hit <kbd>SPACE</kbd> or another key on the keyboard

## Additional information
Maybe there is an issue with stdin being listened on goldtree.
Could be related to #347

**Comment by XorTroll** [comment]
Wait wait, am I getting this wrong or this is just Windows console that allows text to be selected, thus doesn't update content until selection is exited...?

**Comment by XorTroll** [comment]
This is Windows, not Goldtree's issue.
