### ISSUE TITLE
Error 0x291 Installing NSP over USB

### ISSUE THREAD

**Issue by EnriqueJuarez918** [XorTroll/Goldleaf#366]
# [ ive tried to install this and another game (mutant year zero) and they both have the same error ]

## for some reason i cant install these nsp to work

Console firmware: [8.1.0 ]

CFW with version : [ e.g. Atmosphere 0.9.2]

- **Goldleaf version**: [ e.g. 0.6.1 ]

- **Goldtree version**: [ e.g. 0.6.1 ]

![error 0x291](https://user-images.githubusercontent.com/48607288/63991009-bec04200-caab-11e9-822f-363b5ee07f0b.jpg)
![myz error](https://user-images.githubusercontent.com/48607288/63991010-bec04200-caab-11e9-91db-94a287fc0451.jpg)
![nsp install error](https://user-images.githubusercontent.com/48607288/63991011-bec04200-caab-11e9-85cd-55d38d665d4e.jpg)

**Comment by lookye** [comment]
If its only for these two. The NSP files are not valid and thus cant be installed. I tested Mutant Year Zero and it installed fine.
