### ISSUE TITLE
SD root hasn't set the "Install all NSPs in the directory" function

### ISSUE THREAD

**Issue by ParodZetec** [XorTroll/Goldleaf#367]
Normally we can select any folder to show its respective options. The problem with SD root is that it can't be selected to get to those options like the mentioned on issue title.

**Comment by XorTroll** [comment]
Yeah, SD root isn't considered a normal directory like the others.

**Comment by XorTroll** [comment]
I guess that FWIW it is more easy to place anything inside a directory, and not in root.
