### ISSUE TITLE
In-app Updater does not work

### ISSUE THREAD

**Issue by uaevuon** [XorTroll/Goldleaf#369]
## Bug description

Goldleaf's Updates menu does not work on 0.6.1

## Your setup

- **Console firmware**: 8.1.0
- **CFW with version**: Atmosphere 0.9.3
- **Goldleaf version**: 0.6.1
- **Goldtree version**: None

## Bug reproduction

Open updates menu on goldleaf
[Updates: Would you liketo update Goldleaf to the latest available release?] appears
Click Yes
It does not download anything and NSP forwarder prompt appears
If I click yes, it installs nsp. 

It says goldleaf has been updated, but after restart, it is not updated at all.

## Additional information

This happens on every launching methods(through album, games, forwarder)
Goldleaf's location is /switch/goldleaf/goldleaf.nro

**Comment by lookye** [comment]
Move the Goldleaf.nro to /switch/ and try again pls.

**Comment by lookye** [comment]
@uaevuon Feedback would be nice if you fixed your problem with my advise or not.

**Comment by lookye** [comment]
@uaevuon 
> Feedback would be nice if you fixed your problem with my advise or not.

**Comment by uaevuon** [comment]
well on 0.7.0 if nro file is in /switch folder, it downloads 0.7.1 to /switch/goldleaf
I don't get it why this acts like this.
