### ISSUE TITLE
NS crash when opening tinfoil in docked mode

### ISSUE THREAD

**Issue by martimcavaco** [XorTroll/Goldleaf#37]
Nintendo Switch crashes when opening tinfoil when in docked mode with error 2347-0003.

**Comment by aveao** [comment]
This is more of a libnx bug than a tinfoil one.

**Comment by CVFireDragon** [comment]
I think it’s fixed, doesn’t happen to me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
