### ISSUE TITLE
hello bug of not detected of folder is empty of game of moero crystal hyper of e-shop japan switch

### ISSUE THREAD

**Issue by reshiram1** [XorTroll/Goldleaf#370]
# [ Bug report title ]

game of moero crystal hyper switch e-shop japan

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

## Bug description

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

[ Please describe your bug as detailed as possible here. ]

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

## Your setup

- **Console firmware**: [ e.g. 8.1.0 ]

- **CFW with version**: [ e.g. Atmosphere 0.9.3 ]

- **Goldleaf version**: [ e.g. 0.7  ]

## Bug reproduction

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

## Additional information

[ Please add some extra information or screenshots. ] 

folder is empty when the game is in the siemple folder and there are games that if detected and others not apparently do not detect Japanese games e-shop of moero crystal hyper of switch of folder of SD

Can you solve the special characters for sd to install the switch japan e-shop games?

**Comment by XorTroll** [comment]
USB or SD? If USB make sure to update to 0.7, if SD it isn't Goldleaf's problem since the SD support from the system itself doesn't allow special characters.

**Comment by lookye** [comment]
Please fill out everything in your issue template. Also make sure youre using the latest 0.7 Goldleaf release.

**Comment by reshiram1** [comment]
hello Can you solve the special characters for sd to install the switch japan e-shop games?

**Comment by lookye** [comment]
1. Fill out the form above completely (You didnt fill out all needed information). 
2. Goldleaf 0.7 fixed the special character bug.

**Comment by reshiram1** [comment]
hello I don't know what else to say about information that can help

**Comment by lookye** [comment]
Fill out everything that is in Brackets [ ]

**Comment by reshiram1** [comment]
hello ready

**Comment by lookye** [comment]
Console firmware: [ e.g. 8.1.0 ]

CFW with version: [ e.g. Atmosphere 0.93 ]

Goldleaf version: [ e.g. 0.7 ]

Goldtree version: [ e.g. 0.7 ]


???

**Comment by reshiram1** [comment]
hello corrected

**Comment by lookye** [comment]
Have you unset the Archive Bit via hekate? Goldleaf 0.7 should have no problems with special characters like japanese in the filename.

**Comment by reshiram1** [comment]
hello l use Atmosphere. I don't know why he doesn't recognize Japanese letters

**Comment by lookye** [comment]
> Have you unset the Archive Bit via hekate?

**Comment by reshiram1** [comment]
hello not works

**Comment by lookye** [comment]
Can you please write here the titleID from the game?

**Comment by reshiram1** [comment]
hello Moero Crystal Hyper [010072B00ED5C000][v0].nsp

**Comment by lookye** [comment]
The game installs fine and can be played too (being on 8.1 and using goldleaf 0.7).
So the error is somewhere on your side not goldleafs, sorry.

**Comment by lookye** [comment]
Can you pls write in spanish, if your problem is still there and what exactly your problem was?
Did you solved your problem?

**Comment by XorTroll** [comment]
#74 likely related to these
