### ISSUE TITLE
Copy xci from pc to switch,and xci does not work on Gold leaf 0.7

### ISSUE THREAD

**Issue by cisisustring** [XorTroll/Goldleaf#372]
**Bug description**
Copy xci from pc to switch,and xci does not work on Gold leaf 0.7

**Your setup**
Console firmware: 8.1.0
CFW with version: sxos2.8
Goldleaf version: 0.7
Goldtree version: 0.7

**Bug reproduction**
Copying an xci file larger than 4G from pc to switch on Gold leaf 0.7, xci fails to load. But with this xci installed, it works fine. 

**Additional information**
This happens on two different pc.

**Comment by lookye** [comment]
Goldleaf does not support XCIs.

**Comment by bartvincke** [comment]
a copy function should not care what is being copied, just copy bit for bit. it's pretty pointless if it does check first.

**Comment by CarterLi** [comment]
Same issue to me.

**Comment by XorTroll** [comment]
Gosh, what?
The copying code doesnt do any checks of what is copied...? Why...?

**Comment by XorTroll** [comment]
I mean, it does check the file size and stuff like overwriting risk, but not on the file type...?

**Comment by bartvincke** [comment]
weird because it allows the copy and starts copying and judging the duration of the copy it appears to be the full size but afterwards a 3GB XCI becomes a 17MB file on the switch ( both checked with goldleaf )
I understand xci install is not intended with goldleaf but a simple copy should work correct ?

**Comment by XorTroll** [comment]
That was an old issue, latest Goldleaf and Goldtree should definitely fix it.

**Comment by bartvincke** [comment]
> That was an old issue, latest Goldleaf and Goldtree should definitely fix it.

I'll try it out tonight and let you know

**Comment by bartvincke** [comment]
confirmed working in 0.7
thanks !
