### ISSUE TITLE
Why does 0.7 still say version 0.6.1 in the app?

### ISSUE THREAD

**Issue by sawyermade** [XorTroll/Goldleaf#373]
# [ Bug report title ]
Why does 0.7 still say version 0.6.1 in the app?
## Bug description
Why does 0.7 still say version 0.6.1 in the app?
[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]

- **Goldtree version**: [ e.g. 0.5 ]
0.7

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
You need to grab the latest 0.7 NRO. The NSP is just a forwarder that opens the goldleaf.nro. Thats why. Also you did not fill out all details.

**Comment by sawyermade** [comment]
Sorry, was doing it on my phone. That worked though, I thought I replaced the nro but I guess I did not. Works now, thank you.
