### ISSUE TITLE
Display file name containing Chinese

### ISSUE THREAD

**Issue by loyle5** [XorTroll/Goldleaf#375]
# [ Display file name containing Chinese]

## Feature description

Display file name containing Chinese

## Benefits

Files containing Chinese names now all display '☒'

## Additional information

The 0.7 version of Goldleaf can shows that the file name containing Chinese is no longer garbled, but it would be better if you can display Chinese directly.

**Comment by lookye** [comment]
Was it the same for older Goldleaf releases too?

**Comment by loyle5** [comment]
> Was it the same for older Goldleaf releases too?

no
in the older Goldleaf it display like this:![old](https://raw.githubusercontent.com/loyle5/my/master/old.jpg)
in the lasted Goldleaf display like this:![new](https://raw.githubusercontent.com/loyle5/my/master/new.jpg)

**Comment by XorTroll** [comment]
The issue is that Goldleaf's Roboto font doesn't have Chinese character support.
We are considering to switch to a font covering more characters.

**Comment by WanderMax** [comment]
https://github.com/adobe-fonts/source-han-sans
contains all characters support, but a little big.
can Goldleaf take use of system fonts which have Chinese character support?

**Comment by XorTroll** [comment]
#427 keeping a single issue for this bug
