### ISSUE TITLE
USB install lockup

### ISSUE THREAD

**Issue by CFHeadphase** [XorTroll/Goldleaf#377]
# USB installs occasionally locking up randomly

## Bug description

Occasionally, when installing an NSP it will get stuck. The console either reads:

`[gtree:Warn]` or `[gtree:Warn] Input magic mismatch (expected: 0x49434C47, got 0x0!)`.

This forces me to reboot. Doing so causes a blank tile to appear on the home screen where the installed NSP would've been. The size is reported as 0.1MB.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphère 0.9.3

- **Goldleaf version**: 0.7

- **Goldtree version**: 0.7

## Bug reproduction

- Start Goldleaf 0.7 through homebrew takeover
- Explore content
- Remote PC (via USB)
- Find the NSP
- Install to SD card
- Shortly after installation begins, the Switch program will get stuck and the Windows program will output a warning. This only happens sometimes.

**Comment by lookye** [comment]
Does it happen too, if you try another usb port? Do you have another cable to test with?

**Comment by lookye** [comment]
@CFHeadphase Feedback would be helpful.

**Comment by CFHeadphase** [comment]
Issue seems to have been with a faulty USB cable. Closed
