### ISSUE TITLE
hello the Goldleaf 0.7 want to dump a japanese amiibo and not working

### ISSUE THREAD

**Issue by reshiram1** [XorTroll/Goldleaf#378]
# [ Bug report title ]

hello the Goldleaf want to dump a japanese amiibo and not working

## Bug description

the Goldleaf 0.7 want to dump a japanese amiibo and not working and folder is empty. the dump folder

[ Please describe your bug as detailed as possible here. ]

the Goldleaf 0.7 want to dump a japanese amiibo and not working and folder is empty. the dump folder

## Your setup

- **Console firmware**: [ e.g. 8.1.0 ]

- **CFW with version**: [ e.g. Atmosphere 0.9.3 ]

- **Goldleaf version**: [ e.g. 0.7 ]

## Bug reproduction

the Goldleaf 0.7 want to dump a japanese amiibo and not working and folder is empty. the dump folder

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

the Goldleaf 0.7 want to dump a japanese amiibo and not working and folder is empty. the dump folder

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
So you want to dump a japanese amiibo and its not working?
Is it a real amiibo or a amiibo saved on a nfc tag?

**Comment by reshiram1** [comment]
So you want to dump a japanese amiibo and its not working? not get rid of him and

 want to dump a japanese amiibo and not working



Is it a real amiibo or a amiibo saved on a nfc tag? yes real amiibo japan and amiibo saved on a nfc tag not of amiibo saved on a nfc tag

**Comment by lookye** [comment]
Can you exactly write down what you want in your native language?

**Comment by reshiram1** [comment]
hello spanish do you understand

**Comment by lookye** [comment]
Xor speaks spanish, so feel free to write everything in it.

**Comment by reshiram1** [comment]
hola mi problema es el siguiente intento hacer un volcado del amiibo japones conocido por youkai ark y lo pongo en la opcion de goldleaf en la opcion de volcado y poner ponlo en el stick R para empezar el volcado o pulsa el boton B y en el stick R pongo el youkai ark y cuando termina aparece el menu de inicio de goldleaf pulso el boton home y apago la switch pongo la micro sd en pc y voy a la carpeta de goldleaf dentro y dentro de la carpeta de dump y dentro de la carpeta creo que hay 2 es oui o algo asi y dentro no hay ningun volcado y nada esta vacia y la otra carpeta que es la ultima es temp y tambien esta vacia o algo asi no se escribiro correctamente espero que me puedas ayudar muchas gracias un saludo

**Comment by XorTroll** [comment]
Los amiibos no se exportan a la carpeta dump, sino a la carpeta de emuiibo. Si no has ejecutado emuiibo nunca la habrá creado (en la raíz de la sd)

**Comment by reshiram1** [comment]
hola en la carpeta de Atmosphere 0.9.3 y dentro de la carpeta titles puesto la carpeta 0100000000000352 y dentro el archivo exefs.nsp y la carpeta flags y dentro el archivo boot2.flag y en la raiz de la sd la carpeta emuiibo y intentado hacer el volcado y apasado lo siguiente en la carpeta emuiibo y dentro la carpeta amiibo y dentro no hay nada esta vacia y en emuiibo hay otra carpeta llamada miis y dentro hay un archivo amii.bin de 1 byter y mirado en la raiz de la sd y no aparece ningun archivo de volcado todas las carpeta que puesto y como unico archivo es el homebre.bin y ya esta no hay nada mas espero que me puedas ayudar gracias un saludo

**Comment by XorTroll** [comment]
#74 likely related to these
