### ISSUE TITLE
Goldleaf Updater does not detect wired internet connections

### ISSUE THREAD

**Issue by fexofenadine** [XorTroll/Goldleaf#379]
# Goldleaf Updater does not detect wired internet connections

## Bug description

Goldleaf internal updater works fine with WiFi internet connections but does not detect a connection when using wired ethernet connections (USB to ethernet adapter required).

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.3

- **Goldleaf version**: 0.7 (earlier versions did this too)

- **Goldtree version**: N/A

## Bug reproduction

Switch to a wired connection in Switch settings. Open Goldleaf. Select Updates. Error displayed is "No internet connection was found".

## Additional information

Other apps can self update ok. The application shows 3 bars but no IP address next to the battery status indicator. If i switch to a WiFi network it works fine.

I have a uGreen USB-A to ethernet adaptor if its important

**Comment by Teryon** [comment]
Download it again, it should be fixed

**Comment by XorTroll** [comment]
This needs further investigation, tbh.

**Comment by XorTroll** [comment]
I'm testing a new way to detect if the console has connection...
If anyone with this kind of connections (and with this issue) can test something, DM me on Discord.
