### ISSUE TITLE
Key generation mismatch

### ISSUE THREAD

**Issue by racerx8967** [XorTroll/Goldleaf#380]
Trying to install NSP updates even though ive pulled the newTSEC and used the new lockpick which both work fine on 9.0.0 on atmosphere it seems gold leaf .07 still think im on to low of a firmware to install any sort of update 

the old dev menu installed it just fine and work great.. Any idea as to why this is happening? Should i move keys to a certain plaace on the SD card? or is This just a bug that will eventually be fixed?

# [ Bug report title ]

## Bug description

[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by jerry3547** [comment]
same here with 
Console firmware: [9.0.0]
CFW with version: [Atmosphere 0.9.4-master-c62c4846 ]
Goldleaf version: [0.7]
Goldtree version: [0.7]

**Comment by infinity8942** [comment]
> same here

same with jerry3547

**Comment by lookye** [comment]
FYI:
Goldleaf needs to be updated and will receive an update soon to work as intended with FW 9.
We are aware about that. So please be patient.

**Comment by pwn00b** [comment]
same here, waiting for update, can't install any nsp

**Comment by BaamAlex** [comment]
I don't know if it is okay to post that here, but i get an error when i try to install an nsp file. The error code is the following

Error: 2356-0009 (0x1364)
Module: Goldleaf (356)
Description: <invalid error entry> (9)

**Comment by RentaroArts** [comment]
I heard that the new update is coming out today, is this true?

**Comment by lookye** [comment]
> FYI:
> Goldleaf needs to be updated and will receive an update soon to work as intended with FW 9.
> We are aware about that. So please be patient.

As i wrote above. It will be soon.

**Comment by racerx8967** [comment]
Just use dev menu definitive edition 6.xx till now it installs nsps fine. Gold leaf will get updated like the dev said.

**Comment by rcarrata** [comment]
Hi @racerx8967, when you said "dev menu definitive edition 6.xx" is to use Goldleaf of 6.xx (latest version I assume). Is there any procedure for downgrade or substitute the 0.7 version installed? 

Thanks to all the team for your work & effort! You rock!

**Comment by jeffangama** [comment]
> Just use dev menu definitive edition 6.xx till now it installs nsps fine. Gold leaf will get updated like the dev said.

how to do that please

**Comment by lookye** [comment]
@jeffangama 
Just update Goldleaf to its latest version and youre fine. That´s why the issue is closed. If you have any problems, make sure you read the [FAQ](https://github.com/XorTroll/Goldleaf/blob/master/docs/FAQ.md).

**Comment by jeffangama** [comment]
i think ive done everything recommended for atmosphere, still getting

Error: 2356-0009 (0x1364)
Module: Goldleaf (356)
Description: (9)

thank you

**Comment by lookye** [comment]
@jeffangama Are you using Goldleaf 0.7.2? If not, update it. The error you describe is for an older version of Goldleaf.

Things you should check:
- Re-Download 0.7.2
- Get sigpatches (es/fs) and apply them correctly

**Comment by jeffangama** [comment]
I solved the issue with saving my emmunand keys with lockpick

**Comment by CoincidalRS** [comment]
Am I getting this error with 0.7.2 because I inadvertently updated to 9.0.1 when trying to get my exFAT sd to work?

**Comment by juchunwei** [comment]
I have the same issue, and my system is 9.0.1, gold-leaf 0.7.2, what's wrong? i'm using this patch
https://github.com/Joonie86/hekate/releases

**Comment by lookye** [comment]
FYI: Goldleaf will get an update for FW9.0.1. Why do you all just blindly update. And wonder if its break stuff.

**Comment by juchunwei** [comment]
@lookye , sorry, I just wondered maybe I did something wrong. Thanks for your job!

**Comment by mikgit013** [comment]
my setup
ver 9.0.1 
AMS 0.10
