### ISSUE TITLE
goldleaf dont work controller in fw 9

### ISSUE THREAD

**Issue by rmorteza21** [XorTroll/Goldleaf#381]
# [ goldleaf dont work controller in fw 9 ]

## Bug description

[ i have cfw kosmos when installed hbg in console i try for use goldleaf but controllr dont work ]

## Your setup

- **Console firmware**: [ 9 ]

- **CFW with version**: [ kosmos 14.1 ]

- **Goldleaf version**: [ 0.7 ]

- **Goldtree version**: [ 0.7 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ goldleaf in komos working but when i copy hbg files controller dont work. ]

**Comment by lookye** [comment]
Not having an updated hbl/hbmenu is the issue. Also all homebrews need to be updated for FW9  (it was said in a lot of places) and Goldleaf will get its update soon.

**Comment by rmorteza21** [comment]
ok thanks for all works
