### ISSUE TITLE
Goldleaf hangs when I select explore remote PC using quark

### ISSUE THREAD

**Issue by mastachaos** [XorTroll/Goldleaf#382]
## Goldleaf hangs when I select explore remote PC if I'm using quark.  -  If I use goldtree, it works just fine.

Goldleaf hangs when I select explore remote PC using quark.  If I use goldtree, it works just fine.  If I choose to view the log in quark, all I see is the 
```
Command: GetDriveCount
Command: GetDriveInfo 

```
At that point, I must use the home button to exit Goldleaf, as it becomes non-responsive. 

## Your setup

- **Console firmware**: [ 8.0.1]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ 0.71]

- **Goldtree version**: [ 0.7]

## Bug reproduction

Try to browse PC when using quark on PC and goldleaf 0.71

## Additional information

Running Windows 10 x64 - USB 3.0 port.
Java v8 u221 (1.8.0_221-b11)

**Comment by XorTroll** [comment]
Sorry, redownload it.
Silently updated it, there was a small issue ;)
