### ISSUE TITLE
Goldleaf 0.7.1 - Installed titles can not be started

### ISSUE THREAD

**Issue by muxi1** [XorTroll/Goldleaf#383]
with version 0.7.1 Installed titles can not be started. The installation itself, however, runs smoothly.

**Comment by lookye** [comment]
Please use the Issue template you ignored while opening this issue.

**Comment by XorTroll** [comment]
Try to open the issue properly with the issue template.
Also, would be helpful if you attempted to install the exact same titles from 0.7 and check if the issue happens again.

**Comment by muxi1** [comment]
Version 0.7 does not work under FW 9.0.0.

**Comment by lookye** [comment]
Update to 7.0.1

**Comment by muxi1** [comment]
I already have and was the cause of this message

**Comment by muxi1** [comment]
The issue I have reported has now been fixed with version 0.7.2!
