### ISSUE TITLE
[BUG]Invalid NCA

### ISSUE THREAD

**Issue by melxman** [XorTroll/Goldleaf#385]
# [ Bug report title ]

## Bug description

[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: 9.0

- **CFW with version**: KOSMOS14.1(Atmosphere0.9.4)

- **Goldleaf version**: 7.1

- **Quark. version**: lastest

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]
When I install Link's Awakening,it has happened.

## Additional information

[ Please add some extra information or screenshots. ] 
https://raw.githubusercontent.com/melxman/my-issues/master/ns/goldleaf/zelda-error.jpeg

**Comment by lookye** [comment]
You´re missing ES/FS patches. If you dont have them complete, you cant install any NSP.
Also: That game is a converted XCI, so you need full patches.

**Comment by melxman** [comment]
emmm，I have some espatches.Maybe it was't completed.I will find new one. thx

**Comment by melxman** [comment]
emmm，I have some espatches.Maybe it was't completed.I will find new one. thx
