### ISSUE TITLE
Ticket not installing when installing to console memory

### ISSUE THREAD

**Issue by Hanabi7729** [XorTroll/Goldleaf#387]
# Goldleaf installed games saying: " checking if this game can be played"

## Bug description

Newly installed games on 0.7.1 return the text  "checking if this game can be played". I have all the patches i need. I tried with 0.7 and it works perfectly fine.

## Your setup

- **Console firmware**:  8.1.0 (tried with a 9.0.1 one too)

- **CFW with version**: AtlasNX/Kosmos v14.1 (  Atmosphere - 0.9.4 Silent Update 1 and
  Hekate - v5.0.2)

- **Goldleaf version**: 0.7.1

- **Goldtree version**: Using Quark

## Bug reproduction

Install goes nicely, when i launch the game or app it says "checking if this game can be played". 

## Additional information
This error is not present with the same files on the 0.7.0 version. It seems to be a particular problem of this version. I have all the patches i need, that's not the problem (before you ask).  It seems like an error with titles (maybe?) because updates of previously installed titles seems to work just fine. Not a huge problem for me but just a heads up

**Comment by emanzanoaxa** [comment]
I have the same issue with 0.7.1 using kosmos 14.1 and fw 9.0.0 on emunand. Some titles work but almost all gives this error.

**Comment by Hanabi7729** [comment]
Did a little more stuff around. It seems games don't get that error when installed on the sd (only got the error). On internal memory it happens on all games/apps. Would keep experimenting a little bit

**Comment by XorTroll** [comment]
Nope, can confirm. I also get the nag installing to console memory...
What a really strange bug...

**Comment by AlpGoXd** [comment]
im having same issue when i install to sd card

**Comment by sererinn** [comment]
Same issue here with installation to both sd card or console memory.
Went back to 0.5.2 and same nsp installed perfectly and no nag message.

**Comment by davis1687** [comment]
I have the same issue installing in sd card, but if use lithium to install no have problem, so uninstall the nsp via system and i installed once again withe goldleaf and worked well. I have atmosphere 0.9.4 whit system in 9.0.0, and use goldleaf 0.7.1

**Comment by davis1687** [comment]
in fact...to instal nsp whit ticket use lithium and whitout ticket whit goldleaf and works well instaling in console memory or in sd

**Comment by AlpGoXd** [comment]
well lithium don't have pc client

**Comment by davis1687** [comment]
Exactly...i hope can fix this bug to use only goldleaf....I trust more in goldleaf to install nsp's

**Comment by lookye** [comment]
@Hanabi7729 @davis1687 @AlpGoXd 
0.7.2 got released and fixed this issue.
