### ISSUE TITLE
[Quark] Linux migth need udev rules

### ISSUE THREAD

**Issue by A6GibKm** [XorTroll/Goldleaf#388]
# Quark is stuck at USB fail screen

## Bug description

When run from linux Quark gets stuck at the USB fail screen

## Your setup

- **Console firmware**:  8.1.0

- **CFW with version**:  Kosmos 14.1

- **Goldleaf version**:  0.7.1

## Additional information

After adding the following 
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", GROUP="plugdev"
```

and 
```
SUBSYSTEMS=="usb", ATTR{idVendor}=="057e", MODE="0666"
```

To `/etc/udev/rules.d/` with `644` permissions, `sudo udevadm control --reload-rules && sudo udevadm trigger` and a proper restart it started working. Probably a lot of this is redundant and only one of the rules is enough. 

I also re downloaded Goldleaf/Quark, it might have anything to do with it starting working again?

If the rules are indeed necesary it should be noted in README.md.

**Comment by unbranched** [comment]
Console firmware: 9.0.0
CFW with version: Kosmos 15.1
Goldleaf version: 0.8
Linux distro: Arch

You just need:
`SUBSYSTEMS=="usb", ATTR{idVendor}=="057e", MODE="0666"`
and set its permissions like above, then Quark correctly detects the console, otherwise same error as OP.

@XorTroll this should be added to the Readme

**Comment by alcmoraes** [comment]
> Console firmware: 9.0.0
> CFW with version: Kosmos 15.1
> Goldleaf version: 0.8
> Linux distro: Arch
> 
> You just need:
> `SUBSYSTEMS=="usb", ATTR{idVendor}=="057e", MODE="0666"`
> and set its permissions like above, then Quark correctly detects the console, otherwise same error as OP.
> 
> @XorTroll this should be added to the Readme

Can confirm it worked as well on my end.

```
Switch Firmware: 10.0.3 w/ Atmosphere 0.12.0
Goldleaf: 0.8
OS: Linux
Distro: 5.6.15-arch1-1
```

Thanks @unbranched

**Comment by A6GibKm** [comment]
Since there are instructions on https://github.com/XorTroll/Goldleaf/blob/master/docs/QUARK_LINUX.md, I am closing this.
