### ISSUE TITLE
Can't start Quark

### ISSUE THREAD

**Issue by CFHeadphase** [XorTroll/Goldleaf#389]
# Can't start Quark

## Bug description

I can't execute Quark.jar

## Your setup

- **Console firmware**: 9.0.0

- **CFW with version**: Atmosphere 0.9.4

- **Goldleaf version**: 0.7.1

- **Goldtree version**: Quark initial release

- **Java version**: JRE 8 update 221

## Bug reproduction

Starting it from command line with 'java Quark.jar' returns 'Could not find or load main class'.

**Comment by XorTroll** [comment]
Learn to use Java from command-line.
