### ISSUE TITLE
Export menu return

### ISSUE THREAD

**Issue by fennectech** [XorTroll/Goldleaf#390]
# [ Please dont dump us into the main menu ]

## Feature description

[ Instiad of dumping us into the main menu please dump us in the menu we came from when exporting .]

## Benefits

[ When exporting many titles one by one we dont have to wiat for it to jump back into the titles we also dont have to scroll through the menu every time.
. ]

**Comment by idolpx** [comment]
This would be a nice enhancement.

**Comment by XorTroll** [comment]
Latest commit adds/fixes this ;)
