### ISSUE TITLE
[quark] Install split files

### ISSUE THREAD

**Issue by fennectech** [XorTroll/Goldleaf#391]
# [ Quark would love the ability to install split NSP folders ]

## Feature description

[ If quark could live merge NSPs (or feed the parts to goldleaf as if they were one) we could store nsps split instaid of merging them ]

## Benefits

[Simple. The ability to store large nsps wihtout having to split them to install from the card on fat32 drives. ]

**Comment by lookye** [comment]
Is this more or less the same as #230 ?

**Comment by fennectech** [comment]
why yes it is   Good catch
