### ISSUE TITLE
Quark cannot be opened

### ISSUE THREAD

**Issue by sjogro** [XorTroll/Goldleaf#393]
# Quark cannot be opened. Check console for errors.

## Bug description
I get this error: Quark cannot be opened. Check console for errors. (translated)

## Your setup
iMac 2019 / MacOS 10.14.6 / jdk-13_osx-x64_bin

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
not relevant
- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]
not relevant
- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
not relevant
- **Goldtree version**: [ e.g. 0.5 ]
not relevant

## Bug reproduction

1. Download Quark.jar
2. Drag Quark.jar from Downloads to Applications
3. Double click Quark.jar
4. Go to Preferences > Security and privacy > General > Allow Quark.jar to be launched
5. Open again
6. Wait or it
7. Error

## Additional information
I have no problem loading ns-usbloader-0.7.jar (also a jar file, from https://github.com/developersu/ns-usbloader/releases)

**Copy/paste from Mac OS console:**
standaard	12:05:50.133695 +0200	syspolicyd	temporarySigning type=3 matchFlags=0x0 path=/Applications/Quark.jar
standaard	12:05:51.893589 +0200	com.apple.preference.security.remoteservice	-[AppleSecurity_Pref _readCaspianLastDeniedApp] [727] -- _lastRejectedURL: file:///Applications/Quark.jar
standaard	12:05:54.363271 +0200	com.apple.preference.security.remoteservice	-[AppleSecurity_Pref _readCaspianLastDeniedApp] [727] -- _lastRejectedURL: file:///Applications/Quark.jar
standaard	12:05:55.658334 +0200	syspolicyd	temporarySigning type=3 matchFlags=0x0 path=/Applications/Quark.jar

**Screenshot of the error (in Dutch, sorry)**
<img width="532" alt="Screenshot 2019-09-19 at 12 15 44" src="https://user-images.githubusercontent.com/6476418/65236128-37795380-dad8-11e9-9a52-504334ab032e.png">

**Comment by Nazosan** [comment]
Do you have the Quark from GoldLeaf 0.7.1?  There was a GoldLeaf quickfix released today (0.7.2) that fixes a ticket install issue that I fought with for hours last night as well as an issue with Quark that would prevent it from running on *nix systems (which most likely includes Apple systems along the way.)

**Comment by sjogro** [comment]
Thanks I’ll have a look at the 0.7.2 tomorrow and report what happens here. (Yes I was on 0.7.1)

**Comment by lookye** [comment]
Looks like you also downloaded instantly after the first Quark release. Quark in 0.7.1 was shadow updated around 30min later bc of this bug. Anyway you should redownload Quark from 0.7.1 or 0.7.2

**Comment by sjogro** [comment]
I tried 0.72 but it didn't solve the problem. The problem was solved by uninstalling Java and then installing Java 8-Update 221.

Read more here: [#398](https://github.com/XorTroll/Goldleaf/issues/398)
