### ISSUE TITLE
Small Dutch language correction

### ISSUE THREAD

**Issue by sjogro** [XorTroll/Goldleaf#394]
# Small text correction

## Bug description

The first dialogue that appears after opening Goldleaf shows this text:

**Welkom in Goldleaf! JDruk op + voor help en informatie!**

Correction: **JDruk** should be **Druk**

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
7.0.1
- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]
Latest Kosmos
- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
0.7.1
- **Goldtree version**: [ e.g. 0.5 ]
-

## Bug reproduction

1. Open Goldleaf
2. Look at text that appears in black bar at the bottom of the screen

## Additional information

![2019091912325200-D845E50BC4CABB015293099C4863A570](https://user-images.githubusercontent.com/6476418/65236961-f5511180-dad9-11e9-8147-a37bf8833940.jpg)

**Comment by XorTroll** [comment]
Sure, thanks, will be applied for 0.7.2.
