### ISSUE TITLE
Checking if software can be played

### ISSUE THREAD

**Issue by gjimenezf** [XorTroll/Goldleaf#395]
Using latest goldleaf 0.7.1 on firmware 9.00 almost all games installed from usb or  sd card.  When I open the games they try to connect to internet and get message: Checking if software can be played. This did not happened with smash, demon x machina. I tried resintallation of the games and had same problem
The solution was using latest tinfoil to install those games.

**Comment by lookye** [comment]
1. There is already an open issue #387 
2. Will be fixed with 0.7.2 very soon (a typo lead to that bug)

**Comment by XorTroll** [comment]
^
