### ISSUE TITLE
Error 2145-0001 SD install

### ISSUE THREAD

**Issue by LosslessAngel1** [XorTroll/Goldleaf#396]
An Error Occurred attempting to install the NSP

Bug description
Tried installing an NSP via sd install which in 0.7.1 was giving the "Checking to see if title can be played bug"

Error 2145-0001 (0x291)
Module: ETicket (145)
Description: Unknown or Undocumented error (1)

My setup

- Console firmware - 9.0.0

- Atmosphere 0.94

- Goldleaf version 0.7.2

## Bug reproduction

Tried installing an NSP via SD install, NSP previously gave error when using Goldleaf 0.7.1. Install window appears giving info regarding the title to be installed, however after proceeding the error pops up

**Comment by lookye** [comment]
You seem to miss the needed sigpatches (fs and es) to be able to install. Not Goldleafs problem.

**Comment by LosslessAngel1** [comment]
oh okay thanks for letting me know, I thought i had up to date ones rip

**Comment by florensie** [comment]
Would be a good idea to add a description instead of "Unknown or Undocumented error (1)".
