### ISSUE TITLE
Copy & Paste doesn't work

### ISSUE THREAD

**Issue by pOOBAH73** [XorTroll/Goldleaf#400]
# [ Bug report title ]

## Bug description

Copying Files/Folders from/to Switch via USB connection doesn't work.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.94

- **Goldleaf version**: 0.7.1 and 0.7.2

- **Quark version**: 0.7.1 and 0.7.2

## Bug reproduction

Copying files over USB doesn't work. Tried to copy Goldleaf.nro from PC to Switch SD and Checkpoint savegames from Switch SD to PC. Used Y Key, then Copy on source, then Y and paste on destination dir.

**Comment by XorTroll** [comment]
Fixed for 0.8
