### ISSUE TITLE
 Error "quark usb failed" windows10

### ISSUE THREAD

**Issue by dornie** [XorTroll/Goldleaf#402]
# [ Error quark usb failed windows10 ]

## driver installation done right with zadig, 
java version 1.8.0_221
switch properly connected with goldleaf open
but keep getting the error "quark - usb failed" when trying to launch quark on windows 10

## Your setup

- **Console firmware**: [ 9.0.0 ]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ 0.7.2 ]

- **Quark version**: [ 0.2.0 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by GalaxyNET** [comment]
Your windows doesnt have libusbK driver for your nintendo switch, download it here.
https://github.com/pbatard/libwdi/releases/download/b721/zadig-2.4.exe

**Comment by dornie** [comment]
i forgot to tell you that i have indeed succefully installed libusbk driver trough Zadig before (that's what i ment by "switch properly connect")
so the problem isn't the switch driver

**Comment by lookye** [comment]
Please test another USB cable and/or USB port.

**Comment by Shalar** [comment]
I can confirm this behavior on my machine. I had to grab the older USB utility Goldtree to get Quark's functionality.

**Comment by lookye** [comment]
#392 As a collecting point
