### ISSUE TITLE
GolfLeaf not showing usb connection any more

### ISSUE THREAD

**Issue by Luke-101** [XorTroll/Goldleaf#404]
GolfLeaf not showing usb connection any more

## Bug description
2 days ago I installed the 7.0.1 update on the switch from the 6.2.0, to test that everything went well I installed some nsp to check. With my surprise the 5.0.0 update to Super Smash Bros Ultimate didn't work, so I tried Zelda Link's Awakening, the Untitled goose game and Mario Maker 2. The installations finished without any errors but when I tried to open the first 3 games the switch crashed and gave to me the error: "The Software Was Closed Because An Error Occurred" and then I was back to the home screen.
Only Mario Maker 2 didn't gave me a error when opened soI think that this games requred an higher firmware.
But during this process of testing, goldleaf stoped to recognised my usb connection so 2 games I had to install them by having the nsp in the sd card.
After that no matter how many times I reboot my switch or my pc, no matter which sd I used, I can't get the symbol of usb on Goldleaf

## Your setup
Console firmware: 6.2 -> 7.0.1 (now)
CFW: Atmosphere 0.9.4 (latest)
Goldleaf version: Applet Mode, NRO, 0.7.2 (latest)
Quark version: 0.2.0 (latest)

## Bug reproduction
Open goldleaf
Attach the usb cable to the switch
Goldleaf doesn't recognise the usb cable connection

## Additional information
I didn't install any themes
I tried with a clean installation of the sd
I tried also with tinfoil and fluffy without any good result

**Comment by Luke-101** [comment]
this is the driver that is installed with tegraRcmGUI in the settings tab ?

**Comment by lookye** [comment]
No, please read the readme of Goldleaf.

**Comment by Luke-101** [comment]
ok, give me a second that I read that

**Comment by Luke-101** [comment]
So I tried with every port on my laptop, but that didn't work. So I asked a friend if I could tried on his PC (tower) and it worked without even rebooting. 
So for now I think is better to close this issue and thank you, but this weekend I will try on my tower at home and if it worked there is a problem with my laptop. If not I will would be better to check what in particular is the problem in my laptop/tower.
Is that ok for you ?
