### ISSUE TITLE
Reading file took forever

### ISSUE THREAD

**Issue by Miraclaime** [XorTroll/Goldleaf#405]
# Reading file took forever 

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
newest firm 9.0

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]
AMS 0.9.4 and kosmos 14.1 using joonie patch

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
goldleaf 0.7.2

- **Goldtree version**: [ e.g. 0.5 ]
that Quark.jar bundled with GLeaf 0.7.2

umm so to sumarize
-GL frooze after choosing install nsp to sdcard
-after several rage quit now evertime i prompt to install nsp my switch went error and had to restart the console

**Comment by XorTroll** [comment]
Try with latest version...?

**Comment by lookye** [comment]
@Miraclaime Do you still have the problem? If so, please test the latest release.

**Comment by lookye** [comment]
Closed due to inactivity and not being reproducible for us.
