### ISSUE TITLE
[Feature request] Support recent Java versions with Quark

### ISSUE THREAD

**Issue by Shadowghost** [XorTroll/Goldleaf#407]
# Support recent Java versions

## Feature description

Oracle only allows downloading the most recent JRE (currently Java 12) for Windows and Quark only works with Java 8 which is no longer downloadable without registring as developer.

## Benefits

* No bugreports regarding Quark not opening
* restore cross-platform ability of Quark (the idea behind using Java is kinda not working out if you can't use the app without a specific version of JRE)

**Comment by ELY3M** [comment]
wow nice to know.  I am using Java 13 and Quark refuse to work for me.  I am not happy at all.   I do not like how oracle is doing with their downloads.

**Comment by bylaws** [comment]
https://adoptopenjdk.net/ should work
