### ISSUE TITLE
Select multiple files + updates for installation

### ISSUE THREAD

**Issue by tantoinet** [XorTroll/Goldleaf#408]
Thanks for Goldleaf, it works like a charm :)
Is it possible to provide the ability to select multiple files to bulk install them?
Also, having the ability to queue files for installation, so we can get back from the install menu and do something else.

**Comment by lookye** [comment]
You can already select a folder with Y button, choose special options and batch install all nsp files inside of it.
Also: If you open an "issue", why didnt you choose the Feature Request template?

**Comment by tantoinet** [comment]
thanks and sorry, i didn't notice the Feature Request option :+1:
