### ISSUE TITLE
An Error occurred attempting to install the NSP

### ISSUE THREAD

**Issue by KhantRyder** [XorTroll/Goldleaf#409]
# An Error occurred attempting to install the NSP 

## Bug description

 invalid error entry

## My setup

- **Console firmware**: [ 9.0.0 ]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ 0.7.2 ]

- **Goldtree version**: [ Quark v0.2.0 ]

## Additional information
![71053758_2561203713925449_3490682747964358656_n](https://user-images.githubusercontent.com/55906570/65812515-02fb4b00-e1ee-11e9-826a-40706336c020.jpg)

 I have updated sigpatches files for 9.0.0 too. I have already try re-downloading goldleaf 0.7.2 and Quark too but the Error still exist.

**Comment by Synless** [comment]
- Console firmware: [ 8.1.0 ]
- CFW with version: [ Atmosphere 0.9.3 ]
- Goldleaf version: [ 0.7.2 ]
- Goldtree version: [ Quark v0.2.0 ]

Same problem here, followed by Atmosphere crash screen.

**Comment by lookye** [comment]
Then get your title again from the net again. It seems the NSP file is invalid/corrupted.

**Comment by KhantRyder** [comment]
Previously working NSP file were not able to install after the update. I was able to installed NSP file on 8.1.0 (Atmosphere 0.9.4) with goldleaf 0.7 and Goldtree. It's showing Error on all the NSP files that I have, which were able to install with no errors. 

I updated to CFW 9.0.0 this morning and Goldleaf to 0.7.2 and since then I can't seems to install any of the NSP files.

**Comment by KhantRyder** [comment]
Update - If I put the NSP file to the SD card and install the file from SD card, it's can be install with no error. It seems that I can't directly install from my PC using Quark. My SD card is Fat32 format so I can't put the NSP files bigger than 4GB.

**Comment by lookye** [comment]
You can also try Goldtree from the 0.7 release together with Goldleaf 0.7.2

**Comment by KhantRyder** [comment]
I tried as you mention and Yes Sir, it's working now. Goldleaf 0.7.2 and Goldtree from 0.7

Thank you ! 

Console firmware: [ 9.0.0 ]

CFW with version: [ Atmosphere 0.9.4 ]

Goldleaf version: [ 0.7.2 ]

Goldtree version: [ Goldtree 0.7 ]

Working now !
