### ISSUE TITLE
Can´t install NSPs on ReiNX

### ISSUE THREAD

**Issue by MrStimmung** [XorTroll/Goldleaf#416]
# Can´t install NSPs on ReiNX

## Bug description

When trying to install a NSP file it says, that the FW is too low or sigpatches are missing. Also the Firmware says, that its Keygen is Generation is 0.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: ReiNX 2.4

- **Goldleaf version**: 0.7.3

- **Goldtree version**: 0.7 and latest Quark

## Bug reproduction

Try to install a NSP file while being ReiNX.

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
This is actually a confirmed and known bug.
Apparently ReiNX (and SX OS) "fail" when reading BOOT0 in order to check the console's key generation.

The cause of this is yet unknown...

**Comment by MUGIWARA93** [comment]
I have the same problem, just back to 0.7.2 meanwile fix that bug.

**Comment by XorTroll** [comment]
This seems to be fixed for 0.8...?

**Comment by kiwanowski** [comment]
Still doesnt work on ReiNX

**Comment by Enspiron** [comment]
Reinx is old and outdated. Switch to atmosphere with sigpatches for a better experience.

**Comment by lookye** [comment]
Closed due to inactivity and not being reproducible for us.
