### ISSUE TITLE
Error code 2168-0002 and Error code 2356-0009

### ISSUE THREAD

**Issue by JustNachaat** [XorTroll/Goldleaf#420]
# [ ERROR code 2168-0002 and 2356-0009]

## Bug description

[ when i try to install a game using Quark nd Goldleaf , i get this error code then the whole thing crashes 
 after i select the file and i hit install i get the 2356-0009 error code , after i hit ok i get Atmosphere "blue screen" with error code 2168-0002  ]

## Your setup

- **Console firmware**: [ 9.0.1 ]

- **CFW with version**: [ Atmosphere 0.94 ]

- **Goldleaf version**: [0.73 ]

- **Goldtree version**: [  ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by LeroyJennnkinnnns** [comment]
I'm experiencing the same problem with the same setup. It's not the cable as I've tried many different cables.

**Comment by Tempju** [comment]
I'm having the same issues with some .nsp but others are working fine.

Console firmware: [ 9.0.1 ]
CFW with version: [ Atmosphere 0.94 ]
Goldleaf version: [0.73 ]

**Comment by lookye** [comment]
Either youre missing patches or the nsps that fail are corrupted.

**Comment by Tempju** [comment]
There must be something wrong with Quark because it worked with NS-USBloader v00.8 using the same NSP, and same config (sigpatch),

**Comment by LeroyJennnkinnnns** [comment]
I can confirm it is Quark as @Tempju has stated, NSPs that crash in Quark work in NS-USBloader.

**Comment by LeroyJennnkinnnns** [comment]
@XorTroll is there anything I can do to help replicate this issue?

**Comment by Scavy74** [comment]
Hi, got the same problem with some .nsp files. As Tempju i used NS-USBloader and it works.

**Comment by kaitokid00** [comment]
Does anyone solve the problem

**Comment by kaitokid00** [comment]
> 
> # [ ERROR code 2168-0002 and 2356-0009]
> ## Bug description
> 
> [ when i try to install a game using Quark nd Goldleaf , i get this error code then the whole thing crashes
> after i select the file and i hit install i get the 2356-0009 error code , after i hit ok i get Atmosphere "blue screen" with error code 2168-0002 ]
> ## Your setup
> 
>     * **Console firmware**: [ 9.0.1 ]
> 
>     * **CFW with version**: [ Atmosphere 0.94 ]
> 
>     * **Goldleaf version**: [0.73 ]
> 
>     * **Goldtree version**: [  ]
> 
> 
> ## Bug reproduction
> 
> [ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]
> ## Additional information
> 
> [ Please add some extra information or screenshots. ]

Does anyone solve the problem

**Comment by sbblah** [comment]
any update on this?

**Comment by LeroyJennnkinnnns** [comment]
> > # [ ERROR code 2168-0002 and 2356-0009]
> > ## Bug description
> > [ when i try to install a game using Quark nd Goldleaf , i get this error code then the whole thing crashes
> > after i select the file and i hit install i get the 2356-0009 error code , after i hit ok i get Atmosphere "blue screen" with error code 2168-0002 ]
> > ## Your setup
> > ```
> > * **Console firmware**: [ 9.0.1 ]
> > 
> > * **CFW with version**: [ Atmosphere 0.94 ]
> > 
> > * **Goldleaf version**: [0.73 ]
> > 
> > * **Goldtree version**: [  ]
> > ```
> > 
> > 
> > ## Bug reproduction
> > [ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]
> > ## Additional information
> > [ Please add some extra information or screenshots. ]
> 
> Does anyone solve the problem

Yes, use NS-USBloader with Goldleaf for those NSPs that don't work. The problem is with Quark and there is no resolution right now. If you can isolate, reproduce the issue then this might be helpful, but help on this issue is non-responsive at the moment.

**Comment by LeroyJennnkinnnns** [comment]
The issue is, this problem makes bulk installing NSPs useless unless you know which ones won't work with Quark in advance, which obviously you don't if you haven't already tried them all.

**Comment by eddycor** [comment]
right-click on your nsp file and uncheck read-only and try again

**Comment by jeffangama** [comment]
Use tinfoil :)

**Comment by lookye** [comment]
Quark was updated. Please test the latest release and report back.

**Comment by lookye** [comment]
Closed due to inactivity and not being reproducible for us.

**Comment by grifas** [comment]
On your PC, right click on your nsp > Properties > uncheck read only.

Enjoy !
