### ISSUE TITLE
NSZ install

### ISSUE THREAD

**Issue by dolanqqq** [XorTroll/Goldleaf#424]
Option to include NSZ install in Goldleaf

## Feature description

With NSZ turning up and really making a difference with file sizes, I would love it if Goldleaf would be able to install them as well like on Tinfoil as some users prefer Goldleaf over Tinfoil.

## Benefits

Smaller filesizes, included in Tinfoil/SX Installer

## Additional information

**Comment by Conan179** [comment]
Forget it

**Comment by lookye** [comment]
Same as #417
