### ISSUE TITLE
Goldleaf freezes when opening Remote PC (via USB)

### ISSUE THREAD

**Issue by Josh1721** [XorTroll/Goldleaf#429]
Goldleaf freezes when opening Remote PC (via USB) when connected to PC, but acts normal when not connected and the only thing I can do is go to the home page, nothing else works. Some help would be appreciated.

**Comment by XorTroll** [comment]
Do you have the PC tool (Quark or others) opened?

**Comment by lookye** [comment]
1. Issue template wasnt used.
2. There were already issues like #382 #347 . Please read them for the solution.
3. Like Xor already wrote. You need to have Quark open.

**Comment by Josh1721** [comment]
OK I downloaded Quark and it worked, thank you so much.

**Comment by batmanord** [comment]
OK so While transfering a Large NSP I experienced the SAME ISSUE, it will write
[gtree:Log] Received command: ReadFile
[gtree:Log] Received command: ReadFile
[gtree:Log] Received command: ReadFile
And Hang at some point.
Press SPACEBAR in the CMD terminal to refresh and continue installing.
But installing a 32GB file takes 45minutes and pressing spacebar for 45minutes sucks......

I FOUND THAT IF YOU OPEN GOLDTREE with POWERSHELL It works flawlessly.

POWERSHELL.EXE runs Goldtree.exe Better.
Im not much of a windows user so I cant explain why this is happening,
And thats why im not much of a windows user.

GoodLuck.

(Using Goldtree 0.7.0.0 and Goldleaf 0.7.2)
