### ISSUE TITLE
Build issues on windows

### ISSUE THREAD

**Issue by mrdude2478** [XorTroll/Goldleaf#433]
For those building on windows - when trying to build Goldleaf Forwarder.

Make file has this:
@$(CURDIR)/BuildTools/hacbrewpack.-k $(CURDIR)/BuildTools/keys.dat --exefsdir $(BUILD)/exefs --noromfs 

You will get an issue about not being able to execute hackbrewpack, change line to this:
@$(CURDIR)/BuildTools/hacbrewpack.exe -k $(CURDIR)/BuildTools/keys.dat --exefsdir $(BUILD)/exefs --noromfs 

Now the build will be able to execute hacbrewpack.exe.

Also you need to put a keys.dat file in to that same folder where hacbrewpack.exe is created. Then you will be able to compile properly on windows.

**Comment by XorTroll** [comment]
Forwarder isn't a thing now, should build fine
