### ISSUE TITLE
Quark isn't responsive to my Remote PC via USB request

### ISSUE THREAD

**Issue by Jezziel** [XorTroll/Goldleaf#434]
# [ Quark isn't responding to any of my actions ]

## I've launched Goldleaf on my switch, plugged the USB to my PC.Quark isn't responding to my request when I send a remote request from my switch, nothing happens when I execute it. Any leads?

- **Console firmware**: 9.0.0

- **CFW with version**: [Atmosphere 0..9.3 ]

- **Goldleaf version**: [ 0.7.3 ]

**Comment by roeesh1010** [comment]
i have the same issue the switch shows a usb connection but quark isnt detecting it, please help me solve the problem.

**Comment by littlebalup** [comment]
Maybe same issue than this : https://github.com/XorTroll/Goldleaf/issues/446
