### ISSUE TITLE
Goldleaf 0.7.3 not opening - black screeen

### ISSUE THREAD

**Issue by Pepsss** [XorTroll/Goldleaf#438]
# [ Goldleaf 0.7.3 not opening - black screeen ]

## Bug description

[ Whenever I try to open Goldleaf - either from applet mode hbmenu or normal hbmenu - it just freezes and gives me a black screen. I can still press "home" and close the HBmenu. Everything else works fine, I can launch other homebrews without issues. I used to launch goldleaf without any problem at all and I didn't change anything in the meantime. ]

## Your setup

- **Console firmware**: [ 8.1.0 ]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ 0.7.3 ]

- **Goldtree version**: [ 0.5 ]

## Bug reproduction

[ Just opening GoldLeaf from hbmenu ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
I would redownload it, since this makes little sense.

**Comment by Pepsss** [comment]
> I would redownload it, since this makes little sense.

Thank you for your quick reply! Should I just redownload the nro file?

**Comment by XorTroll** [comment]
Yeah, I would just try that since I can't think of anything else causing issues.

**Comment by Pepsss** [comment]
> Yeah, I would just try that since I can't think of anything else causing issues.

I re-downloaded it but still black screen :/

**Comment by XorTroll** [comment]
Try removing Goldleaf folder inside /switch

**Comment by Pepsss** [comment]
Still no luck...

**Comment by lookye** [comment]
Delete older /goldleaf folders on your sd (root and/or /switch folder).

**Comment by Pepsss** [comment]
> Delete older /goldleaf folders on your sd (root and/or /switch folder).

No luck :/

**Comment by lookye** [comment]
Please set up your cfw + homebrews freshfly. That blackscreen problem doesnt make much sense.
Also, if you´re using exfat, you should change to fat32.

**Comment by Pepsss** [comment]
That solved it! I reinstalled kosmos package and i finally can open goldleaf. Of course, another issue arose: i can launch HBMenu only from album app, it doesnt launch from R+games... can you guys give any tips?

**Comment by lookye** [comment]
If you make a clean install, everything should work as intended. 
Also this is a problem, that doesnt belongs here.

**Comment by ELY3M** [comment]
I am having same issue on my banned switch.  I had goldleaf working fine few days ago.  now sudden I am getting black screen.   I found it very odd.       I will try the advices above here.

**Comment by ELY3M** [comment]
fat32 on sd card and latest atmosphere 0.9.4  and I am running 8.1.0  fw

**Comment by ELY3M** [comment]
I finally figured out why I am getting black screen.  I had sysDVR installed on my switch.  I had to delete that sysmodule  :(   I guess I am back to using my elegate capture card.

**Comment by ELY3M** [comment]
00FF0000A53BB665 in /atmosphere/titles is what I deleted.  
if anyone else have black screen issue, check your /atmosphere/titles/  for this folder 00FF0000A53BB665  if it is there, delete it.     00FF0000A53BB665 is titleid of sysDVR

**Comment by Pepsss** [comment]
@ELY3M I had sysDVR as well! I guess the sysmodule is somehow conflicting with goldleaf

**Comment by ELY3M** [comment]
I agree!  thank you for telling us that you have sysDVR.

**Comment by ELY3M** [comment]
read this issue at sysDVR github here  https://github.com/exelix11/SysDVR/issues/5

**Comment by DitDitGitHub** [comment]
Thanks you so much for pointing this out!
