### ISSUE TITLE
Goldleaf seems to crash with a frozen UI when selecting the Remote PC (via USB) option

### ISSUE THREAD

**Issue by v0armd9** [XorTroll/Goldleaf#442]
# Goldleaf seems to crash with a frozen UI when selecting the Remote PC (via USB) option

## Bug description

Goldleaf seems to crash with a frozen UI when selecting the Remote PC (via USB) option.
The driver has been updated using zadig to libusbK
When opening goldleaf, the pc makes a sound as if a device was disconnected. 
I can see the usb icon at the top of goldlead indicating that it detects the connection, but when I select Remote PC (via USB) option, the UI Freezes. I can still press home to get out of goldleaf, but nothing else works. 
if I unplug the switch while it's hung up like this, it will move to a new screen that says select file from PC, but at this point it is disconnected and defeats the point. Plugging back in doesn't seem to allow goldtree to detect the connection

## Your setup

- **Console firmware**:  8.1.0

- **CFW with version**:  Atmosphere 0.9.4

- **Goldleaf version**:  0.7.3

- **Goldtree version**: 0.1

## Bug reproduction

quite literally just selecting the Remote PC (via USB) option when connected to a pc produces this bug for me

**Comment by lookye** [comment]
There were several issues like e.g.: #429 #415 #404 #382 . Please look into these for answers, as your not the 1st one.

**Comment by v0armd9** [comment]
Sorry about that, i looked, but I didn’t think to check closed issues. That’s my bad
