### ISSUE TITLE
Copying folders via USB doesn't work

### ISSUE THREAD

**Issue by mrdouchey** [XorTroll/Goldleaf#448]
# [ Copying folders via USB doesn't work ]

## Bug description

[ You can't copy folders from PC to SD card or the opposite via USB. While it states the copying is successful, the folder is nowhere to be found. I find this extremely strange because copying nro/txt/nsp or anything really works just fine, unless it's a folder. This has been an issue since the Remote USB function was first introduced.]

## Your setup

- **Console firmware**: [ ofw 9.0.1 ]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ Goldleaf 0.7.3 ]

- **Goldtree version**: [ latest Quark]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
I can reproduce and confirm this bug too.

**Comment by rkmax** [comment]
Yep. very annoying

**Comment by XorTroll** [comment]
Fixed for 0.8, which will be released soon ;)
