### ISSUE TITLE
7.3 hangs on NSP dump on file over 4GB on FAT32

### ISSUE THREAD

**Issue by dheutcc** [XorTroll/Goldleaf#450]
# 7.3 hangs on NSP dump on file over 4GB on FAT32

## 7.3 hangs on NSP dump on file over 4GB on FAT32

7.3 hangs on NSP dump on file over 4GB on FAT32. Using 7.0 for files over 4GB as an alternative. files under 4gb 7.3 handles faster since rewrite, thank you.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Kosmos 14.2(Atmosphere 0.9.4)

- **Goldleaf version**: 7.3

- **Goldtree version**: N/A

## Bug reproduction

Try to export NSP over 4gb on fat32 SD

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
Tested it with this setup:

Goldleaf 0.7.3
Atmosphere 0.9.4
Firmware 9.0.1
SD is FAT32

Dumped a title bigger than 4GB and it dumps through it as intended.
