### ISSUE TITLE
Update nag not removed

### ISSUE THREAD

**Issue by joopjuh** [XorTroll/Goldleaf#451]
# [ Update nag not removed. ]

## Bug description

Content manager: You have also the option to remove unused tickets or tickets belonging to contents, plus the options to reset launch version (in order to remove the update nag) or to export base, updates or DLCs to installable NSPs.

I'm able to remove the system update using the Console and GoldLeaf settings area but the system update nag is not removed.
Is the above description only meant for the updates for games?

## Your setup
- **Console firmware**: [ 9.0 ]
- **CFW with version**: [Atmosphere 0.9.4, Kosmos 14.2 ]
- **Goldleaf version**: [0.73 ]

## Bug reproduction

Open Goldleaf,
Remove system update using Console and Goldleaf Settings.
Close Goldleaf.
Reboot the console while having flight mode enabled or with Wi-Fi and DNS settings.
Start game and System update nag appears.
Double checked Goldleaf for system update but they are no longer present.

**Comment by XorTroll** [comment]
This is indeed a bug, will attempt to fix it for 0.8 (I think I got it working)

**Comment by XorTroll** [comment]
Supposedly fixed on 0.8 (testing would be helpful, if so, open another issue)

**Comment by joopjuh** [comment]
Just updated and verified the bug. 
The issue has now been resolved. 
Thanks @XorTroll Hope you had a nice holiday. May 2020 be a good year.
