### ISSUE TITLE
Error 2145-0001 

### ISSUE THREAD

**Issue by danwhit123** [XorTroll/Goldleaf#453]
Goldleaf Error 2145-001

## Bug description

When installing through Quark with Goldleaf i get the error 2145-001 which then fails to install the the title. I have the latest sigpatches installed. 

## Your setup

- **Console firmware**: 9.0.1

- **CFW with version**: Atmosphere 9.0.4

- **Goldleaf version**: 0.73

- **Quark version**: 0.2.0

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
Please see #396

**Comment by contercx** [comment]
hello did u ever figure this out
