### ISSUE TITLE
Couldn't install anything

### ISSUE THREAD

**Issue by flashbeem** [XorTroll/Goldleaf#455]
Hi all,

## Bug description

I'm trying to install a NSP file which I created from a XCI file with my prod.keys file (used 4NXCI as converter).
When I select the NSP file I get the following error:
Error: 2002-4518 (0x234C02)
Modul: FS (2)
Description: Invalid NCA (Missing Sigpatches or too low firmware) (4518)

## Your setup

- **Console firmware**:  9.0.1

- **CFW with version**: Atmosphere 0.9.4

- **Goldleaf version**: 0.7.3

- **Goldtree version**: I don't know what this is.

## Bug reproduction

I tried it with another NSP file and get the same error message.

## Additional information

Is this a known bug? Should I use some other installation app?

**Comment by lookye** [comment]
Youre either missing sigpatches or the NSP is faulty. Thats not a Goldleaf problem.

**Comment by flashbeem** [comment]
Hi there!
Thanks for your reply. The NSP file was already successfully installed on another switch (of course the XCI file was made with the keys of the other switch).
So I guess the NSP file is fine?

But do you know how to solve the "sigpatches" issue? I don't know what this is or how to get rid of it :)

thanks!!!

**Comment by flashbeem** [comment]
Ok, solved it :)

I installed these patches:
https://github.com/Joonie86/hekate/releases

Now it works ;) sorry and thanks !!

**Comment by jacobarvizu583** [comment]
Hey the joonie link is broken anyone have a fixed link

**Comment by MARIOWARE** [comment]
> Hey the joonie link is broken anyone have a fixed link

Yeah same. Did you find the link ?

**Comment by lookye** [comment]
This is not the place to discuss where to get patches. They can be found all over the web.
