### ISSUE TITLE
Quark wont install any nsps and keeps crashing

### ISSUE THREAD

**Issue by CommicKick69ing** [XorTroll/Goldleaf#456]
# [ Quark wont install any nsps and keeps crashing ]

## Quark wont install any nsps and keeps crashing. Im trying to install my SSBU nsp

[ Quark wont install any nsps and gives me an error message and then crashes. Im trying to install my SSBU nsp. ]

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]

- **CFW with version**: [ Atmosphere 0.85 ]

- **Goldleaf version**: [ 0.73 ]

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Quark wont install any nsps and keeps crashing. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by rpalmon** [comment]
#1) Update your atmosphere then see what happens 
#2) use firmware 8.1.0

Out of date cfw would most likely have issues.

**Comment by CommicKick69ing** [comment]
Im am on the latest cfw

**Comment by lookye** [comment]
Pls open a new issue and fill out **all** [ Brackets ] with your console / homebrew information and give more details like:
- when does it crash
- what error code occurs (or make a screenshot)

**Comment by CommicKick69ing** [comment]
Unhelpful prick

**Comment by lookye** [comment]
Making issues without all needed information are unhelpful. Please think before replying/submitting a new issue.
