### ISSUE TITLE
GolfLeaf hangs on install at the end. NSP becomes corrupt afterward.

### ISSUE THREAD

**Issue by TidusWulf** [XorTroll/Goldleaf#457]
GolfLeaf hangs on install at the end. NSP becomes corrupt afterward.

## Bug description

NSP spends a few minutes writing content, then gets stuck at 0 seconds remaining. Can't exit the install screen with any button combo. But pulling out the USB cable makes it step forward a few times, where it hangs again. Plugging the USB cable back in and pressing OK in Quark (the disconnect popup appears, of course) causes the install to finalize, I get a toast saying the NSP was successfully installed, but upon opening the title on the home screen, I get an error that doesn't allow me to load the game (though I do get the black screen with the switch logo in the bottom right.

## Your setup

- **Console firmware**: 7.0.1

- **CFW with version**: Atmosphere - 0.9.4,   Hekate - v5.0.2

- **Goldleaf version**: 0.7.3

- **Quark version**: 0.2.0

## Bug reproduction

Install an NSP with latest golfleaf/quark.

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
Same as #423
