### ISSUE TITLE
With java 9+ the window is collapsed making the app unusable

### ISSUE THREAD

**Issue by rkmax** [XorTroll/Goldleaf#458]
# With java 9+ the window is collapsed making the app unusable

when the app run with java 9, 11 or 13 the app is not usable

## Bug description

recently I'm playing around with the code and learning, found that the problem rises with the stage is set to not resizable

    primaryStage.setResizable(false); // this line trigger the problem

### How the app looks with with java 8

![Screenshot_20191204_084149](https://user-images.githubusercontent.com/395707/70147412-2620fb80-1672-11ea-94a2-7b1cd43a81be.png)

### How the app looks with java 9+
![Screenshot_20191204_084214](https://user-images.githubusercontent.com/395707/70147462-43ee6080-1672-11ea-833b-8cba17ad19be.png)

### Linux java 9
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

### Linux java 13
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

## Bug reproduction

Just run the project with java 9+

**Comment by XorTroll** [comment]
I.. ran it Java 9 and those issues aren't present...?

**Comment by rkmax** [comment]
then probably is just 11 and further, probably I got a bit confused with java versiones cos I tried many xD

**Comment by rkmax** [comment]
Nop i've tested with java 9 on archlinux  and happens the same problem

**Comment by XorTroll** [comment]
Test latest Quark if you can.

**Comment by rkmax** [comment]
Tested with 
```

java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

The result

![Screenshot_20191230_171719](https://user-images.githubusercontent.com/395707/71602879-45ebf800-2b28-11ea-99ee-d395ae3fb282.png)

**Comment by XorTroll** [comment]
It's weird Quark is shown like that, I still have no clue why this would happen

**Comment by daruuuna** [comment]
Can confirm this is happening with me as well:

![2019-12-31-190035_1142x649_scrot](https://user-images.githubusercontent.com/58035589/71635942-e103d100-2bff-11ea-8f16-41428ccf6fc8.png)


Interestingly, Quark shows up in my taskbar:

![2019-12-31-190129_351x57_scrot](https://user-images.githubusercontent.com/58035589/71635952-f7aa2800-2bff-11ea-8040-d3e4cbe8cdb3.png)


I'm running Arch with OpenJDK JRE 13.

**Comment by brando56894** [comment]
Same result with Arch and openjdk 10 and 13

**Comment by magicparty** [comment]
as i know openjdk is not supported.

**Comment by OreoCupcakes** [comment]
Java 11 here. Specifically the Zulu OpenJDK FX version on Windows 10. Quark won't even open at all. It runs into a JNI and Java Exception error and crashes immediately.

**Comment by rkmax** [comment]
I think is a problem with javajx based on what I found related. a way I was able to solve to execute the application in java13 is

remove the `stage.setResizable(false);` and in order to preserve the same behavior, add the following
```java
stage.setMinHeight(d.height);
stage.setMaxHeight(d.height);
stage.setMaxWidth(d.width);
stage.setMinWidth(d.width);
```

in that way I get the app to work
![Screenshot_20200229_144408](https://user-images.githubusercontent.com/395707/75614005-e0a18c80-5b01-11ea-8caa-b49e760770ec.png)
