### ISSUE TITLE
[FR] Activity Indicator or Message Counter on Quark

### ISSUE THREAD

**Issue by adamnock** [XorTroll/Goldleaf#459]
# Activity Indicator or Message Counter on Quark

## Feature description
UX could be improved by adding an activity visualisation (flashing icon on message etc) or a simple total message count which would increment even if the visible log messages werent clearly changing.

## Benefits
Currently the Log viewer in Quark quickly fills with Command: ReadFile when doing a transfer, however its not possible to clearly identify if the logs are incrementing or not as there is no visual indication when the on screen log is all the same message.

**Comment by XorTroll** [comment]
Really ood point, I think I'm just going to show the current time (HH:MM:SS) for every command, so that users can notice if it stops (those ReadFile commands are really annoying, indeed)

**Comment by XorTroll** [comment]
Added it
