### ISSUE TITLE
Error: 2002-4517 (0x234A02)

### ISSUE THREAD

**Issue by vaicius** [XorTroll/Goldleaf#460]
# Error: 2002-4517 (0x234A02)

## Bug description

I get this error when I try to install split NSP with different versions of goldleaf 0.5 or 0.7.3. I've tried different split NSP files. None seem to work. I've successfully installed not split NSP files. 

## Your setup

- **Console firmware**: 9.0.1

- **CFW with version**: AMS 0.9.4

- **Goldleaf version**: 0.7.3 or 0.5

- **Goldtree version**: none

## Bug reproduction

Download Mario Odyssey NSP file, split with macOs "SplitNSP-Swift-GUI" to fit on FAT32 SD card, transfer to USB drive storage, boot VM windows 10, add files from USB drive to SD card.

## Additional information

<img width="1062" alt="Screen Shot 2019-12-07 at 21 17 42" src="https://user-images.githubusercontent.com/24195521/70379576-12f28200-1937-11ea-8693-e2062120baf2.png">

**Comment by XorTroll** [comment]
> might mean missing sigpatches

Goldleaf itself is telling you what the issue might be

**Comment by RenaKunisaki** [comment]
Having this issue too, pretty sure I have all sigpatches (if not, I have no idea where to get the ones I'm missing) and on 9.1.0.

**Comment by Enspiron** [comment]
> Having this issue too, pretty sure I have all sigpatches (if not, I have no idea where to get the ones I'm missing) and on 9.1.0.
You are using 9.1. Goldleaf has to be updated and will be soon.

**Comment by lookye** [comment]
> You are using 9.1. Goldleaf has to be updated and will be soon.

@vaicius @RenaKunisaki please test the latest release and report back.

**Comment by RenaKunisaki** [comment]
Still getting this error on 8.0. I also tried Awoo Installer and it also says Invalid NCA. (I converted it from my own cartridge, which works fine.)

**Comment by XorTroll** [comment]
> > might mean missing sigpatches
> 
> Goldleaf itself is telling you what the issue might be

As I stated several weeks ago :P

**Comment by RenaKunisaki** [comment]
How do I verify which ones I'm missing?

**Comment by raynelogens** [comment]
I’m having the same issue as well. Current firmware and I have the sigpatches (tried from different places) and still cannot install NSPs. Could really use some help. 

Goldleaf 0.7.3 with Hekate v5.1.1 with Atmosphere 0.10.1 Switch firmware 9.1.0

I can’t use Goldleaf 0.8.0 because Quark doesn’t won’t to open.

**Comment by Gullerboi** [comment]
Having the same issue, trying to install nsp: pokemon sword. FW 9.10 using kosmos

**Comment by lookye** [comment]
Kosmos does not support piracy and dont have sigpatches included. If you dont have the latest es/fs patches (sigpatches) for 9.1.0 you cant install nsp files.

**Comment by svdadjust** [comment]
hi. I have same problem too. I cant install pokemon sword.nsp.  
I patched latest ES_patches on kosmos v15 via hekate using tegraRCM GUI.
Can I have some help?

**Comment by lookye** [comment]
I dont think you did exactly, what you described. You need to put files manually on your SD and restart the console.

**Comment by Gullerboi** [comment]
If you downgrade you will be able to do it on ReiNX
