### ISSUE TITLE
Error 2145-0001

### ISSUE THREAD

**Issue by vivito51** [XorTroll/Goldleaf#462]
# [ Error 2145-0001]

## unkown error or not documented

[ I updated to 9.1 switch version, I loaded 0.10.1 atmosphere version. When I used goldleaf to installa a game y get this error and the game don't install. Previous versions worked perfectly. Can someone help me?]

## Your setup

- **Console firmware**: [ 9.1 ]

- **CFW with version**: [Atmosphere 0.10.1]

- **Goldleaf version**: [ 0.7.3 ]

- **Goldtree version**: [ dont know]

## Bug reproduction

[ Try to install a game in those versions ]

## Additional information

[ 
![IMG_20191221_213914](https://user-images.githubusercontent.com/59124966/71313703-b3b76600-243c-11ea-9d9c-520d31abe072.jpg)
 ]

**Comment by Enspiron** [comment]
Goldleaf has not been updated for latest atmosphere. New version will come soon to fix this.

**Comment by vivito51** [comment]
Thanks!

**Comment by StanMOI** [comment]
Please Santa, for new year !

**Comment by lookye** [comment]
@vivito51 Please check the latest release and report back.

**Comment by Magaro-l** [comment]
Hey, I have the same issue with the new version, I'm using the console firmware 9.1, and atmosphere 0.10.1 with the latest goldleaf version. I tried to install a title again but the same error happens again:

![20191230_123407](https://user-images.githubusercontent.com/59368371/71588744-62c10500-2b01-11ea-8ecc-7ea3a10bbc25.jpg)

**Comment by lookye** [comment]
Do you have sigpatches up2date on your sd card?

**Comment by Magaro-l** [comment]
Yeah, I have the updated sigpatches on my sd card.

**Comment by StanMOI** [comment]
> Hey, I have the same issue with the new version, I'm using the console firmware 9.1, and atmosphere 0.10.1 with the latest goldleaf version. I tried to install a title again but the same error happens again:
> 
> ![20191230_123407](https://user-images.githubusercontent.com/59368371/71588744-62c10500-2b01-11ea-8ecc-7ea3a10bbc25.jpg)

Same for me :(

**Comment by XorTroll** [comment]
This error isn't related to Goldleaf at all. It's an ETicket error = ES patches issue.

**Comment by StanMOI** [comment]
> Goldleaf has not been updated for latest atmosphere. New version will come soon to fix this.

still the same problem with new version

**Comment by lookye** [comment]
As mentioned above, its a user-error. You´re missing patches.

**Comment by EddyCR** [comment]
@lookye I'm getting the same error, i know you guys said that it's a user's error but how do i fix it?, i'm having the same problem using the recent release 0.8, i'm on 9.1.0|ASM 0.10.
Thanks for the help, but again i dont know how to fix it if it's a user error

**Comment by lookye** [comment]
E.g. there´s a thread on gbatemp about the "sweet patches". Apply them correctly, boot via fusee-primary into ams and try again.

**Comment by EddyCR** [comment]
@lookye understood, thank you for answering.
