### ISSUE TITLE
Quark not working on 0.8

### ISSUE THREAD

**Issue by Pikotaro** [XorTroll/Goldleaf#465]
# [ Bug report title ]

## Bug description

when I try to start the jar file it wont open

## Your setup

- **Console firmware**: 9.1

- **CFW with version**: latest atmosphere

- **Goldleaf version**: latest

- **Quark version**: latest
Java: version 8 221

## Bug reproduction

just try to start the file lul

## Additional information

idk

**Comment by Pikotaro** [comment]
It says: Error: A JNI error has occurred, please check your installation and try again
next error from JVM: A Java Exception has occurred.

**Comment by mastachaos** [comment]
also getting this error - the previous version of quark works fine

**Comment by LiloBzH** [comment]
same here

**Comment by lanner** [comment]
you need to update Java to 9 i think, and uninstall the java 8

**Comment by XorTroll** [comment]
^^ read the changelog please, if I spent time writing it is for something :P

**Comment by mastachaos** [comment]
The latest jre is version 8. If we need something different now, maybe tell us what that is (a link would be great).  Searching for "Java 9" leads you to Java SE 13.01 - the prerequisites are not clear at all.

**Comment by Pikotaro** [comment]
but no one is using java 9 except for some developers

**Comment by XorTroll** [comment]
Considering the libraries Quark uses, attempting to support both Java 8 and 9+ versions was too complex, so this was the best solution.
Check https://github.com/XorTroll/Goldleaf/blob/master/Quark.md to setup Quark properly (Mac section needs to be done)

**Comment by LiloBzH** [comment]
Rollback to tinfoil for me.
I dont want install another app only for quark.

Anyway, thank you for this app because it's good app !

**Comment by lanner** [comment]
Tested all java of the link, impossible to start Quark for me :)
