### ISSUE TITLE
[Quark] Wayland issues

### ISSUE THREAD

**Issue by A6GibKm** [XorTroll/Goldleaf#466]
# Core dump when using Quark in wayland

## Bug description

Quark trows an error when running it with wayland instead of Xorg, this wasn't the case with the version bundled with Goldleaf 0.7.2 or prior.

## Your setup

- **Goldleaf version**: 0.8

- **Quark version**: 0.3

## Bug reproduction

Run `java -jar Quark.jar` using wayland and get

```
(java:26118): Gdk-CRITICAL **: 19:07:38.462: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc48000cf90, pid=26118, tid=26166
#
# JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10)
# Java VM: OpenJDK 64-Bit Server VM (11.0.5+10, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007fc48000cf90
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /var/home/msandoval/.opt/Switch/core.26118)
#
# An error report file with more information is saved as:
# /var/home/msandoval/.opt/Switch/hs_err_pid26118.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

## Additional information

This isn't an issue with Xorg or previous versions.

**Comment by A6GibKm** [comment]
Solved by running it with `GDK_BACKEND=x11 java -jar quark-0.3.jar`.

**Comment by A6GibKm** [comment]
@XorTroll do you think it is possible to force the app to use the x11 backend so the user does not have to specify it? This would be great for the next release.

**Comment by dragon788** [comment]
You could test this yourself by editing the `Exec` line in the `.desktop` file if it uses one, just change it to `Exec=env GDK_BACKEND=x11 java -jar quark-0.3.jar` and see if that works, then search for that file in the repo and submit a pull request with that change.

**Comment by A6GibKm** [comment]
Quark does not have a desktop file.

**Comment by dragon788** [comment]
Ahh, you could make a little launcher script if you didn't want to remember to set the variable every time.

```
#!/bin/sh
GDK_BACKEND=x11
QUARK_DIR=/your/path/to/quark
pushd $QUARK_DIR
java -jar quark-0.3.jar
```

Then `chmod +x startquark` and you could copy it to `/usr/local/bin/startquark` and then you should be able to just run `startquark` from the terminal.
