### ISSUE TITLE
JNI Error with Quark on Windows 10

### ISSUE THREAD

**Issue by giga300** [XorTroll/Goldleaf#467]
# JNI Error with Quark

## Bug description

From Goldleaf 0.8, Quark is not usable with error **Error: A JNI error has occured, please check your installation and try again**. It works with old Quark but old Quark is not usable with Goldleaf 0.8.

## Your setup

- **Console firmware**: 9.0.1

- **CFW with version**: Atmosphere 0.10.1

- **Goldleaf version**: 0.8

- **Quark version**: 0.8

## Bug reproduction

Open Quark

## Additional information

![Error](https://i.imgur.com/d4UsENZ.png)

**Comment by XorTroll** [comment]
Which Java version do you have?

**Comment by giga300** [comment]
Java 8 Update 231

**Comment by XorTroll** [comment]
https://github.com/XorTroll/Goldleaf/blob/master/Quark.md
