### ISSUE TITLE
[Quark] Batch Install of NSPs 

### ISSUE THREAD

**Issue by mtoensing** [XorTroll/Goldleaf#468]
# Batch Install of NSPs 

## Feature description

Select more than one NSP from the GoldLead explorer and install them without any question asked 

## Benefits

faster installation of games and patches

## Additional information

I know that this was asked and closed before. But maybe this comfort feature can be included in the future.

**Comment by XorTroll** [comment]
This can already be done, select a folder, special options, install all NSPs inside the directory (not exactly what you're asking, but I doubt something more like yours will be added for now)

**Comment by mtoensing** [comment]
Thank you for your swift response. "special options"? How do I do that?

**Comment by lookye** [comment]
Press Y on the folder that contains your files.

**Comment by mtoensing** [comment]
Ah, **on** the folder and not **in** the folder. Thanks.

**Comment by Clydefrosch22** [comment]
Can this also be added for the VIRT:\ directory, cause I cant seem to get this working there
