### ISSUE TITLE
.INI error

### ISSUE THREAD

**Issue by Oui879** [XorTroll/Goldleaf#471]
Hi i am having this issue currently on goldleaf 0.8 using java 8u231 had no problems with 0.7.3.
when i launch quark on my pc a first error window pops up saying "Error: A .INI error has occured, please check your installation and try again" when I close this error window another one pops up saying "A Java Exception has occured"

**Comment by XorTroll** [comment]
https://github.com/XorTroll/Goldleaf/blob/master/Quark.md
