### ISSUE TITLE
Quark 0.8 cannot be run without Java SE 13

### ISSUE THREAD

**Issue by Filoppi** [XorTroll/Goldleaf#473]
## Bug description

I would expect a java application to only require the java runtime (8), not the development kit.

## Bug reproduction

Uninstall the Java SE, keep the Java runtime, run Quark.jar, get an error message

**Comment by lookye** [comment]
1. Not used the issue template
2. Its stated in the readme, that you need Java9 or higher

**Comment by Filoppi** [comment]
When you say you need java, it means you need the java runtime, not the java SE. Am I supposed to understand I need the java SE because you mentioned version 9 while the runtime only reaches 8?
