### ISSUE TITLE
Can't play installed nsp

### ISSUE THREAD

**Issue by failsafe42** [XorTroll/Goldleaf#477]
# Bug description

When I dump nsps from one emummc and try to install them in another, it says "Checking if the software can be played..." and doesn't let me play the game. I already have the latest sigpatches installed.

## Your setup

- **Console firmware**: 9.1.0

- **CFW with version**: Atmosphere 0.10.1

- **Goldleaf version**: 0.8

- **Goldtree version**: N/A

## Bug reproduction

1. Dump nsp
2. Boot into another emummc
3. Install nsp
4. Says "Checking if the software can be played..." and tries to connect to internet

**Comment by Bushido1992** [comment]
You have definitly the wrong patches. Download ES/FS Patches from gbatemp and try again

**Comment by lookye** [comment]
With which tool did you dumped the game? Does the dump have a ticket?

**Comment by XorTroll** [comment]
That's definitely a lack of the required ticket for the installed title to launch.

**Comment by failsafe42** [comment]
I figured it out. It's an issue with the way goldleaf dumps games. I just dumped them with nxdumptool and removed console specific data and they work without problems.

**Comment by BeckysFootSlave** [comment]
> I figured it out. It's an issue with the way goldleaf dumps games. I just dumped them with nxdumptool and removed console specific data and they work without problems.

Could you tell me how you did that?
Dumping with nxdumptool and especially how to remove console specific data!!
Would be awesome!

Thanks!

**Comment by failsafe42** [comment]
> Could you tell me how you did that? Dumping with nxdumptool and especially how to remove console specific data!! Would be awesome!
> 
> Thanks!

Open nxdumptool, select the game you want to dump, select nsp dump, and before you start the dump go down to ″Remove console specific data″ and set it to yes.

**Comment by BeckysFootSlave** [comment]
Thank you so much failsafe42
Helped me allot!
