### ISSUE TITLE
[Quark] can't install nsp files from usb

### ISSUE THREAD

**Issue by TheAustralianTaco** [XorTroll/Goldleaf#478]
can't install nsp's file from usb using Quark
when i try to install a nsp file to my switch using quark, goldleaf freezes and quark does nothing.

- **Console firmware**: 9.1.0

- **CFW with version**: AMS 0.10.2

- **Goldleaf version**: 0.8

- **Quark version**: 0.3.0

It Happens every time on my 2 computers when trying to install anything even on 2 diferent sd cards.

![Sin título](https://user-images.githubusercontent.com/59661972/72002582-6ef64200-3226-11ea-82c1-ea3a3ad360d5.png)
quark stays like that

**Comment by RaistlinY** [comment]
@TheAustralianTaco   how do you fix this issue?

**Comment by herman23a** [comment]
cannot fix this issue, just back to old version 0.73
