### ISSUE TITLE
Crash on update without connection (v0.8)

### ISSUE THREAD

**Issue by Krude** [XorTroll/Goldleaf#479]
# Crash on update without connection (v0.8)

## Bug description

Hitting "Update" on a fresh install when in airplane mode (or possibly just without a current connection) will crash the console.

## Setup

- **Console firmware**: 9.1.0

- **CFW with version**: Atmosphere 0.10.2

- **Goldleaf version**: 0.8

## Atmosphère crash log

https://pastebin.com/wtxAvPAi

**Comment by XorTroll** [comment]
All the backtrace addresses in the crash report point to nx-hbmenu (they would point to Goldleaf if it was Goldleaf's fault)
