### ISSUE TITLE
Downgrade update versions for games

### ISSUE THREAD

**Issue by ckurtz22** [XorTroll/Goldleaf#48]
Can only be done with dev menu atm, but in order to install older update versions of games you have to reset the required version number or the Switch won't let you play without updating. Super useful especially for speedrunning games that lose glitches in newer patches like Mario Odyssey etc.

**Comment by ckurtz22** [comment]
Ah. Is that something that can be touched with homebrew atm or in the future? And that is in USER/Save on my NAND right?

**Comment by ckurtz22** [comment]
Went to look into it myself, and by using LibHac by Moosehunter, I found that the required version is stored inside SYSTEM/save/8000000000000045 and when extracting the container with LibHac/hactoolnet you get 4 files, req_version_db, req_version_header, version_list_db, and version_list_header. req_version_db is the one we want obv, and inside it you have 16 byte chunks that contain the title ID followed by 2 4 byte segments, the first one being the required version, and the 2nd one seemingly being always 0.

**Comment by XorTroll** [comment]
Done for 0.7

**Comment by zakv91** [comment]
sorry to ask, but how do you do this? like from 1.05 -> 1.04
