### ISSUE TITLE
quark unknown id 15 when remote PC

### ISSUE THREAD

**Issue by bkjason** [XorTroll/Goldleaf#482]
# Quark unknown id 15 when remote PC

## Bug description

Showing Unknwn ID 15 when doing remote PC in switch 

## Your setup

- **Console firmware**: [ 9.1 ]

- **CFW with version**: [ Atmosphere 10.2 ]

- **Goldleaf version**: [ 0.8 ]

- **Goldtree version**: [ quark 0.2 ]

**Comment by lookye** [comment]
Update your Quark version to the latest version and read its changelog.
