### ISSUE TITLE
Add build step on readme

### ISSUE THREAD

**Issue by macabeus** [XorTroll/Goldleaf#483]
## Feature description

Would be useful to describe the step by step to build it. It is useful to avoid mistakes

For example:

```
sudo dkp-pacman -S switch-curl -r /System/Volumes/Data
```

Because we need to add curl as dependency.

```
git clone --recursive git@github.com:XorTroll/Goldleaf.git
```

Because we need to clone submodules.

Also, need to link to `Plutonium` repository saying that install its dependencies firstly.

## Benefits

Better documentation for this project.

## Additional information

Maybe there are some useful builds steps to describe here.

**Comment by XorTroll** [comment]
Good point, in fact Goldleaf's documentation in general should be rewritten to be less messy and to be more specific on certain aspects.

**Comment by XorTroll** [comment]
Done on latest commit
