### ISSUE TITLE
[Quark] Auto reconnect

### ISSUE THREAD

**Issue by macabeus** [XorTroll/Goldleaf#485]
## Feature description

Would be very useful and improve UX if Quark try to auto reconnect when lost the connection.

## Benefits

A use case is when you are developing a homebrew. So you need to send and lauch a `.nro` file.
Then you close Goldleaf and on the next time you need to run it again to send a new version of your `.nro`.
But is very boring to click on `Ok` button on Quark in order to reconnect again. Would be better if it auto reconnect again.

**Comment by XorTroll** [comment]
Currently when Quark gets disconnected will continuously try to reconnect unless the user exits, can this be considered what you were asking for?
