### ISSUE TITLE
Online shop integration (JITS, hbg, etc.)

### ISSUE THREAD

**Issue by JoshuaManuel** [XorTroll/Goldleaf#488]
# Jack in the Shop Integration

## Feature description

Allow network installs from places like Jack in the Shop. Ideally the server configs would be built in or allow users to enter them manually. This would be similar to Tinfoil.

## Benefits

+ Allow users to install new games without a USB connection or removing their SD card.
+ Greatly reduce the hassle of finding new NSPs and installing them

## Additional information

I believe this is potentially the biggest feature stopping users from switching from Tinfoil to GoldLeaf.

I would be willing to undertake development of this feature myself if no one wants to, though I have minimal switch homebrew dev experience.

**Comment by Enspiron** [comment]
100% Piracy related. No.
