### ISSUE TITLE
[Quark] doesn't connect to the Switch

### ISSUE THREAD

**Issue by Diego788** [XorTroll/Goldleaf#489]
I'm trying to connect Quark to Goldleaf so I can install some .nsp, but Quark doesn't connect, I tried some old versions too but no luck, all I see is "Connected! Processing USB input from Goldleaf..." but nothing happens

## Your setup

- **Console firmware**: 9.1

- **CFW with version**: Atmosphere 0.10.2

- **Goldleaf version**: 0.8 and 0.7.3, tried with both

- **Goldtree version**: I'm using Quark, version 0.2.0

## Bug reproduction

-connect the Switch to the PC though an USB port, 2.0 or 3.0 (doesn't seem to matter, happens to me on both ports)
-open Goldleaf (ver. 0.7.3 or 0.8)
-start Quark.jar
-it stays on the "Connected..." screen

the USB cable is in good condition, tried with other cables too, works in other programs but not on Quark

here's an screenshot of Quark trying to connect, and Zadig showing that I have the correct libusbK driver
![image](https://user-images.githubusercontent.com/19751404/73115720-ba883b80-3f08-11ea-8f9f-99a22c472455.png)

**Comment by lookye** [comment]
Please update your Quark version with the one from the Goldleaf 0.8 release.

**Comment by XorTroll** [comment]
Outdated Quark
