### ISSUE TITLE
Title with latest update still asks for new update download when launching

### ISSUE THREAD

**Issue by tk1076408** [XorTroll/Goldleaf#492]
## Bug description

[ Title with latest update still ask for new update download when launching even without wifi ]

## Your setup

- **Console firmware**: [ 9.1.0 ]

- **CFW with version**: [  Atmosphere 0.10.2 ]

- **Goldleaf version**: [ 0.8.0 ]

- **Goldtree version**: [ unkown ]

## Bug reproduction

Turn off wifi.
Turn on "Ignore required firmware version for installs: Yes"
Install Zelda: BotW base version, update v720896, DLC1, DLC2
Launch this title, dialog pops out with "A new update is available. It will be downloaded now".
I can choose  'Start Software' game runs, but it's annoying to have one more step select to launch any title.

Tried to reset launch version, same.

## Additional information

[ 
![IMG_4190](https://user-images.githubusercontent.com/7875150/73331673-65ef0400-4219-11ea-962f-6f9a4641b717.jpg)
]

**Comment by deadair3210** [comment]
If it's still asking for the latest update, either your update is broken or isn't the latest update

**Comment by tk1076408** [comment]
That’s wired, as I mentioned I have WiFi disable all the way, how does the console know it’s not the latest version?

Also I double checked v720896 is the latest version for botw.

**Comment by lookye** [comment]
It´s not the latest version. It is v786432. Update your game.
