### ISSUE TITLE
Goldleaf crashing when browsing SD card

### ISSUE THREAD

**Issue by theboy181** [XorTroll/Goldleaf#495]
CRASH
When you brows through your SD card using Goldleaf it will crash

9.1FW

Latest (at this time) Atmosphere

Goldleaf - latest  build supplied from RELEASE

https://cdn.discordapp.com/attachments/655681905907466250/675243813203345418/video0.mov

**Comment by lookye** [comment]
Please use the issue template and open a new issue.
