### ISSUE TITLE
Quark Compile error

### ISSUE THREAD

**Issue by Driftends3** [XorTroll/Goldleaf#504]
# [ Quark compilation failed ]

## Bug description

[ Quark does not allow me to use when opening Gold Leaf, specifically on the part of remote PC (via USB) that is what I need. When I open Quark I receive two messages, the first being like this;![Screenshot_2](https://user-images.githubusercontent.com/61655760/75626967-c66fb900-5baa-11ea-9f90-3b9360f4c133.png) and the second;![Screenshot_3](https://user-images.githubusercontent.com/61655760/75626966-c4a5f580-5baa-11ea-9386-b266015f9f04.png). I hope you can help me. Regards! ]

## Your setup

- **Console firmware**: [ 9.0.0 ]

- **CFW with version**: [ Atmosphere 0.9.4 ]

- **Goldleaf version**: [ 0.8 ]

- **Goldtree version**: [ I'm using the actual Quark version ]

**Comment by lookye** [comment]
Read the latest changelog. Update e.g. to Java**9**
