### ISSUE TITLE
[Quark] A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by TraeF1337** [XorTroll/Goldleaf#508]
# [Quark] A JNI error has occurred, please check your installation and try again

## Bug description

Cant even start Quark 0.8.0 but older version works fine.

## My Setup
- **WIndows**: 10 64 bit 1909
- **java**: 1.8.0_241 x86_64 

- **Goldleaf version**: [ 0.8.0]

## Bug reproduction

Every time I start Quark

**Comment by TraeF1337** [comment]
Can be ignored fixed it with OpenJdk 13 install

**Comment by markmghali** [comment]
How did you fix this issue?

**Comment by lookye** [comment]
This is a lack of having not installed Java9 as said in the latest changelog.
