### ISSUE TITLE
[Quark] Can't connect via USB

### ISSUE THREAD

**Issue by HellsMike** [XorTroll/Goldleaf#509]
## Bug description

Even if Quark recognise my NS, it still say to me that it does't recognise, as you can see from the picture, NS is detected but i can't continue.

## Your setup

- **Console firmware**: 9.1

- **CFW with version**: Atmosphere 0.10.2

- **Goldleaf version**: 0.8

- **Goldtree version**: 0.3

## Additional information

![Immagine](https://user-images.githubusercontent.com/62393676/77088052-2b793a80-6a04-11ea-9c26-62c1c7c40a84.png)

**Comment by lookye** [comment]
https://github.com/XorTroll/Goldleaf#quark-and-remote-pc

**Comment by HellsMike** [comment]
I had follow the guide yet and this is the result, if i mess something, i'm glad to know it

**Comment by XorTroll** [comment]
Are you sure you're using the latest Goldleaf and Quark?
That error might mean that your Goldleaf isn't the latest release...

Can't think of any other potential issues
