### ISSUE TITLE
enhancement: folder browser and list jump

### ISSUE THREAD

**Issue by matteopiccioni** [XorTroll/Goldleaf#51]
Hello,
I'd like to suggest three useful features (if possibile)
- show masterkey version of nsp, if install fails
- possibility to browse folders inside nsp directory
- possibility 'paging'  files faster inside a folder with r and l buttons (for example)
Thanks

**Comment by XorTroll** [comment]
1 - Shown in the ticket of the NSP
2 - NSP has no folders...?

**Comment by XorTroll** [comment]
...
