### ISSUE TITLE
Update to emuiibo 0.5

### ISSUE THREAD

**Issue by impeeza** [XorTroll/Goldleaf#520]
Hi, Emuiibo 0.5 was released and works a lot different.  thanks a lot for your hard work

**Comment by XorTroll** [comment]
Yeah, this must be done for 0.9

**Comment by impeeza** [comment]
🎉 thanks a lot

**Comment by forxdhvg** [comment]
donde puedo ver la 
Actualización a emuiibo 0.5

**Comment by impeeza** [comment]
En el sitio oficial de emubiio:
https://github.com/XorTroll/emuiibo

No olvides buscar también sobre tesla overlay. Lo vas a necesitar

**Comment by forxdhvg** [comment]
muchísimas gracias saludos cordiales

**Comment by forxdhvg** [comment]
amigo   ya puse el tesla y aparece el amiibo   y si sale para  activarlo y desactivarlo, pero el problema es que no localiza las carpeta dond pongo los  amiibos  me sala una que dice (root) y otra miis
pero en ninguna  de las dos  aparece nada te agradezco mucho tu ayuda

**Comment by impeeza** [comment]
Debes seguir bien las instrucciones. Las carpetas de cada amiibo deben ser copiadas en una carpeta específica.  A menos que tengas un volcado de un amiibo real que quieras convertir, te recomiendo usar la herramienta de creación de emubiio. Te recomiendo leer el archivo Read.me de emubiio.

**Comment by forxdhvg** [comment]
Gracias ya lo hize paso a paso y funciona exelente muchas gracias y felicitaciones a los creadores son unos cracks

**Comment by XorTroll** [comment]
Añadiré soporte de la última versión de emuiibo en la próxima versión de Goldleaf (0.9), hasta entonces la única forma de controlarlo es con el overlay de Tesla.

**Comment by impeeza** [comment]
Thank you very much for all your work.  I owe you a beer :D
