### ISSUE TITLE
Clock timezone stuck at GMT +0

### ISSUE THREAD

**Issue by Bec91v** [XorTroll/Goldleaf#522]
# [ Bug report title ]

Clock timezone stuck at GMT +0

Hi, I noticed that the time displayed is of timezone GMT +0.

## Your setup

- **Console firmware**: 9.2.0

- **CFW with version**: [ Atmosphere 0.11.1 ]

- **Goldleaf version**: [ 0.8 ]

- **Goldtree version**: [  ]

## Bug reproduction

Time displayed at the right hand corner

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
The displayed time depends on your console settings. I just changed times and timezones and everything was shown correct in Goldleaf. What is the exact problem you´re running into?

**Comment by Bec91v** [comment]
I changed my region from US to Europe.
When i was using Goldleaf, i noticed the clock reading was amissed.
I tried switching back to US but the error is still there.
The hnmenu is showing the correct time though

**Comment by Bec91v** [comment]
https://github.com/switchbrew/libnx/commit/f043307e7f580f6507f4285c898c6ac725bb364f
I think this commit didn't went into your build

**Comment by lookye** [comment]
So, you´re not changing just time/timezone but the whole region. Did the same thing you described above and restartet the console. No difference for me, time is still shown in goldleaf. Even after changing the region back and restarting again.

I can not reproduce your problem.

**Comment by Bec91v** [comment]
weird, i tried changing the timezone forward, the time will be valid.
if using the same or previous timezone, the clock will be at GMT +0

**Comment by lookye** [comment]
Ok this exactly thing is reproducable. I changed it from something in EU to something in US and  the time didnt show up properly.

**Comment by XorTroll** [comment]
Is this still a problem with latest Goldleaf?
If so, does it also happen with other homebrew apps like hbmenu itself?

**Comment by XorTroll** [comment]
This seems to be no longer a problem
