### ISSUE TITLE
Quark displays garbled text on OSX

### ISSUE THREAD

**Issue by gRoberts84** [XorTroll/Goldleaf#524]
# Quark displays garbled text on OSX

## Bug description

The released version of Quark.jar fails to identify the correct font to use when loading. Console displays multiples of the following:

`2020-04-25 12:41:52.702 java[33063:805838] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].`

## Your setup

- **Java firmware**: 
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
- **OSX version**: Catalina 10.15.3 (19D76)

## Bug reproduction

Simply run Quark.jar, `java -jar Quark.jar`

<img width="899" alt="Screenshot 2020-04-25 at 12 29 08" src="https://user-images.githubusercontent.com/348184/80278995-96e4b500-86f2-11ea-9b4b-3208b998da87.png">

## Additional information

Related to the following https://bugs.openjdk.java.net/browse/JDK-8234916

I simply resolved this by adding: 

```
.root {
    -fx-font-family: Helvetica, sans-serif;
}
```

to `main/resources/Main.css` and rebuilding.

**Comment by Olshansk** [comment]
Were you using a USB 2.0, USB 3.0 or USB-C type port?

**Comment by gRoberts84** [comment]
> Were you using a USB 2.0, USB 3.0 or USB-C type port?

Not sure why that would matter as it's relating to the default font that isn't available on OSX. 

To answer your question though, USB 3.0

**Comment by warpkanal** [comment]
Thanks @gRoberts84, your workaround worked for me!

**Comment by i-am-the-slime** [comment]
You can also edit the jar with vim and add this rule. That was more convenient for me.

**Comment by XorTroll** [comment]
Whoops - I haven't payed attention to this issue in almost a year, just added the fix in the last commit.
