### ISSUE TITLE
Protect against things like custom modules

### ISSUE THREAD

**Issue by Nazosan** [XorTroll/Goldleaf#525]
So a while back I tried the Tinfoil.io tinfoil since it supports some newer formats among other things.  I was a bit irritated at some of its actions including something that could very well be a potential trojan (if not now then later.)  But it also highlights a potential security issue all around.  Pretty much any app could ultimately just install its own custom modules and they don't really even have to ask you then those modules can be used to bypass all protection mechanisms built-in to Atmosphere anyway.

I know it isn't Atmosphere's job to hold the user's hand and act as a virus scanner or whatever, but it does seem like allowing anything to just drop in custom modules at will is a recipe for disaster all the same.

It probably also needs to protect its INI files from modification while it's running I think.  I realize this could be annoying in regards to FTPing changes over, but it's a small price to pay given that an app can currently just disable all protections anyway.

**Comment by XorTroll** [comment]
So what do you expect Goldleaf to do? Goldleaf isn't Atmosphere.

**Comment by Nazosan** [comment]
Oh geez, I'm sorry.  I posted on the wrong one.
