### ISSUE TITLE
Emuiibo Management Option refuses to load (and sometimes crashes Atmosphere CFW)

### ISSUE THREAD

**Issue by CountHomer69** [XorTroll/Goldleaf#527]
## Emuiibo Management Option refuses to load (and sometimes crashes Atmosphere CFW)

When Emuiibo Management is clicked, it says "emuiibo isn't presented or loaded", and if you keep pressing the button enough, it softlocks Goldleaf. If rebooted after softlocking, Atmosphere will crash.

## Your setup

-  10.0.2

- Atmosphere 0.12.0

- Goldleaf 0.8.0

- Unknown?

## Bug reproduction

Reason for why it doesn't load is unknown.

When it doesn't let you load, and you repeatedly press the button, Goldleaf softlocks, and crashes Atmosphere upon opening again after creating the softlock.

## Additional information

Emuiibo Version is 0.5

**Comment by lookye** [comment]
Goldleaf was not updated for the latest emuiibo version. Thus it wont work properly atm.

**Comment by CountHomer69** [comment]
Is there any amiibo loader programmed to handle 0.5?

**Comment by lookye** [comment]
As written in the changelog of emuiibo: The tesla overlay for the moment.
