### ISSUE TITLE
Crash on homebrew install

### ISSUE THREAD

**Issue by HookedBehemoth** [XorTroll/Goldleaf#529]
## Bug description

I wanted to install the homebrew so I go to the sd card and select the atmosphere and I push install on the hbl.nsp and it crashed blue screen. Please help!!!

## Your setup

- **Console firmware**: 10.0.2

- **CFW with version**: atmosphere 12.0

- **Goldleaf version**: 0.8.0

- **Goldtree version**: what is a goldtree???

## Bug reproduction

You wanted to install the homebrew so you go to the sd card and select the atmosphere and you push install on the hbl.nsp and it crashed blue screen.

## Additional information

Crash report attached

[01588884199_010000000000100d.log](https://github.com/XorTroll/Goldleaf/files/4595692/01588884199_010000000000100d.log)

**Comment by XorTroll** [comment]
Fixed for 0.9
