### ISSUE TITLE
Error 2145-0001 (0x291)

### ISSUE THREAD

**Issue by Emmadeath** [XorTroll/Goldleaf#530]
BUG DESCRIPTION

Pretty much I can't install any nsp.
This is the message that pops up after trying to install them. 

Error 2145-0001 (0x291)
Module: ETicket (145)
Description: Unknown or Undocumented error (1) 

I've try this with multiple installers like lithium, awoo, tinfoil etc, didn't work either, pretty much same error.

I have all the sigpatches (es fs) and install them with the sigpatch installer on the switch 

## MY SETUP

- **Console firmware**: 10.0.2

- **CFW with version**: hekate Kosmos 16.1

- **Goldleaf version**: 0.8

## BUG REPRODUCTION

Tried installing an NSP via SD install on goldleaf and thats pretty much

**Comment by lookye** [comment]
The sigpatches aren´t installed properly if you get the ETicket error. Set them up properly.

**Comment by Emmadeath** [comment]
So is there a thread on how to install the properly?

**Comment by bristleroot** [comment]
Are you using the updated sigpatches for 10.0.0

**Comment by bristleroot** [comment]
https://www.reddit.com/r/SwitchPirates/comments/g2n7is/sigpatches_for_1000_are_out/

**Comment by Emmadeath** [comment]
Ooooh maybe thats it... I only install the current version ones

**Comment by Emmadeath** [comment]
Thank you all btw

**Comment by aaron0791** [comment]
> Ooooh maybe thats it... I only install the current version ones

Can you elaborate how you were able to solve this?
I have done everything, installed all the sigpatches and goldleaf can't install anything I keep getting the same freaking error.

**Comment by kokerakos** [comment]
@aaron0791 if you are sure that you have all the proper versions installed (system firmware, Atmos, Hekate, fusee-primary.bin)(i got 10.0.2, 15, 5.3.4)
..and you still getting such errors:
1)load the fusee-primary.bin (from your bootloader)
2)use the latest version of Goldleaf on both pc and switch (I am using v3.0)
