### ISSUE TITLE
Key Generation Mismatch

### ISSUE THREAD

**Issue by ozkan7** [XorTroll/Goldleaf#531]
# [ Bug report title ]
Key Generation Mismatch
# Bug description
so i'm trying to download the 1.2.0 update for animal crossing and when i load into ns-usb loader and try to install onto  my sd card it says "key generation mismatch,console software too (8)" but my goldleaf is updated to the latest 0.8 can anyone help
[ Please describe your bug as detailed as possible here. ]

## Your setup
nintendo switch
- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]
7.0.1
- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]
0.8
- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction
go into gold leaf ,explore content,pc(via USB),try install the update<the error occurs
[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by lookye** [comment]
You´re firmware is too old. Please update it.
