### ISSUE TITLE
Add support for split nsp's

### ISSUE THREAD

**Issue by Ali-Asim800** [XorTroll/Goldleaf#546]
# [ Add support for split NSP files ]

## Feature description

[ I think it would be great if the best, most trustworthy tool for not only installing titles but many more to be able to install split nsp files, I would really like this feature to be implemented, for some reason split nsp's work on tinfoil but I'm not using it since it's closed source, so I would really like goldleaf more if I had the option to install split nsp's. ]

## Benefits

[ the benefits of this would be that fat32 users could install their large games without any problems and that it would just make things much much easier. ]

**Comment by XorTroll** [comment]
FAT32 users can make use of archive bit folders, placing inside those the different parts of the NSP.

**Comment by lookye** [comment]
It´s discussed in #329

**Comment by Ali-Asim800** [comment]
yeah didn't realize this and did some research. thanks for telling me
