### ISSUE TITLE
"Reset launch version" not working to remove update nag anymore

### ISSUE THREAD

**Issue by samcambolt270** [XorTroll/Goldleaf#559]
**Bug description:**

Selecting "Reset launch version" does not remove the "software update required" nag message when launching games.

**Your setup:**

    Console firmware: 10.0.2

    CFW with version: AMS 0.12.0|S

    Goldleaf version: 0.8

**Bug reproduction:**

1: Update a title
2: Delete the update
3: Select "Reset launch version" on that title
4: launch that title (and it will still require you to update)

**Comment by XorTroll** [comment]
Known bug, 0.9 aims to fix it.

**Comment by samcambolt270** [comment]
Oh. I apologize. I wasn't aware it was a known bug.

**Comment by FlareBlitz17** [comment]
Is there a dev version of Goldleaf that fixes this?
