### ISSUE TITLE
Set option to put the goldleaf folder (usually found on the root) in the switch folder instead.

### ISSUE THREAD

**Issue by Aliasim800** [XorTroll/Goldleaf#563]
# Set option to put the goldleaf folder (usually found on the root) in the switch folder instead.

## Feature description

Would please appreciate it if this can be implemented some time soon. I would like the goldleaf folder which is normally found on the root of the  sd card to be in the switch folder directory, I know that there is a goldleaf folder located in the switch folder as well as the root containing different folders and things. What you could do though is merge both the folders to be located in the switch folder.

## Benefits

A cleaner root of the sd card only containing main files that the switch needs to run cfw etc and homebrew app folders only being located in the switch folder.

## Additional information

You could make it similar on how JKSV does it, what JKSV does to put its folder in the switch folder instead of the root is by placing a .txt file named "jksv_dir.txt" in the switch folder and putting the text "sdmc:/switch/JKSV/" in the .txt file which will force the program to put its folder in the switch directory, but its even more flexible than that, if you wish you can put whatever directory you want jksv to put its folder in by just changing the text in the .txt file. You can make it as simple as that or you can just add an option in goldleaf to tell it where to put its root folder in.

Here is the image which jksv shows how to change where it puts its root folder:
![20200718_215306](https://user-images.githubusercontent.com/64366457/87861765-2344f380-c941-11ea-9104-823d551d3022.png)

Thank you and I look forward to this and hope my suggestion gets accepted.

**Comment by lookye** [comment]
It is already /switch/goldleaf. This was done several releases ago.

**Comment by lookye** [comment]
> What you could do though is merge both the folders to be located in the switch folder.

This was already done several releases ago. If you have the `Goldleaf` folder in root, you can delete it.

**Comment by Aliasim800** [comment]
You can delete it then what? I tried doing that a couple of times but it just appears back again, it doesn't appear in the switch folder.

**Comment by lookye** [comment]
Everything is handled in /switch/Goldleaf/

**Comment by Aliasim800** [comment]
Deleted it and did some dumping and did some other stuff that would normally form a goldleaf folder on root but now it seems that it does put everything in  /switch/Goldleaf/ so thanks! Though idk why it didn't work before, at least it does now. Thanks again!
