### ISSUE TITLE
Error 2145-0001

### ISSUE THREAD

**Issue by ekiholic** [XorTroll/Goldleaf#568]
# Error 2145-0001

## Bug description

This bug doesn't happen all the times, but I can't download some games/updates/DLCs. I saw on other issue that the problem was missing sigpatches. But I have both fs and es. Does anyone know how to solve this ?

## Your setup

- **Console firmware**: 10.1.0

- **CFW with version**: Atmosphere 0.14.1

**Comment by lookye** [comment]
Issues #556 #557 and #530 are there already. Fix your setup and grab all the latest sigpatches for atmosphere 0.14.1.

**Comment by aaron0791** [comment]
> Issues #556 #557 and #530 are there already. Fix your setup and grab all the latest sigpatches for atmosphere 0.14.1.

Please be more specific. Dragging and dropping them does not fix anything. I keep getting the same error message
