### ISSUE TITLE
Key Generation Mismatch

### ISSUE THREAD

**Issue by Hoobastank55** [XorTroll/Goldleaf#574]
# [ Key Generation Mismatch]

I'm using goldleaf. When I try to install some games such as Animal Crossing or update of Luigi Mansion3 there is a warning Key Generation Mismatch console firmware is too low (8).I saw the same mistake on the github but I cant solve the problem. I guess goldleaf key generation must be 11 not 8 but I dont know how to do that. I'm the newbie..Please help me.. Thank you..

- **Console firmware**: [ 10.2.0]

- **CFW with version**: [ SX OS V3.0.5 ]

- **Goldleaf version**: [ 0.8.0]

**Comment by lookye** [comment]
SX isn´t really supported. You can always change to atmosphere incl. sigpatches to install stuff.

**Comment by Hoobastank55** [comment]
There is chip inside of the switch. Is it possible to change to atmosphere?

**Comment by Masamune3210** [comment]
I just realized how many people are now in danger of being stranded on SX if not....

**Comment by lookye** [comment]
Well if you have a modchip you´re screwed anyway imo.

**Comment by Masamune3210** [comment]
That's fair

**Comment by Hoobastank55** [comment]
Then there is nothing to do right?
