### ISSUE TITLE
[REQUEST] Add nso dumping from goldleaf

### ISSUE THREAD

**Issue by 64dd** [XorTroll/Goldleaf#577]
## Feature description
It would great if goldleaf were able to dump just the nso of the game if it's even possible.

## Benefits
Saves time for larger nsp, no need to wait for transfer nsp to pc and no need to wait for nsp and nca to be extracted.

**Comment by XorTroll** [comment]
If you mean just dumping the main executable(s) of the game I'm not sure that's possible due to system limitations to access a title's executables
