### ISSUE TITLE
Needs support for 11.0.0 switch update and latest version of atmosphere

### ISSUE THREAD

**Issue by ElucidatorEX** [XorTroll/Goldleaf#578]
# Not Working on Latest Switch Update

## Bug description

Needs support for 11.0.0 switch update and latest version of atmosphere

## Your setup

- **Console firmware**: 11.0.0

- **CFW with version**: Atmosphere 0.16.0

- **Goldleaf version**: 0.8

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by 5H4D0WILA** [comment]
Why should XorTroll add support for a pre-release if sigpatches will not get released before the full release of atmosphere drops?

**Comment by 20Phoenix** [comment]
Correct, v0.8 and 0.9dev don't work with FW 11.0, needs a rebuild.
I use SXOS 3.1.0 with FW 11.0, currently causing a crash sooner or later.

**Comment by jcbuzby** [comment]
There is a development build that works with 11.0.0 and 11.0.1, give it some time

**Comment by colbyjayallen** [comment]
@jcbuzby Where can I find that dev build?

**Comment by jcbuzby** [comment]
I found it in gbatemp forum about goldleaf, should be pretty easy to find

**Comment by jcbuzby** [comment]
> 
> 
> https://mega.nz/file/gUtwiKJA#xmUS0HG8a9qV40aKqomWhbZqqSGCSL9L57Z2NAs6HTw

**Comment by lookye** [comment]
Official dev builds are available on Xors discord. Theres no need for other links.

**Comment by jcbuzby** [comment]
someone independently compiled this version and is the only one I found working so far.  I dont want to use tinfoil, tinleaf, awoo. I like goldleaf, the simplicity. This one will do for now. The color of the theme even changes every time you open it.

**Comment by colbyjayallen** [comment]
This experimental build works with the updated sigpatches. Thank you.

**Comment by xXxQuiquexXx** [comment]
> 
> 
> > https://mega.nz/file/gUtwiKJA#xmUS0HG8a9qV40aKqomWhbZqqSGCSL9L57Z2NAs6HTw

send external links having an official repository. why?

**Comment by j-james** [comment]
@5H4D0WILA : GoldLeaf has a plethora of other features besides installing software.

**Comment by zzpixel** [comment]
does this need to be converted to a .nro?

**Comment by jcbuzby** [comment]
> does this need to be converted to a .nro?

No just extract the rar and it is already goldleaf.nro

**Comment by zzpixel** [comment]
Thanks

**Comment by zzpixel** [comment]
Is there an updated quark.jar?

**Comment by jcbuzby** [comment]
> Is there an updated quark.jar?

No, it still works with latest zadig and quark

**Comment by Th3Alic3** [comment]
Hello @XorTroll!

Do we have an eta for when an update to GoldLeaf will come out to resolve this issue? _(I am forced to use Quark since our game consoles have their own home network separate from our computers. Which I cannot do until Goldleaf will open again.)_

Thanks

**Comment by lookye** [comment]
There is no eta.

**Comment by ghanashyaml** [comment]
> > > https://mega.nz/file/gUtwiKJA#xmUS0HG8a9qV40aKqomWhbZqqSGCSL9L57Z2NAs6HTw
> 
> send external links having an official repository. why?

This worked!! Thanks!

**Comment by Th3Alic3** [comment]
The alt version that @xXxQuiquexXx is a development version so it does not work with Quark.


We need an update to this app @XorTroll!

**Comment by xXxQuiquexXx** [comment]
> 
> 
> The alt version that @xXxQuiquexXx is a development version so it does not work with Quark.
> 
> We need an update to this app @XorTroll!



You are wrong, I did not develop anything, I prefer to wait for the official release of @XorTroll

**Comment by MasterDriverRex** [comment]
Yep, updated to latest version, and am able to boot into CFW (emuMMC) - but trying to launch Goldleaf crashes the system. I have to hold down the power button to turn the console off completely, then use my jig to launch back into CFW.

This is a major problem - is there an alternative? And not Tinfoil (or whatever has an icon containing a heart made out of squares); that's never worked for me.

**Comment by Borrajo** [comment]
awoo-installer

**Comment by MasterDriverRex** [comment]
> awoo-installer

That works! Thanks for the quick reply, mate!

**Comment by nwhiteman42** [comment]
Did the .9 release fix this?  On 11.0.1 I am still crashing when opening.  Deleted all goldleaf files and still no luck

**Comment by Masamune3210** [comment]
Launched fine for me, don't use the nsp, launch it from hbmenu

**Comment by j-james** [comment]
The 0.9 release fixed this. You likely have some leftover files - GoldLeaf writes to strange locations, like `atmosphere/contents/0100000000001013`.

**Comment by nwhiteman42** [comment]
I am launching from hbmenu.  I tried deleting `atmosphere/contents/0100000000001013` and it made no difference.  
![20210211_160801](https://user-images.githubusercontent.com/22136824/107699262-d7162380-6c83-11eb-844e-87d3b818b793.jpg)

**Comment by nwhiteman42** [comment]
I don't know how to parse the fatal error dump but looking at it in HxD it mentions fsp-usb multiple times

**Comment by lookye** [comment]
Works fine as intended. Just tested for you: Firmware 11.0.1, Fresh install of AMS 0.18.0 and Goldleaf 0.9.

**Comment by nwhiteman42** [comment]
Must just be me then.  I'll post my solution if I find it
