### ISSUE TITLE
Goldleaf black screen

### ISSUE THREAD

**Issue by Bafio2603** [XorTroll/Goldleaf#579]
# [ Bug report title ]

## Bug description

[I can't open Goldleaf, just show me a black screen. I've already read that SysDVR may cause black screen but i have nothing installed ]

## Your setup

- **Console firmware**: [ 11.0.0 ]

- **CFW with version**: [Atmosphere 0.16.0 ]

- **Goldleaf version**: [0.8]

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
#578 11.0.0 has breaking changes, thus Goldleaf needs to be recompiled. Will drop 0.9 soon fixing this

**Comment by digweedgr** [comment]
Any news on the release date?
