### ISSUE TITLE
goldleaf isn't opening

### ISSUE THREAD

**Issue by saduwuhour** [XorTroll/Goldleaf#580]
# [ Bug report title ]

## Bug description

when i try to open goldleaf it flashes black and then goes back to the homebrew menu. if i then try to open anything else (like settings or news) it gives me a grey screen with the switch and ok in the bottom corners. in this state i cant enter sleep mode, home menu etc . i have tried following other solutions like deleting atmosphere and installing clean, ive tried replacing the goldleaf nro and downloading sigpatches and nothing worked

## Your setup

- **Console firmware**: [ 11.0 ]

- **CFW with version**: [  Atmosphere 0.16.0 master ]

- **Goldleaf version**: [ e.g. 0.8.0 ]

- **Goldtree version**: don't think it's relevant

## Bug reproduction

trying to open goldleaf and then opening settings

## Additional information

after a few minutes of leaving it like that it gives me an error code 2162-0002 (0x4a2)

**Comment by XorTroll** [comment]
#578
