### ISSUE TITLE
Goldleaf 0.5 and 0.8 does not start

### ISSUE THREAD

**Issue by Archik1000** [XorTroll/Goldleaf#582]
# [ Goldleaf 0.5 and 0.8 does not work ]

## Bug description

I had a problem with installation of new games because of old version of Atmosphere. I upgraded it to the latest version 0.16.1|E with Hbmenu 3.4.0. After it I could install the NSP games using Goldleaf 0.5. Goldleaf 0.8 with Quark did not work. When I tried to open games it require new System version, So i updated to the latest version 11.0.1 by Daybreak. Than I run sigpatch-updater and games started to work fine, but now Goldleaf does not open anymore. Not0.5 and not0.8. It just give for a seconds black screen and then come back to the Hbmenu. The worse thing is that after this I have to restart console. because of when I start the game the switch stuck. Please help how to fix the problem with Goldleaf, because current situation even worse then before I started to upgrade to new versions.  

## Your setup

- **Console firmware**: [11.0.1]

- **CFW with version**: [ Atmosphere 0.16.1|E ]

- **Goldleaf version**: [ 0.5 and 0.8 ]

- **Goldtree version**: [ 0.5]

**Comment by XorTroll** [comment]
#578
