### ISSUE TITLE
Error code : 0x00234a02

### ISSUE THREAD

**Issue by Splixou** [XorTroll/Goldleaf#59]
Hi,

Everytime i try to install any NSP, i got the error code : 0x00234a02
Tinfoil 0.2.0
5.1.0 reiNX
20gb free on SD card
12 gb free on NAND.

Any clue ? 
Thx

**Comment by Adubbz** [comment]
That error means the NCA is corrupted. It usually means the NCA is actually corrupted, or fs_mitm is causing issues.

**Comment by wfriesen** [comment]
I'm seeing this on the latest Kosmos bundle. For me it seems to be a file system issue, since a network install of the same NSP works fine.

**Comment by wibuf** [comment]
I am seeing this as well with multiple, valid NSPs. Not sure what's causing it.

**Comment by XorTroll** [comment]
You mean old Tinfoil or Goldleaf?
