### ISSUE TITLE
Error en Quark y goldleaf

### ISSUE THREAD

**Issue by CypherNoodle** [XorTroll/Goldleaf#591]
# Quark 0.4 sigue sin guardar directorio y goldleaf intercambia nombres de archivos.
## Bug description
Al agregar directorio en Quark 0.4 este no aparece en la consola ni se guarda. Por otro lado al usar la nueva versión, intercambia los nombres de los nsp. 

Antes que nada agradecer por seguir dandole soporte a Goldleaf, no lo cambio por ningun otro, para el primer bug, solo basta con abrir Quark 0.4 y darla a PATH y escoger un directorio al azar y este no lo recordara.
Para le bug de los nombres, si en una carpeta posee en juego y su actualizacion, dentro del explorador de archivos de goldleaf, el que posee el nombre de la actualización es en realidad el juego y viceversa
## Your setup

- **Console firmware**: 11.0.1

- **CFW with version**: Atmosphere 0.18.0

- **Goldleaf version**:  0.9 prerelease

- **Goldtree version**: 0.4.0

## Bug reproduction

-Abrir Quark
-Clickear en Path y escoger directorio
-ester no lo guarda.

- Explorar pc con goldleaf
- ingresar a una carpeta con un juego y su update
- ver como itercambia los nombres de los archivos (verificando el peso de este)

**Comment by XorTroll** [comment]
He estado probando ambas cosas varias veces y todo funciona adecuadamente, los nombres de los archivos se corresponden a los propios archivos y Quark guarda correctamente los paths creados.

**Comment by CypherNoodle** [comment]
Creo que entonces debe ser por mi versión de Java 15
