### ISSUE TITLE
Can't install nsp with quark

### ISSUE THREAD

**Issue by Meltou69** [XorTroll/Goldleaf#595]
# Can't install nsp with Quark 

## Bug description

When I try to install any nsp with Quark, the installing bar show up but it doesn't fill up (also the time clock on goldleaf stops when it start installing)

## Your setup

- **Console firmware**: 11.0.1

- **CFW with version**: ams 0.18.1

- **Goldleaf version**: 0.9.0 (applet)

- **Goldtree version**: 0.4 (quark-j9.jar)

## Bug reproduction

-Open hbmenu then open goldleaf
-Open quark
-Browse files with goldleaf and select a nsp to install
-The installing bar pops up then the screen freezes (i can still go back to home menu)

## Additional information

It is not a space problem since it happens when i try to install on my switch memory and on the sd card (they both have space left), i also tried reinstalling java and quark but u can send me a link maybe i didn't get the good version (im on windows 8.1 x64) 
here's some pictures (sorry for the quality i wrote this on my phone)
![20210301_181615](https://user-images.githubusercontent.com/79863555/109533268-53996680-7aba-11eb-86bc-a925e560ae78.jpg)
I tried to install animal crossing on the switch memory
![20210301_181640](https://user-images.githubusercontent.com/79863555/109533274-54ca9380-7aba-11eb-8f00-021cc2950c78.jpg)
I tried to install VA-11 Hall-A on the sd card
![20210301_181409](https://user-images.githubusercontent.com/79863555/109533277-55632a00-7aba-11eb-91d5-0824ec5d8b1c.jpg)
quark logs taken at 18:13 (so it stopped writing 5min ago)

**Comment by lookye** [comment]
Did you try another usb port **and** another usb cable?

**Comment by Meltou69** [comment]
apprently the problem just solved itself ¯\_(ツ)_/¯ 
everythings working perfectly i guess it was my cable 
also if Xortroll sees this i suggest to add the possibility to chose the color instead of a random color, I got some flashy green that made it hard to read the files names (and some people are colorblind tho)

**Comment by Ammako** [comment]
> also if Xortroll sees this i suggest to add the possibility to chose the color instead of a random color, I got some flashy green that made it hard to read the files names (and some people are colorblind tho)

> Goldleaf supports the customization of colors, assets and other options via a JSON file located at Goldleaf's folder: `sd:/switch/Goldleaf/settings.json`.
