### ISSUE TITLE
Error code : 2345-0037 when Goldleaf start

### ISSUE THREAD

**Issue by bebentheturtle** [XorTroll/Goldleaf#599]
# [ Error code : 2345-0037 when Goldleaf start  ]

## Bug description

I have updated atmospher and switch consol by "AIO switch updater" and since when I try to start Goldleaf, an error message appear with the code 2345-0037. If I try to start a 2nd time Goldleaf, Atmosphere crash and make an error report.

## Your setup

- **Console firmware**: [ 11.0.1 ]

- **CFW with version**: [ AMS M 18.1 ]

- **Goldleaf version**: [ 0.9 ]

- **Quark version**: [ ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots.
[01615710498_010029b0118e8000.log](https://github.com/XorTroll/Goldleaf/files/6178161/01615710498_010029b0118e8000.log)
[01616346503_010000000000100d.log](https://github.com/XorTroll/Goldleaf/files/6178162/01616346503_010000000000100d.log)

 ]

**Comment by bebentheturtle** [comment]
I tried to reinstall Atmosphere + hekate + sigpatch manualy but I always have the same problem.

**Comment by bebentheturtle** [comment]
I can fix this by deleting the 010000000000bd00 folder on /atmosphere/contents.

**Comment by yang12313** [comment]
I have the same issue when upgrade edison using homebrew app. I tried to delete the folder whose name is shown on the crash screen and the problem solved!
