### ISSUE TITLE
ERROR 2145-0001

### ISSUE THREAD

**Issue by piero8783** [XorTroll/Goldleaf#601]
I AM USING THE LATEST VERSION OF ATMOSPHERE 0.19.0. I WANTED TO ENTER A GAME BUT IT APPEARED TO ENTER AGAIN FROM HOME. MAYBE TO INSTALL THE GAME AGAIN BUT I APPEARED AN ERROR 2145-0001 THAT I WOULD BE MISSING TO BE ABLE TO START THE GAME .. HELP ME PLEASE.

**Comment by lookye** [comment]
No need for Capslock, also please use the issue template and fill it completely out if you create a new issue.
