### ISSUE TITLE
Goldleaf does not install or can use the internet sucks like the last version..

### ISSUE THREAD

**Issue by Brandon6565** [XorTroll/Goldleaf#605]
nsp files always give an error I believe the error code is 2451-0001
xci are known as text files it does not install them
internet browser crashes.
the previous version of goldleaf 0.8.0 crashed before showing a screen

I am using atmosphere 1.9.0.1
hekate 5.5.5
version 1.2.0.0

app does nothing it installs nothing.

**Comment by lookye** [comment]
1. You didnt used the issue template.
2. "error code is 2451-0001" you´re missing sigpatches
3. "xci are known as text files" xci is not supported
4. Browser worked fine too (tested via titleoverride

**Comment by Brandon6565** [comment]
> 1. You didnt used the issue template.
> 2. "error code is 2451-0001" you´re missing sigpatches
> 3. "xci are known as text files" xci is not supported
> 4. Browser worked fine too (tested via titleoverride

actually error code 2145-0001

**Comment by lookye** [comment]
Even then, youre missing sigpatches. Stuff works fine.
