### ISSUE TITLE
Unable to access jarfile Quark.jar

### ISSUE THREAD

**Issue by PexoHundido69** [XorTroll/Goldleaf#608]
followed all the steps in the installation guide (https://github.com/XorTroll/Goldleaf/blob/master/Quark.md). When running  `java -jar Quark.jar`  in terminal I get the message "Unable to access jarfile Quark.jar"

Ubuntu 20.04.2 LTS

**Comment by lookye** [comment]
You know how to use terminal to execute files? You need to `cd` the folder where quark.jar is located beforehand or do `java -jar patch_to_quarks_folder/Quark.jar`.
