### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by devomaa** [XorTroll/Goldleaf#612]
# Error while building

## Bug description

It errors when I try to build (as you see I have no idea what to put here)

## Your setup

- **Console firmware**: //

- **CFW with version**: //

- **Goldleaf version**: //

- **Quark version**: //

## Bug reproduction

1. Clone Goldleaf Repo.
2. (also get dependencies)
3. Run `make all`.
4. Get error.

## Additional information

<details>
<summary>Log</summary>

```c
make[1]: Entering directory '/home/me/Goldleaf/Plutonium'
make[2]: Entering directory '/home/me/Goldleaf/Plutonium/Plutonium'
make[3]: '/home/me/Goldleaf/Plutonium/Plutonium/Output/lib/libpu.a' is up to date.
make[2]: Leaving directory '/home/me/Goldleaf/Plutonium/Plutonium'
make[1]: Leaving directory '/home/me/Goldleaf/Plutonium'
make[1]: Entering directory '/home/me/Goldleaf/libusbhsfs'
release
usbhsfs_drive.c
In file included from /home/me/Goldleaf/libusbhsfs/source/usbhsfs_drive.h:20,
                 from /home/me/Goldleaf/libusbhsfs/source/usbhsfs_request.h:15,
                 from /home/me/Goldleaf/libusbhsfs/source/usbhsfs_drive.c:11:
/home/me/Goldleaf/libusbhsfs/source/ntfs-3g/ntfs.h:17:10: fatal error: ntfs-3g/config.h: No such file or directory
   17 | #include <ntfs-3g/config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/opt/devkitpro/devkitA64/base_rules:19: usbhsfs_drive.o] Error 1
make[1]: *** [Makefile:142: lib/libusbhsfs.a] Error 2
make[1]: Leaving directory '/home/me/Goldleaf/libusbhsfs'
make: *** [Makefile:6: all] Error 2
```

</details>

**Comment by Masamune3210** [comment]
you are missing part of ntfs3g or missed a step, it's looking for a file that you are missing. make sure you pulled in all files correctly

**Comment by devomaa** [comment]
i cloned correctly, this is also happening in gh actions

**Comment by lookye** [comment]
As the error shows, you´re missing ntfs-3g in devkitpro, Read up on [here](https://github.com/DarkMatterCore/libusbhsfs) how to set up/compile libusbhsfs to be ready for Goldleaf.
