### ISSUE TITLE
Error 2145-0001 (0x291) ETickets (145) - Atmosphere 12.0.3 - newest sigpatches installed (I think so)

### ISSUE THREAD

**Issue by daniel-neuberger28** [XorTroll/Goldleaf#613]
Error 2145-0001 (0x291) ETickets (145) - Atmosphere 12.0.3 - newest sigpatches

Hello dear community,
This is my first post and I hope I'm doing everything right. 

The other posts that I have found on Google on the subject are a bit older and unfortunately solve none to few problems for me.

If this is the wrong place to start, please let me know where else I can look for solutions.

- Console firmware: 12.03
- CFW with version: Atmosphere M.19.4|S
- Goldleaf version: 0.9.0

I got the latest version of Atmosphere here:
- https://www.reddit.com/r/SwitchHacks/comments/nv6ncy/atmosphere_0194_released_1203_support/

- https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.19.4

I mixed the files from sdsetup.com with the files from "atmosphere-0.19.4-master-2ab01ad3+hbl-2.4.1+hbmenu-3.4.0.zip" and had to run hakate to fix the bits. So my switch won't boot at all with the CFW if I haven't fixed the bits on hakate first or whatever. I did that then and booted the fusee-primary from the one link.

I did it, I'm now in the CFW, but I just can't get it to install the games (NSP files).

Can anyone here help me with this?
![Error 2145-0001 (0x291) ETickets (145)](https://user-images.githubusercontent.com/63915763/121924085-de396500-cd3b-11eb-9490-807426d23a71.jpeg)

I have often read that you need the new sigpatches for this.
I have then also moved these to my SD folder.

I tried these:
- https://github.com/ITotalJustice/patches/releases

And this one: 
https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-primary-fusee-secondary.571543/

But somehow neither of them helped.
I also "mixed" the two, but that didn't help either.
Same error.

Who can help me with this?
I desperately need help and am getting desperate.

I am grateful from the bottom of my heart to anyone who can help me. 

However, I ask for detailed answers, as I am slow on the uptake and do not understand things directly.

Kind Regards

**Comment by lookye** [comment]
The github issue tracker is for technical/program issues. 

You´re missing the correct sigpatches for your version of atmosphere (it got shadow updated shortly after its latest release). Also, if youre booting via a hekate boot config, you need additional patches for hekate. Please seek for additional help on gbatemp or somewhere else on how to apply them correctly.

**Comment by daniel-neuberger28** [comment]
> The github issue tracker is for technical/program issues.
> 
> You´re missing the correct sigpatches for your version of atmosphere (it got shadow updated shortly after its latest release). Also, if youre booting via a hekate boot config, you need additional patches for hekate. Please seek for additional help on gbatemp or somewhere else on how to apply them correctly.


Hello, I would like to thank you for your feedback, thank you.

"You're missing the correct sigpatches"
- that means I need different sigpatches, right?

Where do I get the correct ones?
What is "shadow updated"?

"Also, if youre booting via a hekate boot config, you need additional patches for hekate. "
Why do I need additional patches for hekate?`

What is "gbatemp"?
So did I post my question here somewhere wrong?

If you google "Error 2145-0001 (0x291) ETickets (145)"
you will find a lot of people who have posted this exactly as I have posted it.

Unfortunately, I didn't quite understand what you meant.
Unfortunately, I'm not that good at understanding things.

Could you give me a little step by step guide on what I need to do to fix the bug? That would help me so much.

Thank you for your efforts.

Kind regards

**Comment by daniel-neuberger28** [comment]
> The github issue tracker is for technical/program issues.
> 
> You´re missing the correct sigpatches for your version of atmosphere (it got shadow updated shortly after its latest release). Also, if youre booting via a hekate boot config, you need additional patches for hekate. Please seek for additional help on gbatemp or somewhere else on how to apply them correctly.

hello?

**Comment by Masamune3210** [comment]
One, dont post again just because people haven't immediately responded. If they are going to respond, its on their time schedule, not yours. 

Two, it seems like you have quite a bit of research and googling in your future as a lot of what you asked is very basic stuff that can easily answered simply with a google or two

**Comment by lookye** [comment]
Please seek help in gbatemp forum or dedicated discord server.
