### ISSUE TITLE
No inician juegos nuevos, tales como: Lost in Random y No more heroes 3

### ISSUE THREAD

**Issue by alexjrock** [XorTroll/Goldleaf#625]
## Bug description

Goldleaf permite instalar el juego, sin ningún error, el problema es que no inicia, siempre el error: "No se puede iniciar, archivos dañados, intente desde el menú Home" sea la versión base o con la actualización. 

Al parecer es un problema en el sistema de archivos, otras herramientas ya se están actualizando. 

Saludos

## Your setup

- **Console firmware**: 13.0.0

- **CFW with version**: Atmosphere 1.1.0

- **Goldleaf version**: 0.9

- **Quark version**: 0.4

**Comment by Borrajo** [comment]
estas usando un fowarder para acceder al goldleaf?
