### ISSUE TITLE
[Localization updated] Traditional Chinese strings for Goldleaf v0.10

### ISSUE THREAD

**Issue by qazrfv1234** [XorTroll/Goldleaf#636]
Hello,
the attachment for Goldleaf v0.10  (base on the latest en.json )

[zh-hant.zip](https://github.com/XorTroll/Goldleaf/files/8141556/zh-hant.zip)

Many thanks,
Leo

**Comment by XorTroll** [comment]
Thanks (sorry for reading it a bit late)
To fully support a new language I also need the translations under /Modules and /Results (you only provided the /Strings one)
I'll default them to english for now

**Comment by qazrfv1234** [comment]
oops! sorry,I forgot it! 
[zh-hant.zip](https://github.com/XorTroll/Goldleaf/files/8494428/zh-hant.zip)

**Comment by XorTroll** [comment]
Alright, thanks ;)
