### ISSUE TITLE
Just add the option to stop changing colors everytime

### ISSUE THREAD

**Issue by everyonesweird** [XorTroll/Goldleaf#638]
# [ Feature name or title ] Tiltle says all. Im pissed off. Why do we even need random colors.? And don't tell me to edit the json file. Just disable it or add an option to disable it on the settings tab.

**Comment by Masamune3210** [comment]
Hey, just edit the JSON file

**Comment by XorTroll** [comment]
Literally writing this issue takes more time than editing the config JSON, lol
