### ISSUE TITLE
"Install all NSPs" extra option broken

### ISSUE THREAD

**Issue by Bramard** [XorTroll/Goldleaf#642]
# "Install all NSPs" extra option broken

## Bug description

When select "Install all NSPs" extra option and chooses "SD card", all .nsp files are actually installed on system console memory and not on the sd card.

## Your setup

- **Console firmware**: 14.1.0

- **CFW with version**: Atmosphere 1.3.1 (emuNAND)

- **Goldleaf version**: 0.10

- **Quark version**: 0.5

## Bug reproduction

On a folder containing several .nsp files, press 'Y', then select "Extra options".
Select "Install all NSPs", then select "SD card".

## Additional information

I noticed this behaviour since "0.9 dev" version with quark 0.4.

**Comment by XorTroll** [comment]
Indeed, one of my rewrites created this issue, fixed it in this last commit

**Comment by Bramard** [comment]
Thank you for the fast fix, keep up the good work <3
