### ISSUE TITLE
A bug with extra options / install all NSP's

### ISSUE THREAD

**Issue by gataka85** [XorTroll/Goldleaf#643]
# [ Bug report title ]

A bug when using external USB HDD and the option extra options / install all NSP's

## Bug description

I am installing games from external USB HDD with type-c adapter. The option extra options and install all NSP's is not working correctly. There are two options where to install the content - Sd card and Console memory. What ever i choose it always install on Console memory ! The option to install on Sd card is never working.

## Your setup

Nintendo Switch V1 and 2TB USB HDD on NTFS and type-c to USB adapter.

- **Console firmware**: [ e.g. 5.1.0, 6.2.0, 7.0.1 ]
Diferent consoles on firmware 14.0 and 14.1
- **CFW with version**: [ e.g. Atmosphere 0.18.1 ]
[Atmosphère 1.3.1](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.3.1)
- **Goldleaf version**: [ e.g. 0.8, 0.9 (nightly) ]
0.10
- **Quark version**: [ e.g. 0.4 ]
N/A

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by XorTroll** [comment]
This was already pointed out and one of the last commits fixed it, next release will include the fix

**Comment by gataka85** [comment]
Thank you.
