### ISSUE TITLE
2145-0001 (0x291) - Error when installing an NSP

### ISSUE THREAD

**Issue by UntitledOutput** [XorTroll/Goldleaf#648]
# [ Error when installing an NSP ]

## Your setup

- **Console firmware**: [ 14.1.2 ]

- **CFW with version**: [ Atmosphere 1.3.2]

- **Goldleaf version**: [ v0.10 ]

- **Quark version**: [ N/A ]

## Bug reproduction

Go into Goldleaf, and install an NSP via SD-Card

## Additional information

Game: Splatoon 2 (Base Game)

**Comment by UntitledOutput** [comment]
I have all the latest sigpatches too

**Comment by lookye** [comment]
Dupes of #630 #613 #601 and so on.
You may have not applied all patches correctly.

Please seek support/help on discord as github issues meant for support.
