### ISSUE TITLE
MTP responder

### ISSUE THREAD

**Issue by DraconicNEO** [XorTroll/Goldleaf#650]
# MTP responder feature

## a mode where you can connect the Switch to your PC vis USB to access the Files on the System.

A mode accessable from the main menu where you can connect the Switch to your computer to access, copy, modify, and delete files to and from the SD card, as well as the System memory locations, and the Gamecard slot.
Another thing this could be able to do is to allow directly installing NSP and XCI from PC.

## Benefits

- Allows easy SD card access on PC
- Allows easily backing up Saves to PC
- Allows browsing System Storage on PC
- Allows easily backing up cartridges to PC
- Allows installing NSP and XCI from PC

## Additional information

N/A

**Comment by XorTroll** [comment]
Already supported via Quark/USB
Regarding an actual MTP responder, other homebrew projets already exist implementing it

**Comment by DraconicNEO** [comment]
> Already supported via Quark/USB Regarding an actual MTP responder, other homebrew projets already exist implementing it

Ah I see, well that's too bad. Thanks anyway.
