### ISSUE TITLE
Remove title confirmation bug

### ISSUE THREAD

**Issue by GabriPir1003** [XorTroll/Goldleaf#651]
# Remove title confirmation bug

## Bug description

In Manage console contents/NAND USER/[Title name]/[Base title,update or DLSs]/Remove, if you click yes or cancel Goldleaf will remove in anyway.

## Your setup

- **Console firmware**: 14.1.2

- **CFW with version**: Atmosphere 1.3.2

- **Goldleaf version**: 0.10 (pre-release)

- **Quark version**: 0.5

## Sorry for bad English

**Comment by XorTroll** [comment]
Not entirely sure when, but this was fixed
