### ISSUE TITLE
Amiibo .bin dump to Emuiibo

### ISSUE THREAD

**Issue by SuperMario20** [XorTroll/Goldleaf#653]
Dump amiibo bin to Emuiibo

This would be a very useful feature as amiibo bin files can be edited whereas Emuiibo cannot be in the same way.

I've had an amiibo that I had to dump to a bin in order to make some changes to it and save it back.
For an Emuiibo, this cannot be done. The only way would be to have a .bin file of the amiibo and edit it, then somehow convert it to Emuiibo which is not currently something I've heard of. 

If amiibo dumping to emuiibo format is possible, would amiibo .bin dumping to emuiibo format be possible in the same way?

**Comment by XorTroll** [comment]
Not quite, since the console's amiibo services only provide certain fields and not access to the raw data
Goldleaf already tries to dump as much as it can

**Comment by XorTroll** [comment]
I guess I could look into generic NFC services tho
