### ISSUE TITLE
Error installing nsp

### ISSUE THREAD

**Issue by Linasviel** [XorTroll/Goldleaf#657]
# [ Bug report title ]

## Bug description

Hi  recently there are some nsps that are made in a new format so when you try to install them gaves you the following error:

error: 2356-0002 (0x564)
module: goldleaf (356)
description:no metadata NCA found in the NSP (2)

As appear the homebrew need a new update app to make it compatible

## Your setup

- **Console firmware**: [ e.g. 5.1.0, 6.2.0, 7.0.1 ]
- 15.00

- **CFW with version**: [ e.g. Atmosphere 0.18.1 ]
- Atmosphere 1.4.0

- **Goldleaf version**: [ e.g. 0.8, 0.9 (nightly) ]
- 0.10

**Comment by Ramazottel** [comment]
did you fix it?

**Comment by XorTroll** [comment]
This should no longer be an issue, as of recent commits
