### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by impeeza** [XorTroll/Goldleaf#668]
# Bug description

Since commit 892e7cfa53ca6bc9e4c70df66800e041540bba59 the libnx submodule was removed but the actual Makefile still looks for the LibNX module on root of the GoldLeaf repo. Is this a error or a new design using the LibNX pacman module?

**Comment by XorTroll** [comment]
Oh yeah I didn't notice, I only removed libnx/ references from the non-initial make procedures, will fix this ;)

**Comment by impeeza** [comment]
Thanks a lot buddy. Great work. Regards from Colombia

**Comment by R-YaTian** [comment]
I think this issue should be closed via [1391b9c](https://github.com/XorTroll/Goldleaf/commit/1391b9cab905359b2eab3bed16e75a1478403402)

**Comment by impeeza** [comment]
Hello there, thanks a lot for all your work, I just have a time and start a new MSYS enviroment from scratch and build the latest GoldLeaf and worked fine.

Again thanks a lot.
