### ISSUE TITLE
Installing DLC NSPs causes a "metadata NCA could not be located in the NSP" error

### ISSUE THREAD

**Issue by Sanrax** [XorTroll/Goldleaf#679]
# Installing DLC NSPs causes a "metadata NCA could not be located in the NSP" error

## Bug description

Using Goldleaf to install an nsp containing DLC just throws up an error rather than installing. Seems to happen specifically with DLC nsps. I can verify that the dlc nsp itself is fine and can be installed using other installers such as Awoo.

## Your setup

- **Console firmware**: 16.0.3

- **CFW with version**: Atmosphere 1.5.3

- **Goldleaf version**: 0.10.1

- **Quark version**: n/a

## Bug reproduction

Dump a DLC nsp, attempt to install it using Goldleaf from the sd card. The error shown below is thrown instead of the nsp being installed.

## Additional information

![2023060516481500-C8592A894EB1835410FE9249DA53FC8C](https://github.com/XorTroll/Goldleaf/assets/61475057/733b47ce-2787-4f01-935d-d447ab974521)

**Comment by AnythingVocaloid** [comment]
I have this exact problem and it's driving me INSANE.

**Comment by Sanrax** [comment]
> I have this exact problem and it's driving me INSANE.

Use Awoo Installer for now if you need an open source installer. It works fine for dlc nsps.

**Comment by XorTroll** [comment]
I'd ask you to try with the last testing build I posted on my [Discord server](https://discord.gg/3KpFyaH), since this issue should be fixed there

**Comment by Gudak0** [comment]
I tested the build from the discord on my switch and can confirm installing DLCs works with it

**Comment by XorTroll** [comment]
Last issue solved this

**Comment by Mysterious-Wrangler** [comment]
This issue is not fixed in the lastest version of goldleaf and with the latest atmosphere/firmware as of this date.
