### ISSUE TITLE
Deletion prompt after installation could cause accidentaly deleted files

### ISSUE THREAD

**Issue by dtrunk90** [XorTroll/Goldleaf#683]
# Add a setting or entirely remove the deletion prompt after installation

## Latest changes adding a deletion prompt after installation which is annoying and can lead to removing files if you choose ok by accident

This prompt should be entirely removed again or made configurable by adding a setting for that

## Benefits

No accidentaly deleted files

## Additional info

Might be [this change](https://github.com/XorTroll/Goldleaf/blob/09f68bb6ff822c460f5db0f9aedecbaab913aa9b/Goldleaf/source/ui/ui_InstallLayout.cpp#L476)

**Comment by XorTroll** [comment]
Yeah this was one of the cons I saw, but several users wanted this feature
Might consider some way to make it less risky

**Comment by XorTroll** [comment]
Last commit fixed it with a new setting and disabling it by default (less risky that way)
