### ISSUE TITLE
Error anytime I try and run usb_install_pc.py

### ISSUE THREAD

**Issue by oGamefreak** [XorTroll/Goldleaf#71]
Traceback (most recent call last):
  File "D:\Switch NSPs\usb_install_pc.py", line 27, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

**Comment by ThatNerdyPikachu** [comment]
Please read the script:
```py
# This script depends on PyUSB. You can get it with pip install pyusb.
# You will also need libusb installed

# My sincere apologies for this process being overly complicated. Apparently Python and Windows
# aren't very friendly :(
# Windows Instructions:
# 1. Download Zadig from https://zadig.akeo.ie/.
# 2. With your switch plugged in and on the Tinfoil USB install menu, 
#    choose "List All Devices" under the options menu in Zadig, and select libnx USB comms. 
# 3. Choose libusbK from the driver list and click the "Replace Driver" button.
# 4. Run this script

# macOS Instructions:
# 1. Install Homebrew https://brew.sh
# 2. Install Python 3
#      sudo mkdir /usr/local/Frameworks
#      sudo chown $(whoami) /usr/local/Frameworks
#      brew install python
# 3. Install PyUSB 
#      pip3 install pyusb
# 4. Install libusb
#      brew install libusb
# 5. Plug in your Switch and go to Tinfoil > Title Management > USB Install NSP
# 6. Run this script
#      python3 usb_install_pc.py <path/to/nsp_folder>
```

**Comment by oGamefreak** [comment]
I have all of that. I've even tried uninstalling python and then reinstalling it but I still get the "import usb.core" line 27 error.

**Comment by Melon-Bread** [comment]
_pip3 install pyusb_

**Comment by oGamefreak** [comment]
I'm aware. I've done that. Doesn't work.

**Comment by LittlestCube** [comment]
Are you running the script with `python3 usb_install_pc.py NSP_FILE`?

**Comment by UlisesAR** [comment]
Hi. I'm facing exactly the same issue as oGamefreak.

Followed the instructions.
Installed drivers on PC with Zadig. I see "USB is ready. Waiting for header..." in Switch's screen.

When I run usb_install_pc.py NSP_FILES_PATH i get the same error mentioned before. "... line 27, in <module> import usb.core. ModuleNotFoundError: No module named 'usb'"


oGamefreak, did you found the solution?

**Comment by UlisesAR** [comment]
Ok. I fixed the issue.

I was right clicking the *.py file and using "save as..."

What I did is:
- Click the .py file
- Click in "RAW"
- Save the RAW file instead.
- Success!!

I guess this issue can be closed now.
