### ISSUE TITLE
pleas add suport for usb install for linux

### ISSUE THREAD

**Issue by blackcaty1** [XorTroll/Goldleaf#78]
I get the following error message.

File "usb_install_pc.py", line 7
    <!DOCTYPE html>
    ^

system: Ubuntu 18

**Comment by jtraub** [comment]
It works on linux for me just fine.

Please provide more detailed steps to reproduce the problem.

**Comment by ferdianakbar** [comment]
> 
> 
> I get the following error message.
> 
> File "usb_install_pc.py", line 7
> 
> ^
> 
> system: Ubuntu 18

have you installed the library needed?

**Comment by sethreaver** [comment]
Works for me in Ubuntu 18.10.
I had to install pip with sudo apt install python3-pip
Then I used pip3 install pyusb 
Last I ran the python script with sudo python3 location-of-script location-of-nsps

**Comment by carlosen14** [comment]
> Works for me in Ubuntu 18.10.
> I had to install pip with sudo apt install python3-pip
> Then I used pip3 install pyusb
> Last I ran the python script with sudo python3 location-of-script location-of-nsps

when you say`location-of-script`, what script do you mean ? . I am not able to make it work
