### ISSUE TITLE
problems when installing by usb

### ISSUE THREAD

**Issue by Stive889** [XorTroll/Goldleaf#90]
first thank you for your contribution to the community, which has been great, I've had problems installing games via USB. the installation is completed but when entering the game it fails and the switch tells me that it has corrupt files. I have tried 10 different games and have tried to install them in the normal way and they work well. When you have a time please look at it. I'm in SX SO 2.0 and CFW 5.1.0

thanks for all.

**Comment by Stive889** [comment]
tanks works perfect now

**Comment by TripleKiller666** [comment]
B:\NintendoSwitchGames\Tools\usbfix>usb_install_pc.py B:\NintendoSwitchGames\Tools\usbfix
Traceback (most recent call last):
  File "B:\NintendoSwitchGames\Tools\usbfix\usb_install_pc.py", line 147, in <module>
    dev = usb.core.find(idVendor=0x057E, idProduct=0x3000)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

Anyway to fix this problem without messing with all those Python versions again?

**Comment by Seika-cha-la** [comment]
triplekiller666. ese error lo tenia yo, lo arregle instalando Windows desde cero, creeme lo intente todo, metiendo dlls en system32 y wow64 borrando Python reisntalando todas las versiones desde la 2.6 asta la 3.7.1 instalando los pip installer pyusb y pip installer libusb…

 *satelliteseeker* gracias este repo tuyo me funciono de maravilla.
